### ISSUE TITLE
Filtered format does not work with wiki tables

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticResultFormats#100]
From https://phabricator.wikimedia.org/T48107:
The result format "filtered" does not work using templates that try to display the resulting list in a table.

The list items are wrapped in a div with an id to be able to access and filter them. However, table rows in divs do not work.

http://www.verwaltungsinnovation.at/index.php?title=Test

**Comment by s7eph4n** [comment]
Tables are a peculiar kind of beast that needs specialized styling when hiding/showing entries. It is for example not possible to just set `display:none` to hide a line, as that would cause a re-layout of the table, i.e. the coluymn widths would change every time you show or hide an entry.

A specialized table view is available based on SRF 1.8 in https://github.com/s7eph4n/SemanticResultFormats/tree/table-view . I did not get around to porting it to current SRF versions yet.

**Comment by kghbln** [comment]
@s7eph4n Was this part of the recent refactoring of the "filtered" format? I do not think so since this relates to a "table" view.

**Comment by s7eph4n** [comment]
I don't think so, but considering that a table view exists now, I propose to close this as Won't fix.

**Comment by kghbln** [comment]
> I don't think so, but considering that a table view exists now, I propose to close this as Won't fix.

Ah, yeah, your right. In the meantime there is a "table" view to this format. So this probably got fluffed along the way, too. Thanks for the info.
