### ISSUE TITLE
Datatables format does not parse MW links

### ISSUE THREAD

**Issue by mitchelln** [SemanticMediaWiki/SemanticResultFormats#103]
The Datatables format does not parse properties that contain MW links.

For example, I have a text property called OpenLink which holds links to pages. Example values:

[[Some very long page name that looks ugly and confusing when displayed in full|A short page name]]
[[File:OpenPage.png|link={{PAGENAME}}]]

If I include OpenLink in the ask:

{{#ask:
[[Category:Articles]]
|?Title
|?Author
|?Updated
|?OpenLink
|mainlabel=-
|format=Datatables
}}

The OpenLink property is not rendered. 

This also means thumbnails and images cannot be displayed in the table. For example, if I have a property that holds a thumbnail e.g. [[File:Image1.png|80px]] then it is not rendered.

Should this be working, or is this an enhancement?

Thanks.

**Comment by mwjames** [comment]
> This also means thumbnails and images cannot be displayed in the table. For example, if I have a property that holds a thumbnail e.g. [[File:Image1.png|80px]] then it is not rendered.

Well, thumbnails and links do work for the example shown in [0], some parser specific rendering might not be supported which for the above examples would be classified as enhancements.

I personally don't have time to a look at this, so anyone is welcome to make a contribution.

[0] https://semantic-mediawiki.org/wiki/Demo:Datatables_compared_to_broadtable

**Comment by krabina** [comment]
This is solved in the latest version.
