### ISSUE TITLE
Datatables: Requested unknown parameter

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#105]
If one adds a full stop to the header title like e.g.

``` text
{{#ask:
 [[Category:Articles]]
 |?Title
 |?Author
 |?Updated=Upd.
 |?OpenLink
 |mainlabel=-
 |format=Datatables
}}
```

The follwing error is shown:
`table_id=Datatables_Table_0_ Requested unknown parameter nr. from the data source for row 0`

**Comment by mwjames** [comment]
My comment is similar as in [0], anyone is welcome to fix this but I won't have time for this.

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/103#issuecomment-102199908

**Comment by bogota** [comment]
The workaround below works for me, with the help of a new feature of DataTables 1.10 (http://datatables.net/reference/option/columns.data#string).

1. Get the latest stable release of DataTables at http://datatables.net/download/index . Unpack it and copy jquery.dataTables.js to SemanticResultFormats/resources/jquery/datatables , overwriting the old one.

2. Modify L225 of SemanticResultFormats/formats/datatables/resources/ext.srf.formats.datatables.js like this.
```
	aoColumnDefs.push( {
		'mData': property.label.replace(/\./g, '\\.'), //Modified, escaping periods.
		'sTitle': property.label,
		'sClass': 'smwtype' + property.typeid,
		'aTargets': [index]
	} );
```

**Comment by krabina** [comment]
This is related to an outdated version. Please test the current version and reopen should the error persist.
