### ISSUE TITLE
Fatal exception when trying to install SRF in addition to the SMW tarball release

### ISSUE THREAD

**Issue by SnowlDD** [SemanticMediaWiki/SemanticResultFormats#109]
We've installed Semantic Result Formats 2.1.1, but it ends with a "Fatal exception of type MWException" error.

Using 
MediaWiki 	1.23.9
PHP 	5.5.9-1ubuntu4.9 (cgi-fcgi)
MySQL 	5.5.43-0ubuntu0.14.04.1
Semantic Forms	3.2
Semantic MediaWiki	2.2

Wiki and all extensions installed by our administrator.
Installation without composer, doesn't work on our server, everything works fine but SemanticResultFormats.

The wiki is not open, but I can give you access. Please send mail to klaus@hoogestraats.de.

Thanks for your support.

Sincerely
Klaus

**Comment by mwjames** [comment]
[0] is rather clear about the details required to help with an analysis of an issue. To narrow down the issue for something like "Fatal exception of type MWException" a stack trace [1] is the first step towards a potential solution.

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/CONTRIBUTING.md#reporting-an-issue

[1] https://semantic-mediawiki.org/wiki/Help:Identifying_bugs

**Comment by SnowlDD** [comment]
Thanks for your very quick response. Here is the result of the stack trace:

error_reporting(E_ALL | E_STRICT); ini_set("display_errors", 1);

[f6bf161b] /dev_isw/index.php?title=Spezial:Version Exception from line 182 of /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/Hooks.php: Invalid callback in hooks for ParserFirstCallInit

Backtrace:

#0 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/GlobalFunctions.php(4013): Hooks::run(string, array, NULL)
#1 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/parser/Parser.php(275): wfRunHooks(string, array)
#2 [internal function]: Parser->firstCallInit()
#3 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/StubObject.php(99): call_user_func_array(array, array)
#4 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/StubObject.php(119): StubObject->_call(string, array)
#5 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/cache/MessageCache.php(1023): StubObject->__call(string, array)
#6 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/cache/MessageCache.php(1023): StubObject->firstCallInit()
#7 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/cache/MessageCache.php(1000): MessageCache->getParser()
#8 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/Message.php(977): MessageCache->transform(string, boolean, Language, Title)
#9 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/Message.php(669): Message->transformText(string)
#10 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/Message.php(732): Message->toString()
#11 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/OutputPage.php(855): Message->text()
#12 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/OutputPage.php(901): OutputPage->setHTMLTitle(Message)
#13 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/specialpage/SpecialPage.php(357): OutputPage->setPageTitle(string)
#14 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/specials/SpecialVersion.php(57): SpecialPage->setHeaders()
#15 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/specialpage/SpecialPage.php(379): SpecialVersion->execute(NULL)
#16 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/specialpage/SpecialPageFactory.php(503): SpecialPage->run(NULL)
#17 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/Wiki.php(285): SpecialPageFactory::executePath(Title, RequestContext)
#18 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/Wiki.php(588): MediaWiki->performRequest()
#19 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/Wiki.php(447): MediaWiki->main()
#20 /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/index.php(46): MediaWiki->run()
#21 {main}

**Comment by SnowlDD** [comment]
With the master of SRF we had the same problems...

**Comment by mwjames** [comment]
> [f6bf161b] /dev_isw/index.php?title=Spezial:Version Exception from line 182 of /var/www/vhosts/itmservicewiki.eu/httpdocs/dev_isw/includes/Hooks.php: Invalid callback in hooks for ParserFirstCallInit

Well, I was hoping to see a SMW or SRF related namespace that would point towards a SMW or SRF related class but above does not include any pointer towards SRF or SMW therefore I'm unable to determine the cause.

> Installation without composer, doesn't work on our server, everything works fine but 

@kghbln Apparently composer isn't used, any idea whether this causes some sort of issue when SRF is installed manually?

**Comment by kghbln** [comment]
If the tarball release of SMW is used one cannot use any further semantic extension which requires Composer imperatively, e.g. SRF. So the way out it to install SMW and related extensions on a machine with can make use of Composer and move over the code.

**Comment by SnowlDD** [comment]
Hi Karsten and hello from Dresden to Berlin,

for further comments i will onwards write in english .

Thanks for your quick answer even when this is not, what i hoped to hear :-( 

I think it will be possible to install composer on our Server, but installation sounds very complicated. So, is it possible that you give me initial aid?

Best regards
Klaus

**Comment by kghbln** [comment]
Hi Klaus from Dresden. :)
Composer is not hard to install at all. It is indeed just a matter of executing [the commands as described](https://getcomposer.org/doc/00-intro.md#globally) Do the global install which makes things easier.
Cheers Karsten

**Comment by SnowlDD** [comment]
Hi Karsten,

well i'll try it tomorrow. By the way: we build enterprise wikis, let me known if this could be interesting for you. My enterprise mail address is klaus.hoogestraat@itm-dl.de. There we can talk in german ;-)

best regards
Klaus

**Comment by kghbln** [comment]
I am sure it will work out. I worked a bit on the help page on [Composer](https://semantic-mediawiki.org/wiki/Help:Composer) to have a reference for other people this this kind of worry. We'll stay in touch.
