### ISSUE TITLE
"Pagewidget" format also transcludes properties and subobjects

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticResultFormats#110]
For details, see the bug report over at Semantic MediaWiki: 

"'Embedded' format also transcludes properties and subobjects Semantic MediaWiki" https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1076

The same issue seems to hold true for the pagewidget format, too.

**Comment by mwjames** [comment]
"Pagewidget" derives from the "Embedded format" and faces the same https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1076 which is solved by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1068.
