### ISSUE TITLE
max seems not work for e.g. text

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticResultFormats#111]
https://semantic-mediawiki.org/wiki/Help_talk:Max_format#Test_for_max_1850

**Comment by mwjames** [comment]
Match functions (including max) are only suppose to work with numerical values, for details see [0]

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/formats/math/SRF_Math.php#L44-L71.

**Comment by WolfgangFahl** [comment]
see #112 - i was wondering where the issue was gone while if fixed it. I don't think Math functions should only work with numbers. Getting max of A/B/C is a perfectly valid use case.

**Comment by kghbln** [comment]
The [documentation](http://www.semantic-mediawiki.org/wiki/Help:Max_format) on smw.o is in line with current behaviour.
