### ISSUE TITLE
Tagcloud: Fatal error when running rebuildData.php

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticResultFormats#116]
When running rebuildData.php -v, I get:

```...
 (455/15231 3%) Processing ID 456 ...
 (456/15231 3%) Processing ID 457 ...
 (457/15231 3%) Processing ID 458 ...
 Fatal error: Call to a member function isSpecialPage() on a non-object in 
 /extensions/SemanticResultFormats/formats/tagcloud/TagCloud.php on line 80
```
And the process of rebuilding stops.

Details:
SMW: ~2.3@dev
SRF: @dev
MW: 1.25.1

**Comment by mwjames** [comment]
I can't really make something out of it because according to [0] `$this->getTitle() instanceof Title && $this->getTitle()->isSpecialPage()` is checked to be of a `Title` instance before accessing `isSpecialPage`.

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/formats/tagcloud/TagCloud.php#L80

**Comment by JeroenDeDauw** [comment]
> on a non-object

That part implies that null is returned in the second getTitle call.

**Comment by JeroenDeDauw** [comment]
In #117 I changed the code so getTitle is only called once

**Comment by jaideraf** [comment]
@JeroenDeDauw 
I tested, ```rebuildData.php``` works fine, now.
Thank you! :+1:

**Comment by mwjames** [comment]
@jaideraf I'm bit puzzled about what is display on your `Special:Version` [0] which shows 

```
Semantic Result Formats 2.2 (fc1fb9c) 18:25, 16 January 2014
```

but release 2.2 [1] should have sha1 `885e76e` and not `fc1fb9c`.

[0] http://wikincat.org/wiki/Especial:Vers%C3%A3o

[1] https://github.com/SemanticMediaWiki/SemanticResultFormats/releases

**Comment by jaideraf** [comment]
@mwjames I do not understand this, either. What I did:

I put ```"mediawiki/semantic-result-formats": "dev-TagCloud"``` into my ```composer.local.json``` ("TagCloud" from [here](https://github.com/SemanticMediaWiki/SemanticResultFormats/branches)).
I run ```composer update```.
And, for the test, I run ```rebuildData.php -v```.
Just that.
Why is showing ```Semantic Result Formats 2.2 (fc1fb9c) 18:25, 16 January 2014``` I do not know.

**Comment by mwjames** [comment]
Since non of us knows as to what is wrong I'd suggest to run `composer remove mediawiki/semantic-result-formats` and add it again `composer require mediawiki/semantic-result-formats:~2.2` and hopefully `Special:Version` will show the correct version.

**Comment by jaideraf** [comment]
Actually, I cannot run ```composer remove mediawiki/semantic-result-formats``` in MW 1.25 series, right?
When I run in it, I get: 
```mediawiki/semantic-result-formats is not required in your composer.json and has not been removed```
(because it is in ```composer.local.json``` instead of ```composer.json```, as stated in [0], I think).
So I have to edit, manually, the ```composer.local.json``` file.
(we know, MW sucks changing composer behavior all the time in the last versions, and when I install something with ```composer require ...``` the extension is going to the standard ```composer.json```, driving me mad)

Anyway, I deleted the SRF directory, I removed SRF require statement from ```composer.local.json```, 
I run  ```composer update``` and I run:
```
composer require mediawiki/semantic-result-formats "~2.2"
./composer.json has been updated
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mediawiki/semantic-result-formats (2.2)
    Loading from cache

mediawiki/semantic-result-formats suggests installing mediawiki/graph-viz (Required for 'format=graph')
Writing lock file
Generating autoload files
```

Well, **it did not work**.

0. https://www.mediawiki.org/wiki/MediaWiki_1.25#Better_support_for_composer-managed_extensions
