### ISSUE TITLE
Filtered format "list view introtemplate" doesn't like HTML formatting

### ISSUE THREAD

**Issue by ckoerner** [SemanticMediaWiki/SemanticResultFormats#121]
I've tried `<span>` and `<table>` tags in an attempt to create a 'header' of sorts for my filtered results using 'list view introtempalte'. Plain, unformatted text seems to be ok.

When I do so, I can see my list of filters, and default results from my query. As soon as I click a radio button, my list filters, but then I can no longer filter further. Deselecting a filter checkbox does not reset the filter.

In the console I see:

```
Uncaught TypeError: Cannot read property 'data' of undefinedmethods.isVisible 
@ ext.srf.filtered.js:312$.fn.filtered 
@ ext.srf.filtered.js:320methods.updateAllItems
@ ext.srf.filtered.list-view.js:61listView
@ ext.srf.filtered.list-view.js:102methods.updateAllItems
@ ext.srf.filtered.js:270$.fn.filtered
@ ext.srf.filtered.js:320update
@ ext.srf.filtered.value-filter.js:35(anonymous function)
@ ext.srf.filtered.value-filter.js:267
```

MW 1.25, SMW 2.1, SRF 2.0

See also #100, which may be related.

**Comment by s7eph4n** [comment]
Don think #100 is related.

**Comment by kghbln** [comment]
@s7eph4n Was this part of the recent refactoring of the "filtered" format?

**Comment by s7eph4n** [comment]
Not specifically. Could be that it got fixed en passant, but not sure. @ckoerner, could you maybe give it a try?

**Comment by kghbln** [comment]
> Not specifically. Could be that it got fixed en passant, but not sure. @ckoerner, could you maybe give it a try?

Keeping fingers crossed. @ckoerner  Perhaps you could even set up an example on [sanbox](https://sandbox.semantic-mediawiki.org/wiki/Main_Page)

**Comment by s7eph4n** [comment]
@ckoerner I am provisionally closing the issue. Please re-open if this is still a problem. 
Of course, a demo of the bug e.g. on http://sandbox.semantic-mediawiki.org/ would be really appreciated in this case.
