### ISSUE TITLE
Tree format - Replicating results omitted in combination with template 

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticResultFormats#123]
On http://semantic-mediawiki.org/wiki/Help:Tree_format I tried to demonstrate the use of a template with the 'Tree' format, but something unexpected happened. 

Results which should appear a second time, or third, etc (because they are members of more than one list), are omitted from the tree. The bullets that would precede them are preserved but no value is printed. For instance, Stuttgart should appear twice: under both Baden-Württemberg and Demo:Germany, but it is not listed under the latter even if a bullet indicates where it should have been. 

<h3>Additional notes</h3>
- I tried the same query with named args but the outcome is the same
- In the example above, the "link=" parameter was set to "none"; the same behaviour is observed when the parameter is left out and the template's formatting of page links has been adjusted. 
- FWIW: I've seen examples of the tree format being used where some of the lower members of a hierarchy tree were not shown at all. No clue what could be the cause of this, unfortunately.

**Comment by kghbln** [comment]
My impression is that the example we had on smw.o without the template was working ok. Frankly I'd rather have a working example than a broken one. Perhaps it can be relocated to e.g. a subpage for the time being.

I see this more as an enhancement than a bug, however I may be wrong. I believe @s7eph4n introduced this result format so he may want to weigh in at this and reassess.

**Comment by Contrafibularity** [comment]
Fair point - amended accordingly. 

The template option is part of the official docs for this format, so I would say that the issue here is a bug rather than simply a wanting feature. 

To add the above, you'll find that without template formatting, Demo:New York turns up twice in the parent list, while with the template formatting applied to the list, the second item disappears (apart from the bullet and the dangling syntax). I didn't intend to squeeze three or more bugs into a single report, but perhaps they could all be related.

**Comment by kghbln** [comment]
Great, thank you. To have information in the docinfo table does not necessarily mean that the feature is actually supported. This table is not correct for other formats either. We could get into a philosophic discussion about if my assessment of this issue as an enhancement is correct or not but I guess that would be unnecessary extra talk. That's why I pinged @s7eph4n who indeed created this format. I believe he will understand this issue correctly and will relabel if applicable. :)

**Comment by gesinn-it** [comment]
... did you try using the limit parameter [1]?

[1] https://semantic-mediawiki.org/wiki/Help:Inline_queries#Result_limits_and_links_to_further_results

**Comment by Contrafibularity** [comment]
I certainly did - something like limit=1000, to be on the safe side.

**Comment by kghbln** [comment]
@s7eph4n Since you referenced the pull which was refactoring the "tree" format I believe that this issue was resolved. Thanks a lot for this, too. Again, much appreciated!

If I am for some reason mistaken it will we nice if you could reopen this issue report.
