### ISSUE TITLE
Tree format does not always produce sub-results

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticResultFormats#124]
Say that pages D1 and D2 are members of page C through a property like 'Member of'; likewise page C is a member of page B, and the hierarchy continues up to page A. Normally you can use the tree format to produce a tree like

<pre>
* A
** B
*** C
**** D1
**** D2
</pre>

The problem is that this does not always happen for some reason. Sometimes the sub-results are not shown.

I'll have to check more thoroughly but It is possible that this applies exclusively to pages that are members of more than one page - although not all pages that are members of multiple pages are necssarily affected. Could there be a connection to #123 ? 

To add
- This is true both with and without use of the template option. 
- Dummy edits do not help force pages to refresh their data and give appropriate results, so I don't think that a 'data lag' is responsible (then again, who knows)
- Unfortunately, I cannot show you a public example.

**Comment by kghbln** [comment]
@Contrafibularity Is this issue still happening. I started using the tree format a month ago and so far it is reliably showing the expected results. Also if you could provide info about your setup.

**Setup**
- MediaWiki	1.27.3 (798ceea) 21:03, 30 April 2017
- PHP	5.6.30 (cgi-fcgi)
- MySQL	5.6.28-76.1-log
- Semantic MediaWiki	2.5.2 (84007ca) 09:45, 17 May 2017
- Semantic Result Formats	2.4.2 (17be353) 17:13, 6 May 2017

**Comment by s7eph4n** [comment]
It is probablythe same issue as described in #204

**Comment by kghbln** [comment]
Then I am not sure why this works for me.

**Comment by s7eph4n** [comment]
Because you probably do not have any subtrees (i.e. not just leaves) appearing multiple times.

**Comment by kghbln** [comment]
> Because you probably do not have any subtrees (i.e. not just leaves) appearing multiple times.

Ah, ok.

**Comment by kghbln** [comment]
@s7eph4n Since you referenced the pull which was refactoring the "tree" format I believe that this issue was resolved. Thanks a lot for this. Much appreciated!

If I am for some reason mistaken it will we nice if you could reopen this issue report.

**Comment by s7eph4n** [comment]
Yes, this should be fixed. @Contrafibularity, maybe you could confirm.

**Comment by Contrafibularity** [comment]
I missed this, sorry! The new version (SF2.5.0) does not appear to be working as you'd expect:

https://www.semantic-mediawiki.org/wiki/Help:Tree_format/example_query

**Comment by kghbln** [comment]
https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/235 will ship with 2.5.1
