### ISSUE TITLE
2.3 release

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticResultFormats#129]
Tracking issue for the 2.3 release.

* [Release notes](https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/RELEASE-NOTES.md)
* [Changes since 2.2](https://github.com/SemanticMediaWiki/SemanticResultFormats/compare/2.2...master)

--

* [x] Finalize RELEASE NOTES
* [x] Update version number `SemanticResultFormats.php`
* [x] Update version number `README.md`
* [x] Update `INSTALL.md`
* [x] Create tag
* [x] Announce via mail
* [x] Do a release tweet on Twitter
* [x] Run `composer update` on smw.o

**Comment by kghbln** [comment]
I applied another tiny fix to "de.json". Apart from this we are cool. Release notes cover all changes and just needs a release date.

**Comment by kghbln** [comment]
Ping @JeroenDeDauw

**Comment by JeroenDeDauw** [comment]
All fine from my side

**Comment by kghbln** [comment]
Disaster struck me today so I guess it is one of these days for me. :| Probably I will do this either tonight or on Saturday afternoon. Thanks for your ok!

**Comment by kghbln** [comment]
@JeroenDeDauw It has all happened. :) I will do the release tweet tomorrow morning. So you could do the other honours now. :)

**Comment by JeroenDeDauw** [comment]
Oh, cool! By all means feel free to also do the email part.

**Comment by kghbln** [comment]
@JeroenDeDauw Ok, but I still need you to update the software on smw.o first

**Comment by JeroenDeDauw** [comment]
Done

**Comment by kghbln** [comment]
Thanks a bunch! Just send out the mail. Hopefully this one was fluffy. ;)
