### ISSUE TITLE
[Eventcalendar] Is changing from one month to another (< or >) suppose to query for events again?

### ISSUE THREAD

**Issue by johnnybaloney** [SemanticMediaWiki/SemanticResultFormats#130]
Hi,

```
Semantic MediaWiki	2.2.2
Semantic Result Formats	2.1.2
```

Is changing from one month view to another (using < or > buttons) suppose to trigger querying for events again? I cannot see that happening, only the initial batch of events gets displayed (for the current month with some spill to the previous month). I use the following settings based on what I have seen on the [Calendar Format](https://semantic-mediawiki.org/wiki/Help:Calendar_format) page:

```
{{#ask:
[[Has event::+]]
[[Has event start::>{{#calendarstartdate:}}]]
[[Has event start::<{{#calendarenddate:}}]]
|?Has event=title
|?Has event start
|?Has event end
|?Has event description=Description
|?Has event color=color
|?Has event location
|format=eventcalendar
|start=current
|defaultview=month
|limit=
|link=subject
|legend=pane
|firstday=Monday
|dayview=yes
|headers=hide
|theme=vector
}}
```

My previous setup had:

```
{{#ask:
[[Has event::+]]
[[Has event start::+]]
...
```

instead of the current range and I could see **all the events** since I started the calendar but then I reached the default 50 events limit. I could increase the limit but I thought the ranges solution would make events load separately for every month but since events are loaded only once this is not the case.

**Comment by mwjames** [comment]
> s changing from one month to another (< or >) suppose to query for events again?

No.

> since I started the calendar but then I reached the default 50 events limit. 

See above options to change the limit on-the-fly.

![image](https://cloud.githubusercontent.com/assets/1245473/10574855/f373f088-7658-11e5-8cf5-cd2ea8bd3b4d.png)

Feel free to test this on [0].

[0] http://sandbox.semantic-mediawiki.org/wiki/Recurring_events

**Comment by johnnybaloney** [comment]
Thank you for the confirmation and extra information.

I have my own instance running and for me the limit workaround is good enough, for now anyway, but I can imagine for someone with lots of events **who would like to keep the past events visible** in the calendar (perhaps not the use case this calendar was provided with in mind?) having a default limit set to 50 requires this value to be changed to something like 99999. This is a bit ugly, better to have no limit at all by default.

Is this limit enforced by the extension or the calendar plugin? I haven't seen anything to do with limiting the number of fetched events on the [FullCalendar plugin's page](http://fullcalendar.io/docs/display/).

**Comment by mwjames** [comment]
> Is this limit enforced by the extension or the calendar plugin?

```
|defaultview=month
|limit=
```

If you leave the limit blank then it will use [0] as default value otherwise you can choose an individual limit which is only bound by [1].

[0] https://semantic-mediawiki.org/wiki/Help:$smwgQDefaultLimit
[1] https://semantic-mediawiki.org/wiki/Help:$smwgQMaxInlineLimit
