### ISSUE TITLE
Jqplotseries (stacked) / system message "srf-error-jqplot-stackseries-data-length" missing

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#131]
Used [here](https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/6a38b2337f19c1963c1a1bc0af028c0da3a8cabd/formats/jqplot/resources/ext.srf.jqplot.chart.bar.js#L43) and [there](https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/6a38b2337f19c1963c1a1bc0af028c0da3a8cabd/Resources.php#L479) for checking if the data series has the same length. Just to make sure: does this mean that the queried properties I want to stack will have to have a value set. So if no result is returned by the query for e.g. "Has number" for any of the pages for the stack this message will be emitted?

```text
{{#ask:
 [[Demo::{{FULLPAGENAME}}]]
 |?Has label
 |?Has number
 |?Has market share=Has another number
 |?Has revenue
 |format=jqplotseries
 ...
}}
```

**Comment by mwjames** [comment]
> Just to make sure: does this mean that the queried properties I want to stack will have to have a value set. So if no result is returned 

According to [0], "Check if data series has the same length otherwise stackseries throws an error".

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/6a38b2337f19c1963c1a1bc0af028c0da3a8cabd/formats/jqplot/resources/ext.srf.jqplot.chart.bar.js#L43-L47

**Comment by kghbln** [comment]
I have read this, but what does this mean? May it be interpreted like I did? I am unsure what lenght means here.

**Comment by mwjames** [comment]
Looking at the code length is related the amount of elements which means if one column (Has number) returns 5 elements and another column (Has foo) returns only 4 then the stack went berserk and jqplot was throwing a JS error but to avoid this we check if the elements amount (length) is equal and if not we bail-out.

**Comment by kghbln** [comment]
Thanks for confirming, that's how I understood this. My wording was probably not the best of breed. I will move in a commit soon.
