### ISSUE TITLE
Thousands separator in math formats (English language MW)

### ISSUE THREAD

**Issue by jongfeli** [SemanticMediaWiki/SemanticResultFormats#135]
It seems that it is not possible to get a result from the **math** [0] formats without the thousands separator. With `{{#ask:...` or `{{#show:...` you can specify if the thousands separator should be in the result or not but this is not transferred to any of the math formats. There are no parameters documented [0]. This means that the results of these formats can not directly be used in the `{{#expr:...` parser function. If I could I would disable the thousands separator all together but that is not possible [1]. See example [2].

[0] http://www.semantic-mediawiki.org/wiki/Help:Sum_format
[1] http://www.semantic-mediawiki.org/wiki/Help:Type_Number#Numbers_in_other_languages
[2] http://sandbox.semantic-mediawiki.org/wiki/Thousands_separator

**Comment by kghbln** [comment]
Indeed, I just the NumberFormat extension to strip the results blanc. Yeah, there is plenty of room for improvement here.

**Comment by JeroenDeDauw** [comment]
This format uses MWs language number formatting (`$wgLang->formatNum`).

**Comment by kghbln** [comment]
Well, MW claims to be imperfect in this respect, too. This is about getting plain numbers and not formatted ones from a query if I am not mistaken.

**Comment by jongfeli** [comment]
> However, this issue is about getting plain numbers 

Yes that is correct. Our wiki language is set to English because the actual documentation is also in English but in Holland most of the time the thousands separator is not used at all and when it is used it should be a **```"."```**.  so I would like to disable it completely (on the wiki) but that is something that can not be done. As for the math formats it would be nice if it would support stripping the thousands separator like the other formats do. You can not use these formats in ```{{#expr:...```. @kghbln, I will try the **NumberFormat** extension, thanks for the tip.

As a separate comment, I understand linking these separators (decimal and thousands) to the wiki language but would it not be more user friendly if there was a possibility to tell the wiki what to use and if it should use it. So you could set the ```"."``` as the decimal separator on a wiki no matter what the language is set to? There must be a lot of wiki's running on the English language but are used outside the USA or UK. This especially applies to SMW wikis where you do calculations on properties with the type Number and even more when these values represent Money. When SMW started was there ever the idea to create a money type property on which you could set separators and the amount of decimal values? This would increase readability of numbers a lot.

```
Item1      €    1234
Item2      €  234.45
Item3      €    34.2
Item4      €       4
```
With control:

```
Item1      € 1234,00
Item2      €  234,45
Item3      €   34,20
Item4      €    4,00
```

**Comment by mwjames** [comment]
> When SMW started was there ever the idea to create a money type property

Have a look at the temperature datatype which should give an idea on how a money datatype can be constructed (including exchange rates etc.).

> the idea to create a money type property on which you could set separators and the amount of decimal values? This would increase readability of numbers a lot.

Precision comes to mind. I have somewhere a PR that adds the ability to declare an explicit precision of a property like `[[Precision of::3]]` but that's not very high on my list to make it mergeable.

**Comment by jongfeli** [comment]
We use custom properties (Quantity) for all kinds of values. It is great for our USA colleagues so they can read the value of ```15 cm``` in ```inches```. I could define a Quantity type property that represents ```€``` but you do not have control over the location of the ```€```sign. It is ok to write ```500 Nm``` but it is not ok to write ```500 €``` it should be ```€ 500```.

> explicit precision of a property like [[Precision of::3]] but that's not very high on my list to make it mergeable.

I understand and that it is not a problem, if there is one then it is the fact that the math formats results can not be used in ```{{#expr:...``` so I will run them trough **NumberFormat** first. Thanks for the info.

**Comment by mwjames** [comment]
>  It is ok to write 500 Nm but it is not ok to write 500 € it should be € 500.

How about (if time permits) you think about writing a small RFC (for SMW core) to gather some requirements. For example, if you do something like below you could try making an inference (necessary for the parser) of the position of the label either as leading or last ` [[Corresponds to::€ 1]]`.

```
Property:Debit

[[Has type::Quantity]] [[Display units::€]] 

* [[Corresponds to::€ 1]]
* [[Corresponds to::1.06 US]]
* [[Corresponds to::0.70 British Pound]]
```

**Comment by jongfeli** [comment]
Where do start a **RFC**, as an issue? 

Logic says that you basically got it in your example, if the ```[[Display units::..``` are defined SMW should be able to determine the position in the ```[[Corresponds to::``` which in turn makes sure the unit, in this case, is in front of the result. But what do I know, I don't even know how you spell **PHP** let alone program in it... That is of course a joke, I do know how to spell it :)

**Comment by mwjames** [comment]
> Where do start a RFC, as an issue?

Yes.

PS: The word sounds bigger than it actually is. Just a place to gather ideas about possible restrictions and requirements and see what would be the most viable solution to get it implemented.

**Comment by JeroenDeDauw** [comment]
Am I understanding correctly that this issue could be solved by adding a parameters that allows disabling the formatting of the number in the math formats? (If so, then yay, cause this is very easy to do.)

**Comment by jongfeli** [comment]
> disabling the formatting of the number in the math formats?

Yes, on [0] the result of ```{{#ask:[[{{PAGENAME}}]]|?Value1#|?Value2#|format=sum}}``` should be 22000,95  and not 22,000.95. As documented on [1].

[0] http://sandbox.semantic-mediawiki.org/wiki/Thousands_separator
[1] http://www.semantic-mediawiki.org/wiki/Help:Type_Number#Plain_printout_format_for_queries

**Comment by JeroenDeDauw** [comment]
Oh hold on, I forgot about the non-optionality decimal separator :D This thing needs to be formatted either way, so it's not as trivial as I thought.

**Comment by jongfeli** [comment]
Well that was my mistake in the example above (I changed it). This issue only concerns the thousands separator. On an English Wiki the result should be ```22000.95```. All the math result formats should just strip the thousands separator when ```{{#ask:[[{{PAGENAME}}]]|?Value1#|?Value2#|format=sum}}``` is used. This is to get a "clean" number that can be used in ```{{#expr:...```. This also makes the behaviour the same as the other result formats.

**Comment by gesinn-it** [comment]
It seems, that the hack with blanking out MediaWiki:Smw_kiloseparator message [0] is also not working...

[0] https://www.semantic-mediawiki.org/wiki/Help_talk:Type_Number#Disabling_the_separators

**Comment by gesinn-it** [comment]
@mwjames @kghbln : preparing a fix (PR) for this. Would be cool if we could get this into 2.5.0 release...
