### ISSUE TITLE
Undefined variable $lower_day in SemanticResultFormats.parser.php on line 121

### ISSUE THREAD

**Issue by jamesmontalvo3** [SemanticMediaWiki/SemanticResultFormats#153]
Running `php extensions/SemanticMediaWiki/maintenance/rebuildData.php -d 5 -v` while migrating to a new server gives me the following error:

> (761/229105) Processing ID 762 ...
> (762/229105) Processing ID 763 ...
> (763/229105) Processing ID 764 ...
> (764/229105) Processing ID 765 ...
> (765/229105) Processing ID 766 ...
> 
> Notice: Undefined variable: lower_day in /opt/meza/htdocs/mediawiki/extensions/SemanticResultFormats/SemanticResultFormats.parser.php on line 121
> 
> Notice: Undefined variable: lower_day in /opt/meza/htdocs/mediawiki/extensions/SemanticResultFormats/SemanticResultFormats.parser.php on line 121
> (766/229105) Processing ID 767 ...
> (767/229105) Processing ID 768 ...
> (768/229105) Processing ID 769 ...
> (769/229105) Processing ID 770 ...

Looking at the [code in master](https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/SemanticResultFormats.parser.php#L94) and the [code in v2.3](https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/SemanticResultFormats.parser.php#L94) I see that in both cases it is possible for `$lower_day` to be undefined. Furthermore, this if-statement appears to be unnecessary: 

```php
if ( is_numeric( $query_day ) && ( intval( $query_day ) == $query_day ) && $query_day >= 1 && $query_day <= 31 ) {
	$lower_day = $query_day;
}
else {
	$lower_day = '1';
}

$lower_day = $wgRequest->getVal( 'day' );
```

Environment: transitioning from MW 1.23 and SMW 2.2 to MW 1.25 and SMW 2.3

**Comment by kghbln** [comment]
Thanks for reporting. A pull request for this is welcome. :)
