### ISSUE TITLE
Filtered Calendar view no longer works with Google Chrome

### ISSUE THREAD

**Issue by mitchelln** [SemanticMediaWiki/SemanticResultFormats#159]
Hi.

I have a filtered calendar view here:
https://www.wiltshireparentcarercouncil.co.uk/en/Children_Calendar

It no longer renders with Google Chrome (version 51.0.2704.84). You get nothing. No errors are thrown in the developer console.

It still works fine in Firefox, IE9,10,11, Edge and Safari. 

Thanks.

**Comment by kghbln** [comment]
@mitchelln You might want to have a look at issue #158 so there seem to be even more troubles ahead.
