### ISSUE TITLE
Remove usages of deprecated ResultPrinter::getParameters

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#162]
This method is deprecated since 1.8 yet still used by CategoryResultPrinter, EmbeddedResultPrinter and ListResultPrinter. Should not be hard to refactor

https://github.com/SemanticMediaWiki/SemanticResultFormats/search?utf8=%E2%9C%93&q=getParameters

Per https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1654#issuecomment-226932849

**Comment by kghbln** [comment]
This has now been rescheduled to SRF 3.1.0

**Comment by s7eph4n** [comment]
There are no occurrences of `getParameters` in SRF left.

**Comment by kghbln** [comment]
> There are no occurrences of getParameters in SRF left.

Ok, super!
