### ISSUE TITLE
2.4 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#164]
Tracking issue for the 2.4 release.

* [Release notes](https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/RELEASE-NOTES.md)
* [Changes since 2.3](https://github.com/SemanticMediaWiki/SemanticResultFormats/compare/2.3...master)

--

* [x] Finalize RELEASE NOTES
* [x] Update version number `SemanticResultFormats.php` (tag is 2.4.0 NOT 2.4)
* [x] Update version number `README.md`
* [x] Update `INSTALL.md`
* [x] Create tag
* [x] Announce via mail
* [x] Do a release tweet on Twitter
* [ ] Run `composer update` on smw.o

**Comment by kghbln** [comment]
I think https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/163 should go into this release.

**Comment by kghbln** [comment]
https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/171 and https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/172 should go in here, too.

@JeroenDeDauw What about doing a release a week before SMWCon Fall 2016.

**Comment by JeroenDeDauw** [comment]
Looking at the release notes it seems high time a release is made yes; keeping features and fixes unavailable to users for so long is unfortunate.

I'm happy to poke a bit at a release but current do not have the time to tackle the issues you linked myself.

**Comment by kghbln** [comment]
@JeroenDeDauw I believe that #163 should be doable rather quick. Probably I can even do this, while it is just a matter of getting a reply for #171 from @Fannon while #172 has a patch waiting by @kriegfrj. So no big deals for them. The only big? issue is now #174 which I just created, so if you or @mwjames could poke the JavaScript for this that will be cool.

**Comment by JeroenDeDauw** [comment]
I've put up a PR for the Ploticus thing and suggest we make the release after that's merged. In time for SMWCon :) And kinda long overdue anyway

**Comment by kghbln** [comment]
> I've put up a PR for the Ploticus thing and suggest we make the release after that's merged.

Thanks a bunch. I totally forgot. All the other issues assigned to the 2.4 milestone are resolved now.

**Comment by kghbln** [comment]
@JeroenDeDauw Time to move on?

**Comment by kghbln** [comment]
@JeroenDeDauw Thanks a lot!
