### ISSUE TITLE
Missings labels in nl.json (Dutch translations)

### ISSUE THREAD

**Issue by waandershz** [SemanticMediaWiki/SemanticResultFormats#166]
nl.json misses some entries for the Dutch language, for example: "srf-ui-datatables-label-sInfo".

So, my Dutch overview now show some English labels like "Showing 1 to 10 of 65 entries" and "Search".

**Comment by JeroenDeDauw** [comment]
Thanks for reporting the issue. You can contribute the missing labels yourself via TranslateWiki.

https://translatewiki.net/w/i.php?title=Special%3AMessageGroupStats&x=D&group=ext-semanticmediawiki&suppressempty=1

**Comment by waandershz** [comment]
How does this work?

**Comment by kghbln** [comment]
> How does this work?

@waandershz Have a look at [How to start](https://translatewiki.net/wiki/Translating:How_to_start). Basically you have to register over there, get the translator permission and start translating via the interface as shown via the link provided in Jeroen's post. The new translations are regularly synced into our repository here.

**Comment by kghbln** [comment]
Same for [Semantic MediaWiki](https://translatewiki.net/w/i.php?title=Special:Translate&group=mwgithub-semanticmediawiki&language=nl&filter=%21translated&action=translate) and other semantic extensions. It will be great if you would tackle doing the translations.
