### ISSUE TITLE
Filtered format / change symbols for collapsed and expanded

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#169]
Currently the filtered format uses a ["+" and "-"](https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/formats/Filtered/libs/ext.srf.filtered.value-filter.js#L178-L179) to toggle the view via the "filter collapsible" option. What about changing this to ► and ▼ for consistency with other extensions or even better allow for wiki specific adaptation via a system message like it is done with the CategoryTree exension (`categorytree-collapse-bullet`, `categorytree-expand-bullet`)

@s7eph4n Thoughts?

**Comment by kghbln** [comment]
@s7eph4n Just a ping on your thoughts about this.

**Comment by s7eph4n** [comment]
These are inserted now by CSS rules instead of hardcoded in the JS. You should be able to overwrite the rules with custom CSS. See https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/227/files#diff-3240592a2a2ac125974f87c2120b03bfR83.

**Comment by kghbln** [comment]
> These are inserted now by CSS rules instead of hardcoded in the JS.

Wow, great news indeed, so adaptions could probably be similar what [SBL is doing with arrows.](https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/blob/master/res/sbl.styles.css#L52)
