### ISSUE TITLE
Datatables format / empty printout not supported

### ISSUE THREAD

**Issue by kriegfrj** [SemanticMediaWiki/SemanticResultFormats#172]
* MediaWiki 1.25.3
* SMW 2.4.1
* SRF 2.3

Sometimes I want to move the subject of a query result to a different position in a table row. For the standard formats, this is done by using `mainlabel=1` and then a printout like `|?=Subject`. However, if you try and do this with datatables you get a Javascript error like this:
````
DataTables warning (table id = 'DataTables_Table_0'): Requested unknown parameter 'Subject' from the data source for row 0
````

Sandbox example to come hopefully - it's just being a little bit slow at the moment.

**Comment by kriegfrj** [comment]
Sandbox example created to demonstrate: http://sandbox.semantic-mediawiki.org/wiki/Issue/172_(SRF_-_datatables_doesn%27t_handle_subject_printout)

Unfortunately it seems that my control datatables output format isn't working in the sandbox either. I thought it worked originally.

**Comment by mwjames** [comment]
> Sandbox example created to demonstrate:

:+1: 

> DataTables warning (table id = 'DataTables_Table_0'): Requested unknown parameter 'Subject' from the data source for row 0

Yes, it is a bug.

Unfortunately, I cannot spare any time on SRF to fix this which means unless someone else finds the time to send a PR this will unlikely be fixed soon.

**Comment by kriegfrj** [comment]
Thanks @mwjames. I didn't really have the time either but I managed to squeeze it in as a useful training exercise. :smile: Please see PR #173 for a fix.
