### ISSUE TITLE
Eventcalendar format / Not loading due to SCRIPT1006: ')' expected load.php (235,66)

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#174]
**Setup**
- MediaWiki 	1.25.6 (01b4001)
- PHP 	5.6.11-1ubuntu3.4 (apache2handler)
- MySQL 	5.6.31-0ubuntu0.15.10.1
- Semantic MediaWiki	2.4.1 (af78257)
- Semantic Result Formats	2.3 (986366a)

**Issue**
Currently the eventcalendar format does not load for Internet Explorer (11), Edge (25), Safari (9) and Opera (12). Chrome (51) and Firefox (48) are not yet? affected.

While Opera and Safari return "yellow snow" i.e. no useful information Internet Explorer and Edge provide more information:

`SCRIPT1006: ')'` expected in "load.php (235,66)"

It seems that these browsers are now expecting
   `return null;};var blobstore=function(namespace,engine,description)`
instead of
   `return null;};var blobstore=function(namespace,engine,description='')`
from 235
```
return null;};var blobstore=function(namespace,engine,description=''){this.VERSION=1;this.namespace=namespace;this.engine=engine;if(this.engine===''||this.engine===undefined){this.engine=new FORAGE(namespace,description);}return this;};blobstore.prototype.getNamespace=function(){return this.namespace;};blobstore.prototype.set=function(key,value,ttl){this.engine.set(key,value,ttl);};blobstore.prototype.get=function(key,callback){return this.engine.get(key,callback);};window.onoi=window.onoi||{};window.onoi.blobstore=blobstore;}(jQuery));});mw.loader.implement("onoi.localForage",function($,jQuery){!function(a){if("object"==typeof exports&&"undefined"!=typeof module)module.exports=a();else if("function"==typeof define&&define.amd)define([],a);else{var b;b="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this,b.localforage=a()}}(function(){return function a(b,c,d){function e(g,h){if(!c[g]){if(!b[g]){var i="function"==typeof require&&require;
```

**Comment by mwjames** [comment]
> var blobstore=function(namespace,engine,description='')

Expected this to be solved with https://github.com/onoi/shared-resources/releases/tag/0.2.3.

**Comment by kghbln** [comment]
> Expected this to be solved with https://github.com/onoi/shared-resources/releases/tag/0.2.3.

Affirmative! It is working for IE, Edge and Opera again. Cannot test Safari but why shouldn't this work. Thanks a ton!
