### ISSUE TITLE
Allow inclusion of the entry point without MW loaded

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticResultFormats#178]
Stop executing non-global assignment in entry point, most notably 

``` php
if ( !defined( 'MEDIAWIKI' ) ) {
    die( 'Not an entry point.' );
}
```

So non-MW dependent tests can be run without having MW loaded. Also avoids similar problems when SRF is included in some other project.

See the Maps entry point for an example: https://github.com/JeroenDeDauw/Maps/blob/master/Maps.php

**Comment by kghbln** [comment]
@JeroenDeDauw Is this still a thing to do or can this be closed?

**Comment by JeroenDeDauw** [comment]
Looks like a certain @mwjames took care of it
