### ISSUE TITLE
Filtered format: Performs an AND operation in upgraded version; it used to be an OR (and should be)

### ISSUE THREAD

**Issue by RinekeOostenrijk** [SemanticMediaWiki/SemanticResultFormats#189]
### Setup

- MW version:  1.27.1
- DB (MySQL etc.):  	5.5.50-MariaDB
- PHP version:  5.6.28 (apache2handler)
- SMW version: 2.4.2
- SRF version: 2.4
- Browsers and versions (if applicable):

### Issue
I use filtered output in an overview of references. Users can select publication years and publication types to filter the result. The filter uses an OR within a property and an AND between properties in my current version. See http://themasites.pbl.nl/models/image/index.php/All_references_overview  (MW:1.22.0; PHP: 5.6.28; DB:  	5.5.5-10.1.19-MariaDB; SMW: 1.8.0.5; SRF:1.8) 

We upgraded to the newest versions of the software on a test server (with versions above described) , but now the filter uses an AND within the values of a property. It is no longer possible to select all articles published in 2014 OR 2015. I should say this is a bug. We don't get any debug messages though.

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):
I reproduced the query in the  sandbox wiki: https://sandbox.semantic-mediawiki.org/wiki/Reference_filter

**Comment by kghbln** [comment]
@RinekeOostenrijk Thank you for reporting.

**Comment by s7eph4n** [comment]
Should work now (SRF 2.5.4 and later).
