### ISSUE TITLE
DataTables: Inline limit set to 750

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticResultFormats#20]
On the [mailing-list](http://wikimedia.7.x6.nabble.com/SMW-results-format-datatables-td5023877.html) the following appeared as question "s there a hard 750 on limit parameter for the amount of rows you can request in results format datatables?"

I don't remember why the value was set to [750](https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/formats/datatables/resources/ext.srf.formats.datatables.js#L560)  but you could change it to something like:

```
inlineLimit: smw.settings.get( 'smwgQMaxLimit' )
```

**Comment by kghbln** [comment]
I think making this format listen to `$smwgQMaxLimit` will be  a nice enhancement

**Comment by kghbln** [comment]
@mwjames Is there any objection to changing this line with the patch provided in you initial https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/20#issue-29376587?

**Comment by mwjames** [comment]
> Is there any objection to changing this line with the patch provided in you initial

No objections.

PS: I haven't tested therefore needs verification of whether this is sufficient or not.

**Comment by krabina** [comment]
I think this is solved with the new datatables format. https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/771
