### ISSUE TITLE
Tree format / provide CSS classes

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#208]
So far this result format uses the standard HTML ul and li to render the results. I think it will be a great enhancement to allow applying CSS adaptions e.g. to have different margins and padding as well as different colors etc. for the different hierarchy levels.

@s7eph4n I dunno if this is easy to achieve or possible at all.

**Comment by s7eph4n** [comment]
It will take more than just adding the `class` attribute. The level is readily available in the `$level` parameter, but the result format produces wikitext for the lists (see [SRF_Tree.php#L180](https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/formats/tree/SRF_Tree.php#L180)). I do not know if you can somehow add a class there. The easiest solution would probably be to wrap the whole thing in a `<div class="srf-tree">` and then style on `div.srf-tree ul`, `div.srf-tree ul ul`, `div.srf-tree ul ul ul`, etc.

**Comment by kghbln** [comment]
@s7eph4n Awesome idea which I could or should have had too! Not that I am not using a similar approach for other formats. ;)

So the enhancement to the code could be to let it automatically wrap the result within the mentioned div class without extra user intervention?

**Comment by s7eph4n** [comment]
Yes, that's the idea.

**Comment by kghbln** [comment]
> Yes, that's the idea.

Cool!

**Comment by kghbln** [comment]
@s7eph4n Since you referenced the pull which was refactoring the "tree" format I believe that this issue was resolved, too. Thanks a lot for this. Much appreciated!

If I am for some reason mistaken it will we nice if you could reopen this enhancement request.

**Comment by s7eph4n** [comment]
Yes, this should be fixed. The tree is now wrapped in a `<div class='srf-tree'>`. See https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/226/files#diff-c218d8485e4f87038e116d7b077c082fR149

**Comment by kghbln** [comment]
@s7eph4n Cool. Please do not mind that I just "ballert you zu" with other questions to the two formats you re-factored.
