### ISSUE TITLE
Datatables format / Sort option is not respected in ask queries

### ISSUE THREAD

**Issue by djflux** [SemanticMediaWiki/SemanticResultFormats#211]
### Setup

- MW version: 1.25.5
- DB (MySQL etc.): MySQL 5.6.36
- PHP version: 5.6.14 (apache2handler)
- SMW version: 2.4.0-rc1
- SRF version: 2.3
- Browsers and versions (if applicable): NA

### Issue

The `Datatables` results format does not respect the `sort` option set.

A demonstration is available: 

#### Production SMW
https://www.semantic-mediawiki.org/wiki/User:Arechenberg

#### Sandbox SMW
https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Arechenberg

Here is are the ask queries I tried

```
Production SMW site

modified from  https://www.semantic-mediawiki.org/wiki/Demo:Datatables_simple_table

{{#ask:
 [[Category:Result formats]]
 [[Release status::current]]
 [[Docinfo language::en]]
 |?Has format name=Name
 |?Has description=Description
 |?Has category=Category
 |?Has component=Provided by 	
 |format=datatables
 |mainlabel=Help page
 |sort=Has category
 |order=descending
}}
```

```
Sandbox SMW

{{#ask:
 [[-Has date::+]]
 [[-Has number::+]]
 [[Category:Test]]
 |?Page author
 |?Has date
 |?Has number	
 |format=datatables
 |sort=Has number
 |order=descending
}}
```

Thanks for your help.

Cheers,
Andy

**Comment by kghbln** [comment]
Thanks for testing and reporting. Indeed this is a feature missing. SWM 3.0 will bring the class `datatable` to the table and broadtable formats (See this [pull request](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2420)). Result format "datatables" indeed still needs this enhancement.

**Comment by mwjames** [comment]
Hi,

> Thanks for testing and reporting. Indeed this is a feature missing. SWM 3.0

I'm aware of that but as I already mentioned in #2427, I'm unable to
set aside time to implement this for the SRF:DataTables format. Users
are welcome to look at #2427 on how it is implemented and provide a
fix for this format.

Cheers

**Comment by kghbln** [comment]
> I'm aware of that but as I already mentioned in #2427

I knew about it but did not remember where you wrote it. I just cross-referenced for completeness.

**Comment by krabina** [comment]
Closing since this relates to a very old version. Please try the latest version and reopen should the problem persist.
