### ISSUE TITLE
Excel format does not return all results

### ISSUE THREAD

**Issue by ubibene** [SemanticMediaWiki/SemanticResultFormats#213]
### Setup

- MW version: 1.27.3 
- DB (MySQL etc.): 5.7.17
- PHP version:  5.6.30
- SMW version:  2.5.1
- SRF version:  2.4.2
- Browsers and versions (if applicable): NA

### Issue

query does not return all results if format=excel
Steps to reproduce the observation

- My wiki instance has 865 pages with category A
- in LocalSettings.php put $smwgQMaxInlineLimit=1000;
- simplified example to reproduce the behaviour : 
  -  {{#ask [[Category:A]|... |format=csv|limit=1000|..}} returns a CSV with 866 lignes (header + 1 ligne per page)
  -  {{#ask [[Category:A]|... |format=excel|limit=1000|..}}  returns an Excel File with 801 lines (header + 1 line per page, 65 lines are missing)

**Comment by s7eph4n** [comment]
I just tried it on a dataset of cities and with these queries:
```
{{#ask:[[Category:City]][[~S*]]|format=csv|limit=1000}}
{{#ask:[[Category:City]][[~S*]]|format=excel|limit=1000}}
```

It works for me. Both queries returned a file with the 855 cities (in line with the number of 854 items to be expected in the result as reported by the count format).

I tested this is on
* MediaWiki 1.29.0-alpha (9a6a304)
* Semantic MediaWiki 2.5.0 (a41d159)
* Semantic Result Formats 2.5.0-alpha (54a673c)
which should be close enough.

If possible, it would be great if you could find out some more about how this bug manifests itself, e.g.
* Which values are missing from the excel dataset? Random? The last from a sorted list?
* Does this also happen for smaller datasets?
* If yes, could you create a demonstration on http://http://sandbox.semantic-mediawiki.org/?
* If not, from what size of the result set does this start?

**Comment by ubibene** [comment]
Hi @s7eph4n 

> Which values are missing from the excel dataset? Random? The last from a sorted list?

The last one from a sorted list are missing

> Does this also happen for smaller datasets?
No

A dataset with 97 entries, and another one with 582 entries are correctly fetched with the xls format.
 
>  If not, from what size of the result set does this start?
801 entries seem to be the starting point where the xls exports fails

**Comment by ubibene** [comment]
Not sure if this helps or is relevant , but here are the csv/excel (sanitized) headers

- (blank) : page name
- aliases
- id 1
- id 2
- description :  a multiline string, may be quite long	
- prop 1
- prop 2
...
- prop 20

**Comment by ubibene** [comment]
Interesting : If I omit the "description" field/property from the query/export, the excel file has all 865 lines

**Comment by s7eph4n** [comment]
That's an interesting one! Now (hopefully) all we need to find out is what is different about the description in line 800 or 801 that breaks the excel format.

**Comment by ubibene** [comment]
Nope ;-)  

I tried both queries with  sort=ascending and sort=descending , and both end up with à 801 lines excel

**Comment by s7eph4n** [comment]
Dang! :)

**Comment by ubibene** [comment]
Should I activate logging to find about any warnings ?  How would I do this ?

**Comment by s7eph4n** [comment]
That would be great. See here: https://www.mediawiki.org/wiki/Manual:How_to_debug#PHP_errors

**Comment by ubibene** [comment]
Here are messages seen in the log ( the referer "/Exporter" is the page containing the query called for exporting)  :


```
[Fri May 19 12:56:48.106685 2017] [:error] [pid 4486] [client xxx] PHP Notice:  Did not find alias for special page 'ImportSpreadsheet'. Perhaps no aliases are defined for it? [Called from SpecialPageFactory::getLocalNameFor in /opt/mediawiki/includes/specialpage/SpecialPageFactory.php at line 689] in /opt/mediawiki/includes/debug/MWDebug.php on line 300, referer: http://xxx/index.php/Exporter

[Fri May 19 12:56:48.107123 2017] [:error] [pid 4486] [client xxx] PHP Notice:  Did not find alias for special page 'DeleteHistory'. Perhaps no aliases are defined for it? [Called from SpecialPageFactory::getLocalNameFor in /opt/mediawiki/includes/specialpage/SpecialPageFactory.php at line 689] in /opt/mediawiki/includes/debug/MWDebug.php on line 300, referer: http://xxx/index.php/Exporter

[Fri May 19 12:56:48.107495 2017] [:error] [pid 4486] [client xxx] PHP Notice:  Did not find alias for special page 'GetData'. Perhaps no aliases are defined for it? [Called from SpecialPageFactory::getLocalNameFor in /opt/mediawiki/includes/specialpage/SpecialPageFactory.php at line 689] in /opt/mediawiki/includes/debug/MWDebug.php on line 300, referer: http://xxx/index.php/Exporter

[Fri May 19 12:56:48.141445 2017] [:error] [pid 4486] [client xxx] PHP Notice:  Did not find alias for special page 'GetData'. Perhaps no aliases are defined for it? [Called from SpecialPageFactory::getLocalNameFor in /opt/mediawiki/includes/specialpage/SpecialPageFactory.php at line 689] in /opt/mediawiki/includes/debug/MWDebug.php on line 300, referer: http://xxx/index.php/Exporter
```

**Comment by s7eph4n** [comment]
Is the excel download still producing a valid file?

**Comment by ubibene** [comment]
Yes it is. I can open the excel file either with MS Office 2010 or LibreOffice 5.2 without any warnings.

**Comment by ubibene** [comment]
Hi again

I added a few traces in SRF_Excel.php
```

134         protected function populateDocumentWithQueryData( $res ) {
135                 $count=0;
136                 while ( $row = $res->getNext() ) {
137                         $this->rowNum++;
138                         $count++;
139                         $this->colNum = 0;
140                         $this->readRowData($row);
141                 }
142                 error_log("count : ".$count);
143         }
```
This gives me 800 in the error log

**Comment by ubibene** [comment]
Going up one level and addings a trace in error_log in the function that calls  SRF_Excel ( SMW_SpecialAsk.php/ line 311 )

```
 310                         $res = $this->getStoreFromParams( $params )->getQueryResult( $queryobj );
311                         error_log("count 1 ".$res->getCount());
312                         $duration = number_format( (microtime( true ) - $duration), 4, '.', '' );
```


 I get : 

[Mon May 22 13:28:34.236961 2017] [:error] [pid 10388] [client 10.122.200.153:52737] count : **800**, 

for the query including the multilines description field in the printout.

For the same query, but  omitting the description printout : 
 
[Mon May 22 13:51:56.032356 2017] [:error] [pid 7152] [client 10.122.200.153:52974] count :  **866**,

For the csv format query including the description field printout I get count = 866

**Comment by s7eph4n** [comment]
At this point I am totally lost. I have no idea how the results can be different between csv and excel formats, when the result printer has not even been called. @mwjames, do you have any idea?

**Comment by kghbln** [comment]
> Here are messages seen in the log ( the referer "/Exporter" is the page containing the query called for exporting)
>
> PHP Notice:  Did not find alias

Note that these errors are unrelated to this issue. Apart from that this appears to be an interesting issue which should not happen. We just have found the reason yet.

**Comment by ubibene** [comment]
I'm sorry, and I think I should take a break :  I had set limit=800 for the excel format, whereas  I set limit=1000 for the other 5 queries on the same page. The excel export has got all the lines, once I change 800 to 1000.

**Comment by kghbln** [comment]
One of these days. ;)

**Comment by s7eph4n** [comment]
\o/
