### ISSUE TITLE
Migrating code to PHP 5.4+ short array syntax

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#214]
In case [SRF 2.5.0](https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/190) [drops support for PHP 5.4 and earlier](https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/190#issuecomment-303799107) the arrays could probably be migrated to use the short syntax, i.e. `array( )` to `[ ]`.

[See here on how to do this](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2318#issuecomment-285849787)

**Comment by kghbln** [comment]
@JeroenDeDauw I figured that it was just a matter of running the command specified in you post. However in the meantime they seem to have rewritten the software so a fixer option does no longer exist. I'd rather leave this task to you.

**Comment by JeroenDeDauw** [comment]
If you use the latest version of the tool, the command is:

    php php-cs-fixer fix src/ --rules='{"array_syntax": {"syntax": "short"}}'

**Comment by kghbln** [comment]
> If you use the latest version of the tool, the command is:

Great. Thanks a lot for the hint. I was somehow unable to translate their instructions into this command. Senior I believe.

**Comment by kghbln** [comment]
Once this got merged we may keep this on sandbox for a fortnight or so and then release

**Comment by JeroenDeDauw** [comment]
It took me 15 minutes or so to figure it out as well some months ago. The docs for this are just shit

**Comment by kghbln** [comment]
> It took me 15 minutes or so to figure it out as well some months ago. The docs for this are just shit

This somehow makes me feel better.
