### ISSUE TITLE
graphviz based formats / Missing argument 4 for GraphViz::graphvizParserHook(),

### ISSUE THREAD

**Issue by mwColin** [SemanticMediaWiki/SemanticResultFormats#215]
### Setup

- MW version: 1.27.3
- DB (MySQL etc.): MariaDB 10.0.29
- PHP version: 7.0.8
- SMW version:2.5.2
- SRF version: 2.4.2
- Browsers and versions (if applicable):

### Issue

When using the graphviz format, there is an error reported for a missing parameter when calling the graphvizParserHook function from the Mediawiki GraphViz extension. It should be called with 4 parameters instead of 3. Passing an empty parameter, removes the error.

The line should be this, unless the authors see a more appropriate version
```php
$result = GraphViz::graphvizParserHook( $graphinput, "", $GLOBALS['wgParser'], "");
```
Although the error is reported, it doesn't seem to effect the operation of the extension.

**Comment by kghbln** [comment]
Thank you for reporting and suggesting a fix. Which version of GraphViz are you using? What is the exact error message?

**Comment by mwColin** [comment]
I am using GraphViz version 2.0.1

The error is:

Missing argument 4 for GraphViz::graphvizParserHook(), called in /w/extensions/SemanticResultFormats/formats/graphviz/SRF_Graph.php on line 115 and defined in /w/extensions/GraphViz/GraphViz_body.php on line 360
Notice:  Undefined variable: frame in /w/extensions/GraphViz/GraphViz_body.php on line 378

**Comment by kghbln** [comment]
Thanks a lot, so you are using the latest release of the GraphViz extension. A programmer will probably know what this is all about right away but error messages also help finding and identifying the issue for others, too.

**Comment by mwjames** [comment]
> GraphViz extension. It should be called with 4 parameters instead of 3. Passing an empty parameter, removes the error.
>  A programmer will probably know what this is all about right away

Changing the call `GraphViz::graphvizParserHook` to `$result = GraphViz::graphvizParserHook( $graphInput, "", $GLOBALS['wgParser'], "" );` in [0] should be sufficient.

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/eaaec343d6321fac44ec0179550d6b334bdb2dec/formats/graphviz/SRF_Graph.php#L114-L115
