### ISSUE TITLE
 Class 'ImageGallery' not found

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticResultFormats#224]
### Setup

- MW version: 1.29
- DB (MySQL etc.):
- PHP version: 
- SMW version: 3.0+
- SRF version:2.4+

### Issue

**Steps to reproduce**

- https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3ARequ%C3%AAter&q=[[File%3A%2B]]&po=&eq=yes&p[format]=gallery&sort_num=&order_num=ASC&p[source]=&p[limit]=&p[offset]=&p[link]=all&p[sort]=&p[headers]=show&p[mainlabel]=&p[intro]=&p[outro]=&p[searchlabel]=...+further+results&p[default]=&p[class]=sortable+wikitable+smwtable&p[widget]=&p[navigation]=nav&p[perrow]=&p[widths]=&p[heights]=&p[autocaptions]=1&p[captionproperty]=&p[imageproperty]=&p[redirects]=&eq=yes

**Stacktrace** 

```
Fatal error: Class 'ImageGallery' not found in /var/www/htdocs/mw/02100/w/extensions/SemanticResultFormats/formats/gallery/Gallery.php on line 66
```

**Comment by mwjames** [comment]
Somehow the class went missing with the current release! Yeah, MediaWiki is funnnnnnnnn and I'm certainly not annoyed by this!

**Comment by mwjames** [comment]
Expected to be fixed with https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/e02b1b90e3f7930f5c21f9d799b83b05fa21ba29.

**Comment by s7eph4n** [comment]
Sorry for the mess. I referenced the wrong bug.
