### ISSUE TITLE
Gallery: Remove feature switch

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticResultFormats#229]
### Setup

- MW version: 1.23+
- SRF version: 2.5-dev (e02b1b90e3)

### Issue

[formats/gallery/Gallery.php#L66](https://github.com/SemanticMediaWiki/SemanticResultFormats/tree/e02b1b90e3/formats/gallery/Gallery.php#L66) contains a feature switch to ensure compatibility with old MW versions. The `ImageGallery` class was removed in MW 1.22, SRF requires MW 1.23+. It should be safe to remove the feature switch and expect `TraditionalImageGallery` to exist.

(F'up to #224)

**Comment by kghbln** [comment]
I have rescheduled this to SRF 3.1.0
