### ISSUE TITLE
Oltree: No longer provides numbers

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#234]
### Setup

- MediaWiki 	1.27.3 (798ceea) 19:03, 30 April 2017
- PHP 	5.6.30 (cgi-fcgi)
- MySQL 	5.6.28-76.1-log
- Semantic MediaWiki	2.5.2 (84007ca) 07:45, 17 May 2017
- Semantic Result Formats	2.5.0 (a8fce2c) 12:58, 13 June 2017

### Issue

Choosing the "oltree" format does not longer render the numbers:

### Example
See the [docu page](https://www.semantic-mediawiki.org/wiki/Help:Oltree_format)

**Comment by kghbln** [comment]
@s7eph4n The first "fatalities" after the refactoring.

**Comment by s7eph4n** [comment]
Well that went fast. :(

**Comment by kghbln** [comment]
No worries. I understand what we are talking about quite complex stuff. So ...

**Comment by kghbln** [comment]
Affirmative, works perfect. Thanks a lot! Back-ported with faedb76ff6e10c7ef49120f1a743a56d5dd19d6f
