### ISSUE TITLE
Tree: template option no longer works

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#235]
### Setup

- MediaWiki 	1.27.3 (798ceea) 19:03, 30 April 2017
- PHP 	5.6.30 (cgi-fcgi)
- MySQL 	5.6.28-76.1-log
- Semantic MediaWiki	2.5.2 (84007ca) 07:45, 17 May 2017
- Semantic Result Formats	2.5.0 (a8fce2c) 12:58, 13 June 2017

### Issue

The "template" parameter no longer works.

**Query**
```
{{#ask:
 [[Category:Content Page]]
 [[Has parent page::+]]
 |?Has page author=
 |format=oltree
 |parent=Has parent page
 |limit=500
 |sort=Has sortkey
 |order=decending
 |template=TocTree
 |valuesep=,
}}
```
**Tempate**
```
<includeonly><span style="font-size:110%;">{{{1|}}}</span>&emsp;({{{2|}}})</includeonly>
```
**Result**
```
{{1=My Page |2=My first author, My second author |#=1 }}
    {{1=My first subpage |2=My first author, My second author |#=2 }}
    {{1=My second subpage |2=My first author |#=3 }}
```
Whereas the pages and author pages are wikilinks and `{{1=` etc. are just rendered as is. If I just ask for two properties this workaround is indeed no longer required, however for the third property the display resembles like the "list" format.

**Comment by kghbln** [comment]
@s7eph4n This is the second "fatality" I observed.

**Comment by s7eph4n** [comment]
Long night ahead, I guess. :/

**Comment by kghbln** [comment]
I really appreciate you effort! Things may go wrong in edge cases however the world is still turning. Just looked out of the window to verify.

**Comment by kghbln** [comment]
Cool, works perfect. Thanks a ton! Back-ported with 8aa9e0ee4a4f9f98b6551d1e664d3f69599fce26

**Comment by D-Groenewegen** [comment]
Still having problems with the Tree format. It looks like the link=none parameter is no longer working. 

https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3ARequ%C3%AAter&q=%5B%5BHas+child%3A%3A%2B%5D%5D&po=&eq=yes&p%5Bformat%5D=tree&sort_num=&order_num=ASC&p%5Bsource%5D=&p%5Blimit%5D=&p%5Boffset%5D=&p%5Blink%5D=none&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bsep%5D=%2C+&p%5Btemplate%5D=&p%5Btemplate+arguments%5D=&p%5Buserparam%5D=&p%5Bintrotemplate%5D=&p%5Boutrotemplate%5D=&p%5Bparent%5D=Has+child&p%5Broot%5D=&p%5Bstart+level%5D=1&eq=yes

**Comment by kghbln** [comment]
So this is [https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/new another issue] I guess.

**Comment by D-Groenewegen** [comment]
Well, yes and no, not entirely. Link and userparam are two parameters in support of template usage that used to work. It probably helps to create a separate issue though. 

Thanks, Stephan, for your work on this! Really much appreciated.
