### ISSUE TITLE
Filtered format, map view: should recognize basic map settings

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticResultFormats#238]
Currently (SRF 2.5.0) the map view in filtered format displays a map with a fixed height of 400px and a width of 100%, furhtermore, other maps settings are ignored.

Basically, the format should support as many of maps-specific settings as possible (see [0])
Most important ones are probably:
- width
- height 
- resizable 
- markercluster, clustergridsize, clustermaxzoom, clusterzoomonclick, clusteraveragecenter, clusterminsize)
- zoom, maxzoom and minzoom
- layers
- controls

[0] https://www.semantic-mediawiki.org/wiki/Help:Map_format

**Comment by s7eph4n** [comment]
`width` and `resizable` are problematic.

The width of the map is derived from the width of the view container, which depends on the width of the Filtered output as a whole. If I added a `map view width` parameter that would result in a map not filling the complete view container or a map being too large for the view container and a scrollbar being shown.

I could introduce a `width` parameter for the Filtered format as a whole, but that would then also be applied to all other view types (list, table, calendar). This effect could also be achieved by wrapping the `#ask` in a div:
```
<div style="width:500px">{{#ask: ... }}</div>
```

Specifying one fixed width would also have an impact on mobile devices.

**Comment by krabina** [comment]
great, now we have
map view height
map view zoom
map view min zoom
map view max zoom

layers can be set using
$srfgMapProvider=

leaves as the only important ones (in my opinion) some settings to control the clustering:
markercluster, clustergridsize, clustermaxzoom, clusterzoomonclick, clusteraveragecenter, clusterminsize

**Comment by s7eph4n** [comment]
We now have the following parameters for `#ask`:
* map view height
* map view zoom
* map view min zoom
* map view max zoom
* map view marker cluster
* map view marker cluster max zoom
* map view marker cluster max radius
* map view marker cluster zoom on click

...and the following new setting for LocalSettings.php:
* $srfgMapProvider
