### ISSUE TITLE
Filtered format, map view: support for customizable icons

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticResultFormats#239]
In SRF 2.5.0 the map view in filtered format shows default icons only.

They should 
a) be customizable
b) be able to be defined on a per-filter base in order to display e. g. markers with different colors/icons for different sets of data

**Comment by krabina** [comment]
Should this be closed, because it is done?

I don't understand the usage of
* map view marker icon property
* map view marker icons
though. Can somehone give an example?

**Comment by kghbln** [comment]
Ping @s7eph4n

**Comment by s7eph4n** [comment]
Yes, it should be closed.

https://www.semantic-mediawiki.org/wiki/Help:Filtered_format has some documentation:
![image](https://user-images.githubusercontent.com/2829850/45531748-7ef84000-b7f1-11e8-8400-78131c5f6b54.png)

Example:
```
|map view marker icon property=Has icon
|map view marker icons=building=house.png, bridge=bridge.png, default.png
```

The icons should be stored as images in the File namespace on the wiki.

**Comment by kghbln** [comment]
I added the parameters to the [example](https://www.semantic-mediawiki.org/w/index.php?title=Help:Filtered_format&diff=64449&oldid=64448)

**Comment by s7eph4n** [comment]
Thanks! :+1:

**Comment by s7eph4n** [comment]
You will need both. `map view marker icon property` defines the property that is to be used to select the icon. `map view marker icons` is the "catalogue" the icon is selected from. So using the example above, if the result element has `[[Has icon::building]]`, the selected marker will be "File:house.png".
