### ISSUE TITLE
Filtered format: customizable filter value controls

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticResultFormats#242]
Filter value control elements cannot be custimized currently (SRF 2.5.0).

* A number filter is displayed as slider. Maybe a user wants a set of values to be selectable or an entry field for a specific value.

* A value filter is displayed as checkboxes. Maybe a user has many values that would crowd the filter area. Other control elements (e. g. a mulit-select drop-down) should be supported.

* Furthermore the control elements (slider, checkboxes, or others) should be stylable (CSS)

**Comment by s7eph4n** [comment]
1. For the number filter, could you provide an example link of a control? Or a mock-up?
2. Followed in #278.
3. What's missing? It's admittedly not very well documented, but most (all) elements should have classes set. Just hit F12 and explore. :wink:

**Comment by krabina** [comment]
1. regarding number filtering/sliders: 
A slider is nice as default. One enhancement would be to introduce a width parameter. Currently the slider uses 100% of the width. If I have many filters, I might want to have two or more sliders adcacent in the same row., Width=50% could do that.

Currently the slider has a min and max value and shows two controls for it. So for the property year, I can set +number filter min value=1945 and +number filter max value=2017. This results in a slider that shows 1945 on the left and 2017 on the right. I have two slider values. However, I might not want to set an interval (1955 to 1969), but a concrete value without having to touch both sliders and set them to one value. Maye an option like +number filter slider=single could be implemented?

Another enhancement would be to introduce a labeled slider. Currently, Only the min value and the max value can be set. It would be nice to be able to indicate intervals (e. g. +number filter interval=50) and show or hide labels.

Furthermore, one might want to restrict the filtering to certain values, this could be done by +number filter values=1900, 1918, 1933, 1945, 1955, especially useful in combination with show labels.

Another option could be to have a drop down instead of a slider, especially in combination with values=...

**Comment by s7eph4n** [comment]
https://refreshless.com/nouislider/ might be a candidate that supports jumping to specified values instead of fixed intervals.

**Comment by s7eph4n** [comment]
>A slider is nice as default. One enhancement would be to introduce a width parameter. Currently the slider uses 100% of the width. If I have many filters, I might want to have two or more sliders adcacent in the same row., Width=50% could do that.

Styling should be possible by CSS.

>Currently the slider has a min and max value and shows two controls for it. So for the property year, I can set +number filter min value=1945 and +number filter max value=2017. This results in a slider that shows 1945 on the left and 2017 on the right. I have two slider values. However, I might not want to set an interval (1955 to 1969), but a concrete value without having to touch both sliders and set them to one value. Maye an option like +number filter slider=single could be implemented?

#286 introduced the `|+number filter values` option. You can set it to `auto` or a comma-separated list of values.

>Another enhancement would be to introduce a labeled slider. Currently, Only the min value and the max value can be set. It would be nice to be able to indicate intervals (e. g. +number filter interval=50) and show or hide labels.

The new library has a label on each slider. You can use the `|+number filter step` parameter to set the step width of the sliders. To actually have each value printed out on the scale under the slider, use the `|+number filter values` option, i.e. list each value you want labelled.

>Furthermore, one might want to restrict the filtering to certain values, this could be done by +number filter values=1900, 1918, 1933, 1945, 1955, especially useful in combination with show labels.

`|+number filter values` again.

See [the README.md of the Filtered format](https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/48315c72ed49de8b8f2c6e85ba44dc886943b134/formats/filtered/README.md#number-filter) for a list of all options of the number filter.

>Another option could be to have a drop down instead of a slider, especially in combination with values=...

Use upcoming improved value filter (#278).

**Comment by s7eph4n** [comment]
I think this is fixed, right?
