### ISSUE TITLE
Filtered format: filters vs. printouts

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticResultFormats#243]
In the current setup (SRF 2.5.0) the filters are defined by printouts of the ask query. The usual behaviour is that this ist the same. So a filter by an attribute "type" would result to show the value for type in a table view or list view or as a property in the map view (when you click on a marker).

There are cases where you want to have filters not repeated as printouts. So there should be a filter setting indicating whether or not the property is only used for filtering or also as a printout.

Maybe with something like
|+value filter printout=show (default) 
|+value filter printout=hide

**Comment by s7eph4n** [comment]
Is this really only about the value filter? What about simply `|+hide`, meaning: Use this value for filtering, but do not show it in views.

**Comment by s7eph4n** [comment]
Fixed for master and 2.5.x

A simple `|+hide` does not work, you have to use `|+hide=yes`. In fact, you can use on/off, yes/no, true/false, or 1/0
