### ISSUE TITLE
Filtered format: slider shows decimal numbers

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticResultFormats#245]
in SRF 2.5.0 a value slider for |+filter=number shows decimal values. This might be OK in some cases, but for others it is awkward. 

In my use case I have a property storing years. The slider ranging from 1910 to 2017, indicates "1964,8" as slider value. So there should be an option to remove the display of comma values in the slider. 

The best option is to set some kind of parameter to indicate the incremental value, e. g.
|+number filter increment = 50
would mean that the slider does not to decimal steps, but steps of 50 (years, in this case).
|+number filter increment = 1 
would mean yearly increments
absende of the setting would have the default, decimal increments based on the values and width of the displayed slider

**Comment by krabina** [comment]
seems to be partly fixed with [https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/267](Filtered - map view: New parameters, improved testing #267 )
There is no option to influence the value yet, but at least there are no more decimals displayed.

**Comment by s7eph4n** [comment]
This was part of #227. See https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/formats/filtered/README.md#number-filter
