### ISSUE TITLE
Tree format: link=none and userparam

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticResultFormats#263]
### Issue
Follow-up from #235 

Now that the tree format is restored/enhanced, two parameters are in need of attention :
* `link=none` has stopped working (it used to work before), which is especially unfortunate when you need this for working with the template parameter. 
* `userparam` is doing something funky. Instead of being used as a template parameter, the very word userparam is printed verbatim at the start of the output. 

**Sandbox**

[--> Special:Ask](https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3ARequ%C3%AAter&q=%5B%5BHas+child%3A%3A%2B%5D%5D&po=&eq=yes&p%5Bformat%5D=tree&sort_num=&order_num=ASC&p%5Bsource%5D=&p%5Blimit%5D=&p%5Boffset%5D=&p%5Blink%5D=none&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bsep%5D=%2C+&p%5Btemplate%5D=&p%5Btemplate+arguments%5D=&p%5Buserparam%5D=&p%5Bintrotemplate%5D=&p%5Boutrotemplate%5D=&p%5Bparent%5D=Has+child&p%5Broot%5D=&p%5Bstart+level%5D=1&eq=yes)

### Setup

- MW version: 1.28.2 / 1.29.0
- SMW version: 2.5.0 / 3.0.0-alpha
- SRF version: 2.5.1 / 3.0.0-alpha

**Comment by kghbln** [comment]
@s7eph4n FYI
