### ISSUE TITLE
Tree format <div> container breaks TreeAndMenu?

### ISSUE THREAD

**Issue by krowlandnet** [SemanticMediaWiki/SemanticResultFormats#287]
### Setup

- MW version: 1.29.0 (on a private domain)
- DB (MySQL etc.): 10.1.21-MariaDB
- PHP version: 5.6.30
- SMW version: 2.5.4
- SRF version: 2.5.1
- Browsers and versions (if applicable):

### Issue

I use the SRF tree format in combination with the [TreeAndMenu](https://www.mediawiki.org/wiki/Extension:TreeAndMenu) extension to build an interactive overview of a thesaurus. After upgrading MW and SMW, this no longer works.

**Steps to reproduce**
1. Install TreeAndMenu
2. Create an ultree (as in https://sandbox.semantic-mediawiki.org/wiki/Ulree_example) wrapped in a TreeAndMenu #tree. The example from my site is
`{{#tree:root=Thesaurus|
{{#ask:
[[Category:Thesaurus]]
[[Is narrower than::+]]
 | format=tree
 | limit=200
 | parent=Is narrower than
}}
}}`

**Expected result:** ...
The whole tree is rendered.
**Observed result:** ...
Only the Thesaurus root node (specified after #tree) is shown.

**My own solution**
The problem seems to be that the SRF tree for 2.5.1 is wrapped in a HTML div container, with class srf-tree (formats/tree/TreeResultPrinter.php, line 149), while TreeAndMenu expects a ul list. My previous version of SRF didn't put it in the div container AFAIK. I solved this issue for now by removing the Html:rawElement method and simply returning the result.
`return Html::rawElement( 'div', [ 'class' => 'srf-tree' ], $resultText );`
becomes
`return $resultText;`

I'm not sure what the rationale behind the div container was, and whether this is a SRF or TreeAndMenu bug. If it is the latter please let me know and I will log the bug there.

**Comment by s7eph4n** [comment]
The rationale was to be able to style the tree. But compatibility with Tree and menu is a problem. @kghbln, any ideas?

**Comment by kghbln** [comment]
Indeed, without the possibility to style the tree this format is as useless as it is now apparently in a very different way for users of the TreeAndMenu extension. However before I had to manually wrap the query into a individual div container, so this was a way out for the tree users while now there is no way out for the TreeAndMenu users. In case there is no other smart way reverting back looks like the easiest solution.

**Comment by krowlandnet** [comment]
I'm quite a noob, but is a parameter for the div wrapper in LocalSettings an option? That way, users can decide what they want?

**Comment by s7eph4n** [comment]
Well, maybe. But then you couldn't use both at the same time on the same wiki. And generally I'd like to avoid yet another global variable. 

I see two possibilities:
1. Somehow recognize that the result of `#ask` is fed into Tree And Menu and then don't wrap it in the div. 
2. Somehow set a class attribute on the `ul` instead of the div.

**Comment by mwjames** [comment]
> Somehow set a class attribute on the ul instead of the div.

Not a very appealing idea.

> Or maybe 3. a parameter on the ask function, but that also would mean yet another parameter.

I think we already have the `class` parameter for common use cases in other printers, introducing it here wouldn't necessarily bloat the interface.

> Indeed, without the possibility to style the tree this format is as useless as it is now apparently in a very 

If we have the `class` parameter available (which by default is empty), any setting to it should be assumed as an intent to separate the instance from others and therefore allow it to be wrap with a div + class and for when no class is set, except its "pure" existence by only outputting `ul`/`il`.
