### ISSUE TITLE
Timeline format reports a "Timeline.DefaultEventSource is not a constructor"

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticResultFormats#292]
### Setup

- MW version:  1.30-alpha
- DB (MySQL etc.): *
- PHP version: *
- SMW version: 2.5.6
- SRF version: 2.5.2 (any version)
- Browsers and versions (if applicable): Chrome

### Issue

![image](https://user-images.githubusercontent.com/1245473/29664220-b55f78e2-8909-11e7-99b4-a02380dcdbad.png)

![image](https://user-images.githubusercontent.com/1245473/29664161-7efb61f8-8909-11e7-80cf-d4ffbf916c00.png)

Most likely relates to:

*  https://github.com/simile-widgets/exhibit/issues/143
* https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/9a2d405d28e18ef50cdda12996d3b260c29e2127
* Async, queue approach of the ResourceLoader

**Comment by kghbln** [comment]
@mwjames Cool! Probably worth backporting?!

**Comment by kghbln** [comment]
The fix was backported to the 2.5.x branch so it will ship with SRF 2.5.3.
