### ISSUE TITLE
Timeline, Eventline issues with subobjects

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticResultFormats#294]
### Setup

- MW version:
- DB (MySQL etc.):
- PHP version:
- SMW version: 3.0-alpha
- SRF version: 2.5.2 (and any other version) !!
- Browsers and versions (if applicable):

### Issue

Timeline shows no subobject

![image](https://user-images.githubusercontent.com/1245473/29743325-aec1fd9e-8aca-11e7-9142-7c4725525019.png)

Eventline uses a wrong target url

![image](https://user-images.githubusercontent.com/1245473/29743310-727bd86e-8aca-11e7-9db7-5108cbdac118.png)

**Steps to reproduce**

* https://sandbox.semantic-mediawiki.org/wiki/Issue/293_(SRF)

**Comment by kghbln** [comment]
The fix was backported to the 2.5.x branch so it will ship with SRF 2.5.3.
