### ISSUE TITLE
Filtered format: Show error in user language

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticResultFormats#302]
### Setup

- MW version:
- DB (MySQL etc.):
- PHP version: 7.1
- SMW version: 3.x
- SRF version: 3.x
- Browsers and versions (if applicable):

### Issue

While skimming the sandbox, I found:

![image](https://user-images.githubusercontent.com/1245473/30241714-da898682-95c3-11e7-96bb-ecd7db0f9eea.png)

It is preferable for errors [0] to be displayed in the selected user language.

[0] https://sandbox.semantic-mediawiki.org/wiki/Filtered/Map_view

**Comment by s7eph4n** [comment]
Fixed.
