### ISSUE TITLE
Filtered format: filters should only filter values when touched

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticResultFormats#303]
When using the filtered format, an ask query like this
```
{{#ask:
 [[Category:Tools]]
 |?Year# -|+filter=number
 |format=filtered
}}
```
works like
```
{{#ask:
 [[Category:Tools]]
 [[Year::+]]
 |?Year# -|+filter=number
 |format=filtered
}}
```
Because entries who don't have a year set, get not displayed. 

The desired functionality is that the format shows everything that the query should bring up and omit only entries once a filter is touched by the user.

**Comment by s7eph4n** [comment]
The clean solution here would probably be some kind of on/off switch for filters.

**Comment by s7eph4n** [comment]
On second thought I am not sure if adding that on/off switch is a good idea.
It would probably overload the UI and might be too complicated for casual browsing.

For the moment I have added #323. Would that be good enough?
