### ISSUE TITLE
Implement vtimezone in icalendar format

### ISSUE THREAD

**Issue by hidrarga** [SemanticMediaWiki/SemanticResultFormats#306]
Hello !

I noticed that the icalendar format does not implement the vtimezone component yet. This is a problem as I use this format to export events on a google calendar. However, the events doesn't appear correctly (for instance with a +2 hours difference). 

I'm willing to implement this, but I would need to know how to obtain timezone information in mediawiki. I tried with $wgLocalTimezone but it always returns null.

Thanks,
HgO

**Comment by mwjames** [comment]
> I'm willing to implement this, but I would need to know how to obtain timezone information in mediawiki. I tried with $wgLocalTimezone but it always returns null

I'm not entirely clear about the use case (TZ of the user setting, TZ of the annotated time, time correction etc.) but in SMW we do have something like [0] and for a stored TZ of an annotated value, the TZ in its serialized form is available via [1] which contains a code and will be resolved during the output by [2].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/LocalTime.php
[1]https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/dataitems/SMW_DI_Time.php#L175-L181
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/DataValues/Time/Timezone.php

**Comment by hidrarga** [comment]
>I tried with $wgLocalTimezone but it always returns null.

So, I managed to get this work ! I could implement a generator for the vtimezone component, I will propose a pull request in a few minutes.

>I'm not entirely clear about the use case

My bad, I should have been more precise. For the moment, I'm only assuming that all the events are on the same timezone, that is the server's timezone. Although, in the future, we could change that in order to handle several timezones... Anyhow, thanks for your help ! :)
