### ISSUE TITLE
Filtered format: i18n for placeholder "Select a filter value"

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticResultFormats#312]
### Setup

- SRF version: 2.5.2

### Issue

I couldn't find a i18n key for the placeholder "Select a filter value". Please provide one, if it does not exist. Thanks.

**Comment by s7eph4n** [comment]
Should be `srf-filtered-value-filter-placeholder`.

**Comment by jaideraf** [comment]
Oh, right, BTW it was translated last week, sorry. My mistake.
