### ISSUE TITLE
EventCalendar format: Fatal error - Call to undefined method SRF\EventCalendar::getSkin()

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#317]
### Setup
- MediaWiki | 1.29.1 (a69ecd8)18:59, 23. Aug. 2017
- PHP | 5.6.30-0+deb8u1 (apache2handler)
- MariaDB | 10.0.32-MariaDB-1~jessie
- Semantic MediaWiki | 3.0.0-alpha (8ff300d) 17:24, 10. Okt. 2017
- Semantic Result Formats | 3.0.0-alpha (4ca8288) 08:38, 9. Okt. 2017

### Issue
While doing the automated weekly "rebuildData.php" run on sandbox the script fataled with
```
PHP Fatal error:  Call to undefined method SRF\EventCalendar::getSkin() in /../w/extensions/SemanticMediaWiki/includes/queryprinters/RawResultPrinter.php on line 87
Fatal error: Call to undefined method SRF\EventCalendar::getSkin() in /../w/extensions/SemanticMediaWiki/includes/queryprinters/RawResultPrinter.php on line 87
```

**Comment by mwjames** [comment]
Relates to [0] and [1]. There are no tests in place for this format
hence [1] has missed the issue.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2748
[1] https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/315
