### ISSUE TITLE
Timeline format: Using param "timelinestart" and "timelineend" results in empty timeline

### ISSUE THREAD

**Issue by revansx** [SemanticMediaWiki/SemanticResultFormats#326]
### Setup

- MW version: 1.28.2
- DB (MySQL etc.): 5.5.56-MariaDB
- PHP version: 5.6.31 (apache2handler)
- SMW version: 2.5.2
- SRF version: 2.5.2 (2b22309) 16:47, 15 October 2017	
- Browsers and versions (if applicable):

### Issue 
Use of the SRF Timeline parameters "timelinestart" and "timelineend" not only do not work, but they kill the ASK such that the timeline renders without complaint, but contains no events.

Is have tried various date formats such as: "12:00 01/01/2001" and just "01/01/2001".

documentation does not exist (that I can find) on the timeline format beyond the basic usage from the timeline help page ... specifically, the parameters in question are not elaborated on in the main help article at https://www.semantic-mediawiki.org/wiki/Help:Timeline_format 

-Rich

**Comment by s7eph4n** [comment]
Wow, that format is ancient. Most of the code is from 2008. :open_mouth:

**Comment by kghbln** [comment]
@revansx Thanks for reporting.

From reading the [e-mails in the mailing list](https://sourceforge.net/p/semediawiki/mailman/message/36078428/) I believed that both parameters were working before the update and broke after the recent fix. However when looking at the docu I conclude that these could not have possibly worked either before since these two parameters hold the name of a property of datatype date and not a direct value.

**Comment by kghbln** [comment]
My quick attempt to work out the magic behind these parameters did not succeed. However the docu wiki is cluttered with heaps of distracting data so, i.e. a mess so probably using the sandbox wiki to find out how to use the parameter is not the worst of ideas. I can also imagine that using timelinestart and timelineposition at the same time may not work.

**Comment by s7eph4n** [comment]
It should work. As far as I can tell the format can show punctual events and intervals. In `timelinestart` and `timelineend` you have to specify the names of the properties that hold the respective values for each result item.
If you have punctual events use only `timelinestart`.
`timelineposition` just tells the format where it should initially focus.
There is no way (and no point) to tell the format the start of the complete timeline. If you need that, just add a condition to the query.

**Comment by kghbln** [comment]
@revansx Have you revisited this in light of this new info?

**Comment by revansx** [comment]
[There is no way (and no point) to tell the format the start of the complete timeline. If you need that, just add a condition to the query.] 

Hmmm..  Maybe I'm just confused.. I'd like to stack multiple timelines on top of each other and I'd like to be able to program them to initially render with the same start and stop dates regardless of the results.

I am hard coding the start and stop dates into the ask statement per those parameters. 

Am I using this the wrong way? What is meant by "If you need that, just add a condition to the query."

Thanks!

**Comment by s7eph4n** [comment]
That's not what this format does. It just takes the results of your query and outs them on a timmeline. See the example in the docs: https://www.semantic-mediawiki.org/wiki/Help:Timeline_format#Example

If it works. The format seems to try running JS before it is loaded at times. It has probably never been properly updated for the ResourceLoader. I don't think it should be used in production.

**Comment by mwjames** [comment]
> If it works. The format seems to try running JS before it is loaded at
> times. It has probably never been properly updated for the ResourceLoader. I
> don't think it should be used in production.

I think I specifically addressed this with #293.

**Comment by mwjames** [comment]
> Hmmm..  Maybe I'm just confused.. I'd like to stack multiple timelines on
> top of each other and I'd like to be able to program them to initially

@revansx Generally, when discussion an abstract (or concrete) issue
please provide an example on wiki (as outlined in the beginning of an
issue, the sandbox is provided for exactly this reason). This avoids
guessing on the particular circumstances and helps project volunteers
to make the most of their time in resolving an issue.

**Comment by s7eph4n** [comment]
> I think I specifically addressed this with #293.
Hmm, in that case I don't know. In any case I got errors that looked like race conditions between loading and execution several times.

**Comment by mwjames** [comment]
What is the status with this issue?

**Comment by s7eph4n** [comment]
The original question/issue is solved, I think. The loading issue needs more investigation.

**Comment by mwjames** [comment]
>The original question/issue is solved,

:+1: 

> I think. The loading issue needs more investigation.

#339
