### ISSUE TITLE
Latest format ignores |default=

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticResultFormats#344]
format=latest ignores settings in |default

an example can be seen here:
https://sandbox.semantic-mediawiki.org/wiki/LatestTest

the working query has results and displays what is put in |intro=... followed by the latest date.
the not working query has no results, should display what is put in  |default=
but instead displays nothing

probably true also with  earliest format?

**Comment by mwjames** [comment]
This issue relates to:

https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/eaaec343d6321fac44ec0179550d6b334bdb2dec/formats/time/SRF_Time.php#L93-L97

The format redefines the `default` as `'type' => 'integer', ` and in your example using a string value `default=NO!` (which is validated as to not conform with the parameter definition) will be ignored as default output.

**Comment by krabina** [comment]
So this clearly a bug. |default is a standard parameter used when a qery delivers no result. So usually text is what is put there...

**Comment by mwjames** [comment]
> So usually text is what is put there...

In case this is the expected behaviour, you just has have to remove the parameter from the definition so that the original `default` definition can be used instead.

**Comment by mwjames** [comment]
> So usually text is what is put there...

In case this is the expected behaviour, you just has have to remove the parameter from the definition so that the original `default` definition can be used instead.

**Comment by mwjames** [comment]
> So this clearly a bug.

I'm not sure about this since it was added with an intend [0].

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/06b3d469a4fd5bab930d2a5cd997b8b907ed0051

**Comment by mwjames** [comment]
Anyway, in case some one wants to push a PR, please consider adding an integration tests so the intend is clear and testable.

**Comment by krabina** [comment]
I would want to but feel not able to ;-)
