### ISSUE TITLE
Kanban board format?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticResultFormats#347]
Question: Would it make sense to support something like kanban boards [0]?

PS: I'm not going to implement this but someone might find the idea appealing and was looking to make a contribution.

[0] https://codepen.io/riktar/pen/KqZpgL
[1] https://github.com/riktar/jkanban

**Comment by gesinn-it** [comment]
Question: Let's say the status of a kanban item is stored in a property of this item. What would be the best way to implement changing the value of that property when an drop event occurs? Something like PF's #autoedit [0]?

[0] https://www.mediawiki.org/wiki/Extension:Page_Forms/Linking_to_forms#Modifying_pages_automatically

**Comment by mwjames** [comment]
> way to implement changing the value of that property when an drop event occurs? Something like PF's #autoedit [0]?

I'd say split the task into two possible modes, the first being a simple display without a possibility to alter the state, and the second to allow changing the state using a parameter switch but this should happen without reliance on PF. Use the standard API because people like myself don't use PF and #autoedit would make it a hard dependency which I'm not in favour of.

**Comment by krabina** [comment]
Since there is a dedicated extension for this and there has not been any movement here, I am closing it.
https://github.com/enterprisemediawiki/SemanticActions
