### ISSUE TITLE
Filtered format: value filter labels always use printoutValue

### ISSUE THREAD

**Issue by matthew-a-thompson** [SemanticMediaWiki/SemanticResultFormats#354]
This issue pertains to code on the 2.5.x branch of SemanticResultFormats.
Changes to ValueFilter.ts as introduced in commit 23f6708df246dba3e3ead04e9b1954e32698ca01 have the behavior of always using the printoutValue as the label for a value filter option, rather than using this value only when formattedValue is falsy. In cases where the property value is a wiki page, this leads to behavior where the value of the label is the name of the wiki page, rather than the page's display title.

https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/2.5.x/formats/filtered/resources/ts/Filtered/Filter/ValueFilter.ts#L127 is the current location of the responsible code.

**Comment by s7eph4n** [comment]
Curious. I am sure I had a reason to remove the formatted value, only I don't remember. I'll have to investigate.

**Comment by gesinn-it** [comment]
To my opinion, if a Display Title is set for a page, this should always be used in the filters. We often have a wiki page name with a UUID plus a "human readable" Display Title.

E.g.:
Building:C67696c9-d823-4a1a-8001-e20786b75b8e with Display Title "Factory Block A"

**Comment by matthew-a-thompson** [comment]
@s7eph4n Did you end up discovering the reason why this change was made? If it would be acceptable to change it back, I can put together a pull request to make that change.

**Comment by s7eph4n** [comment]
Already have one. Just need to push it. Will do it tonight.
