### ISSUE TITLE
Filtered format: Fatal error: Call to undefined method SRF\Filtered\Filtered::getOutput()

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticResultFormats#362]
### Setup

- MW version: 1.30.0 (830bb58)
- DB (MySQL etc.): 10.0.33-MariaDB-1~jessie
- PHP version: 5.6.30-0+deb8u1 (apache2handler)
- SMW version: 3.0.0-alpha (5771144)
- SRF version: 3.0.0-alpha (04b9aab)

### Issue

```
Fatal error: Call to undefined method SRF\Filtered\Filtered::getOutput() in /../w/extensions/SemanticResultFormats/formats/filtered/src/Filtered.php on line 267
```

**Steps to reproduce**

- https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3ARequ%C3%AAter&q=%5B%5BHas+text%3A%3A%2B%5D%5D&po=&eq=yes&p%5Bformat%5D=filtered&p%5Bsource%5D=&p%5Blimit%5D=200&p%5Boffset%5D=0&p%5Blink%5D=all&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bviews%5D=&p%5Bfilter+position%5D=top&p%5Blist+view+type%5D=list&p%5Blist+view+template%5D=&p%5Blist+view+introtemplate%5D=&p%5Blist+view+outrotemplate%5D=&p%5Bcalendar+view+start%5D=&p%5Bcalendar+view+end%5D=&p%5Bcalendar+view+title%5D=&p%5Bcalendar+view+title+template%5D=&p%5Btable+view+class%5D=wikitable+sortable&p%5Bmap+view+marker+position+property%5D=&p%5Bmap+view+marker+icon+property%5D=&p%5Bmap+view+marker+icons%5D=&p%5Bmap+view+height%5D=auto&p%5Bmap+view+zoom%5D=&p%5Bmap+view+min+zoom%5D=&p%5Bmap+view+max+zoom%5D=&p%5Bmap+view+marker+cluster%5D=1&p%5Bmap+view+marker+cluster+max+zoom%5D=&p%5Bmap+view+marker+cluster+radius%5D=&p%5Bmap+view+marker+cluster+zoom+on+click%5D=1&sort_num%5B%5D=&order_num%5B%5D=asc&sort_num%5B%5D=&order_num%5B%5D=asc&eq=yes

**Comment by s7eph4n** [comment]
Broken since https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2748
Will probably need getter/setter for extension data in SMWOutputs.

Not this year anymore, I'm afraid.

**Comment by mwjames** [comment]
> Broken since SemanticMediaWiki/SemanticMediaWiki#2748
Will probably need getter/setter for extension data in SMWOutputs.

```
			$getter = [ $this->getOutput(), 'getProperty' ];
			$setter = [ $this->getOutput(), 'setProperty' ];
```

Sorry for the trouble, if you think you need access to the `OutputPage` object on a special page then maybe you could directly access `\RequestContext::getMain()`. If possible, I'd like to avoid the kitchen sink (as noted in 2748) object.

> Not this year anymore, I'm afraid.

:+1: 

Backtrace
```
#0 ...\extensions\SemanticResultFormats\formats\filtered\src\Filtered.php(203): SRF\Filtered\Filtered->addConfigToOutput(string, array)
#1 ...\extensions\SemanticMediaWiki\src\Query\ResultPrinters\ResultPrinter.php(307): SRF\Filtered\Filtered->getResultText(SMWQueryResult, integer)
#2 ...\extensions\SemanticMediaWiki\src\Query\ResultPrinters\ResultPrinter.php(272): SMW\Query\ResultPrinters\ResultPrinter->buildResult(SMWQueryResult)
#3 ...\extensions\SemanticMediaWiki\src\MediaWiki\Specials\SpecialAsk.php(257): SMW\Query\ResultPrinters\ResultPrinter->getResult(SMWQueryResult, array, integer)
#4 ...\extensions\SemanticMediaWiki\src\MediaWiki\Specials\SpecialAsk.php(187): SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#5 ...\includes\specialpage\SpecialPage.php(522): SMW\MediaWiki\Specials\SpecialAsk->execute(NULL)
#6 ...\includes\specialpage\SpecialPageFactory.php(578): SpecialPage->run(NULL)
#7 ...\includes\MediaWiki.php(287): SpecialPageFactory::executePath(Title, RequestContext)
#8 ...\includes\MediaWiki.php(851): MediaWiki->performRequest()
#9 ...\includes\MediaWiki.php(523): MediaWiki->main()
#10 ...\index.php(43): MediaWiki->run()
#11 {main}
```
