### ISSUE TITLE
vCard format: introduce `filename` parameter

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticResultFormats#371]
### Setup

- MW version:1.27
- SRF version: 2.5.4

### Issue

In contrast to the csv export format, the vCard format does not know a |filename= parameter. Every result format that delivers a file should have the possibility of specifying a filename.

**Comment by kghbln** [comment]
Thanks for reporting. Use the `searchlabel` paramter for this like e.g.:
```text
Download the vCard of {{#ask:
 [[Category:Person]]
 |?firstname
 |?lastname
 |?mail=email
 |?url=homepage
 |?skype=note
 |format=vcard
 |searchlabel=Bernhard Krabina
}}
```
@krabina Does this work for you?

**Comment by krabina** [comment]
yes, thank you. But it does someting a little different. 
I'd like to have "vCard" displayed and the resulting filename is e. g. Krabina.vcf
Your workaround is fine for me at the moment, but I think this should be streamlined according to the CSV format. (Haven't tried, but I guess, the same thing happens with Excel format).

**Comment by kghbln** [comment]
This is why I did not close this one but instead labeled as enhancement. Same as this one goes for the "bibtex" format.
