### ISSUE TITLE
Thumbnails are displayed twice

### ISSUE THREAD

**Issue by DanielDIQA** [SemanticMediaWiki/SemanticResultFormats#372]
Hi there!

the issue can be seen in the demo:
https://www.semantic-mediawiki.org/wiki/Demo:Datatables_compared_to_broadtable

The caption is supposed to be displayed next to the thumbnail. Apparently the caption is replaced by the thumbnail which is displayed twice in each line.

I guess thats a bug.

All the best
Daniel

**Comment by kghbln** [comment]
Thanks for reporting. I am sure that this is a variant of https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/188
