### ISSUE TITLE
Filtered format: select2 list elements rendering outside of containing element

### ISSUE THREAD

**Issue by matthew-a-thompson** [SemanticMediaWiki/SemanticResultFormats#373]
### Setup

- MW version: 1.29.0
- DB (MySQL etc.): MySQL 5.6.39
- PHP version: 5.5.38
- SMW version: 2.5.5
- SRF version: 2.5.5-alpha (aad259d)
- Browsers and versions (if applicable): IE11, Chrome

### Issue

When a value filter is used in the filtered result format, it can be displayed either as a list of checkboxes or as a scrollable menu that adds selected elements to a list (a jquery select2 element.) When displaying as a select2 element, the li elements representing each selection are rendering outside of their container.

**Steps to reproduce**

IE11: From the output of a filtered format query with a select2 element, select an item from the select2 list.
Chrome: From the output of a filtered format query with a select2 element, select items from the select2 list. The issue will appear once the total width of selected elements is sufficiently large (greater than the width of the containing element.)

**Expected result:**

li elements with the names of the selected items appear within the containing ul element.

**Observed result:**

li elements appear almost entirely outside the containing ul element, and are only barely visible. See attached screenshots for the observed result in IE11 and Chrome.

In IE11, with the li element barely visible on the left edge of the containing ul element:
![image](https://user-images.githubusercontent.com/22081959/36452918-466dfe66-1664-11e8-92f1-9b42fcfb492f.png)

In IE11, with the li element highlighted:
![image](https://user-images.githubusercontent.com/22081959/36452863-1d71cc68-1664-11e8-8cbd-f31b63ca3079.png)

In Chrome, with the li element barely visible on the left edge of the containing ul element:
![image](https://user-images.githubusercontent.com/22081959/36452936-572bc346-1664-11e8-8005-26364929d1e8.png)

In Chrome, with the li element highlighted:
![image](https://user-images.githubusercontent.com/22081959/36452949-6045bc84-1664-11e8-89e6-54e5dfb31a56.png)

**Proposed solution:**
The placeholder text li element (class="select2-search select2-search--inline") currently has the css "float: none" applied to it, due to https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/2.5.x/formats/filtered/resources/css/ext.srf.filtered.value-filter.less#L72. Removing this css block appears to resolve the issue. The element will then have "float: left" applied to it, due to https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/2.5.x/formats/filtered/resources/css/ext.srf.filtered.select.css#L39. The li elements representing selected values render correctly when "float: left" is applied to the placeholder li element. I will be creating a pull request shortly that implements this solution.

**Comment by kghbln** [comment]
Thanks a lot for reporting and providing a pull for the fix! I will now request a code review from @s7eph4n

**Comment by s7eph4n** [comment]
Thanks for the report. Do you have an example where I could see this live? Or could you create on, e.g. on http://sandbox.semantic-mediawiki.org/?

**Comment by matthew-a-thompson** [comment]
@s7eph4n I've created https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Mathompson/filtered to demonstrate this. Curiously, it doesn't seem to want to demonstrate the issue in Chrome, but it does still appear in IE11.

**Comment by s7eph4n** [comment]
Thanks!
That's probably the reason why I did not notice this before. I usually use Firefox or Chrome and only occasionally IE.
I'll have to find out why I put that `float: left` in int the first place.

**Comment by matthew-a-thompson** [comment]
@s7eph4n can you give me an update on the status of your review of the pull request?

**Comment by s7eph4n** [comment]
Still no idea, I'm afraid. I'd say lets merge and see if somebody else complains.

**Comment by s7eph4n** [comment]
Fixed with #374
