### ISSUE TITLE
Gallery format: image dimensions displayed in the captions

### ISSUE THREAD

**Issue by the1gofer** [SemanticMediaWiki/SemanticResultFormats#375]
### Setup

- MW version: 1.3
- DB (MySQL etc.): MySQL | 5.6.32-78.1
- PHP version:   PHP | 7.0.25 (cgi-fcgi)
- SMW version: 2.5.5
- SRF version: 2.5.4
- Browsers and versions (if applicable): n/a

### Issue

Gallery format displays image dimensions in the captions, with no apparent option to remove them. 

example:  http://crewsgenealogy.com/wiki/index.php?title=United_States_Census,_1870#Images

**Comment by mwjames** [comment]
> Gallery format displays image dimensions in the captions, with no apparent
> option to remove them.

Issue introduced by WMF in [0].

You have two options, either you ask WMF to restore the default
behaviour be setting `protected $mShowDimensions;` to `protected
$mShowDimensions = false;` or you extend the gallery class with
something like:

```
@@ -65,10 +65,15 @@ class Gallery extends ResultPrinter {
 		// #224
 		$ig = class_exists( '\TraditionalImageGallery' ) ? new
\TraditionalImageGallery() : new \ImageGallery();

 		$ig->setShowBytes( false );
 		$ig->setShowFilename( false );
+
+		if ( method_exists( $ig, 'setShowDimensions' ) ) {
+			$ig->setShowDimensions( false );
+		}
```

In either case, I'd like to see an integration test to avoid a similar
situation by the next release before I consider pressing the merge
button.

[0] https://github.com/wikimedia/mediawiki/commit/ebb168035933dac7f8f4da6f88ee3ed5b5148b8e#diff-c2c646962548f5bc6daffb94201859ef

PS: I won't create a PR and only added the necessary context to the issue.

Cheers

**Comment by the1gofer** [comment]
is that something that can be done in the config file?  or would I need to
find it someplace else?

**Comment by mwjames** [comment]
> is that something that can be done in the config file?  or would I need to
> find it someplace else?

Not sure what you mean with config but as outlined in both cases some
code changes are necessary. There is no config because the issue was
introduced in the code base that creates the image gallery.

**Comment by the1gofer** [comment]
Ok, think that’s probably a bit beyond me, but I’ll poke around and see
what I can find. Do you know which file it can be found in?

**Comment by the1gofer** [comment]
Never mind, please excuse my ignorance. Thanks for the help.

**Comment by kghbln** [comment]
Thanks for reporting.

> either you ask WMF to restore the default behaviour be setting `protected $mShowDimensions;` to `protected $mShowDimensions = false;`

From experience we should not hold our breath here, so updating the gallery format is probably the better solution.

**Comment by anrake** [comment]
Hi is there any progress to update SRF for this issue?

**Comment by mwjames** [comment]
> Hi is there any progress to update SRF for this issue?

I think I gave all the required information for community members to act on. If nothing has happened yet then project members didn't find the time to make the necessary changes, yet we are happily accept PRs.

**Comment by anrake** [comment]
Thanks, I think I'm a little inexperienced to help out so will wait for some kind person to hopefully fix this.
