### ISSUE TITLE
.gitignore exludes formats/Exhibit/exhibit/extensions

### ISSUE THREAD

**Issue by jhf2442** [SemanticMediaWiki/SemanticResultFormats#377]
### Issue

.gitignore excludes extensions/ subdirectory, leading to exclusion of formats/Exhibit/exhibit/extensions/*
therfore, commit'ing the installation of SRF results in incomplete directory state

what is the purpose of having extensions/ excluded in .gitignore ?

**Comment by kghbln** [comment]
Thanks for reporting. I personally do not know. 

Ping @JeroenDeDauw who added this to the file. 

Ping @s7eph4n I understand that exhibit was abandoned though it has seen some activity recently. Time to remove the code altogether or is it worth keeping it for interested parties.

**Comment by s7eph4n** [comment]
The latest release I could find is Exhibit 3.1.1. from 2014. After that there was an RC for 3.1.2 but that apparently never made it to production. If you ask me unless somebody wants to take ownership of that format we should remove it (and ideally find a replacement).

**Comment by s7eph4n** [comment]
Forgot the link: https://github.com/simile-widgets/exhibit

**Comment by kghbln** [comment]
Thanks for your comment.

> (and ideally find a replacement)

I believe that the filtered format was or is meant to take this role.

**Comment by JeroenDeDauw** [comment]
Composer normally installs into ./vendor, but MW extensions go into ./extensions. This is where the .gitignore entry came from. Perhaps not needed anymore.

**Comment by kghbln** [comment]
@JeroenDeDauw Thanks for your info.

> Perhaps not needed anymore.

How can we find out?

**Comment by JeroenDeDauw** [comment]
This is basically only relevant for development, so I suppose we could just remove it and see if someone gets mad about it.
