### ISSUE TITLE
Google bar and Google pie formats: Still using the Google Chart API via http

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#378]
### Setup

- MediaWiki | 1.27.4 (317104c)23:34, 7 February 2018
- PHP | 7.0.25-0ubuntu0.16.04.1 (apache2handler)
- MySQL | 5.7.21-0ubuntu0.16.04.1
- Semantic MediaWiki | 2.5.7-alpha (e0c6791) 15:00, 14 February 2018
- Semantic Result Formats | 2.5.5-alpha (aad259d) 15:31, 11 December 2017

### Issue

[Google bar](https://www.semantic-mediawiki.org/wiki/Help:Google_bar_format) and [Google pie](https://www.semantic-mediawiki.org/wiki/Help:Google_pie_format) are still calling the respective Google Chart API via http causing mixed content warnings.

**Comment by mwjames** [comment]
> [Google bar](https://www.semantic-mediawiki.org/wiki/Help:Google_bar_format)
> and [Google
> pie](https://www.semantic-mediawiki.org/wiki/Help:Google_pie_format) are
> still calling the respective Google Chart API via http causing mixed content
> warnings.

These services should be disabled by default with a notice that if
enabled, a connection to a third-party site may leak data which the
wiki, SMW, or SRF has not control over and cannot take any
responsibility in case of a misuse.

Cheers

**Comment by kghbln** [comment]
> These services should be disabled by default

They are indeed disabled by default.

> with a notice that if enabled, a connection to a third-party site may leak data which the wiki, SMW, or SRF has not control over and cannot take any responsibility in case of a misuse.

I will add this to the README of the result formats. On wiki we already have this warning.
