### ISSUE TITLE
Excel format: phpoffice/phpexcel deprecated

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#382]
### Setup

- MW version: all versions
- DB (MySQL etc.): all versions
- PHP version: all versions
- SMW version: all versions
- SRF version: all versions

### Issue
The [excel format](https://www.semantic-mediawiki.org/wiki/Help:Excel_format) is no longer supporting maintained libraries since the underlying ["phpoffice/phpexcel"](https://github.com/PHPOffice/PHPExcel) library was deprecated and replaced by ["phpoffice/phpspreadsheet"](https://github.com/PHPOffice/PhpSpreadsheet).

It will be great if support for the "phpoffice/phpspreadsheet" library is added.

**Comment by kghbln** [comment]
@netbrain FYI Migration effort will be much appreciated. :)

**Comment by mwjames** [comment]
## Migration from PHPExcel

- https://phpspreadsheet.readthedocs.io/en/develop/topics/migration-from-PHPExcel/
- https://stackoverflow.com/questions/48122220/phpspreadsheet-where-is-phpexcel-worksheet-drawing

**Comment by mwjames** [comment]
This format should be renamed to `spreadsheet` with `excel` being alias of `spreadsheet`.

**Comment by s7eph4n** [comment]
Is there a reason not to include phpoffice/phpspreadsheet by default?
The situation where the excel format is activated by default but falls back to table if phpoffice/phpspreadsheet is not installed is awkward. If at all it should probably fall back to csv format.

**Comment by kghbln** [comment]
> Is there a reason not to include phpoffice/phpspreadsheet by default?

Since excel is active by default - no. However, should it be active by default since an extra lib is required.

> If at all it should probably fall back to csv format.

Sounds reasonable.

**Comment by kghbln** [comment]
> Well, there is a number of formats using external libraries. the only difference is, that this one is pulled in by composer.

So yes to both of them. :)
