### ISSUE TITLE
Tree format: Undefined index: template arguments

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#390]
### Setup
- MediaWiki | 1.30.0 (01d9055)18:41, 23 April 2018
- PHP | 7.0.27-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.0.0-alpha (497c969) 20:17, 29 April 2018
- Semantic Result Formats | 3.0.0-alpha (540e63e) 09:28, 19 April 2018

### Issue

When rebuilding data I get the following notices:

```
PHP Notice:  Undefined index: template arguments in /../w/extensions/SemanticResultFormats/formats/tree/TreeResultPrinter.php on line 74

Notice: Undefined index: template arguments in /../w/extensions/SemanticResultFormats/formats/tree/TreeResultPrinter.php on line 74
PHP Notice:  Undefined index: template arguments in /../w/extensions/SemanticResultFormats/formats/tree/TreeResultPrinter.php on line 81

Notice: Undefined index: template arguments in /../w/extensions/SemanticResultFormats/formats/tree/TreeResultPrinter.php on line 81
PHP Notice:  Undefined index: template arguments in /../w/extensions/SemanticResultFormats/formats/tree/TreeResultPrinter.php on line 82

Notice: Undefined index: template arguments in /../w/extensions/SemanticResultFormats/formats/tree/TreeResultPrinter.php on line 82
PHP Notice:  Undefined index: template arguments in /../w/extensions/SemanticResultFormats/formats/tree/TreeResultPrinter.php on line 74
```

I think this was an expected issue in connection with https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2488

@s7eph4n FYI

**Comment by s7eph4n** [comment]
Yes, this is probably connected.

**Comment by mwjames** [comment]
@s7eph4n Do you think you could have look at it since those are the tests that currently fail after I fixed [0] last week.

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/873aebd049d3b2943a6733699944b4a0f269991b

**Comment by s7eph4n** [comment]
I'll have a look, no problem.

**Comment by JeroenDeDauw** [comment]
:(

**Comment by JeroenDeDauw** [comment]
Fixed by https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/414/files
