### ISSUE TITLE
Datatables format: columnsearchinput field is always disabled

### ISSUE THREAD

**Issue by matthew-a-thompson** [SemanticMediaWiki/SemanticResultFormats#399]
### Setup

- MW version: 1.29.0 (a112e4f) (local development environment) and 1.31.0 (568bd6d) (smw sandbox)
- DB (MySQL etc.): MySQL 5.6.41 (local development environment) and MariaDB 10.1.26-MariaDB-0+deb9u1 (smw sandbox) 
- PHP version: 7.0.31 (local development environment) and 7.0.30-0+deb9u1 (smw sandbox)
- SMW version: 2.5.5 (local development environment) and 3.0.0-alpha (7b51392) (smw sandbox)
- SRF version: 2.5.5-alpha (a4c53b6) (local development environment) and 3.0.0-alpha (1093a59) (smw sandbox)
- Browsers and versions (if applicable): tested in Microsoft Edge 41.16299.547.0 and Google Chrome 68.0.3440.84 (32-bit)

### Issue

When producing output in the datatables format, a "Column filters and search" panel can be opened to provide filtering and search based on values in a specified column. Column searching is supported by two form elements: a select element with a list of column names, and a text field in which the user can enter a search string. The text field is initially disabled, but should become enabled when a column is selected for searching. However, it remains disabled even when a column is selected.

**Steps to reproduce**

Demonstration page: https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Mathompson/datatables

1. Click the button in the top-right of the datatables output to show the "Column filters and search panel"
2. Note that the text field in the "Column filters and search" panel shows the placeholder text "Search..." and is currently disabled, and that the dropdown menu immediately above the text field is blank.
3. Select a column from the dropdown menu immediately above the text field (this is the single-selection dropdown menu, not the column-visibility-toggle dropdown menu).

**Expected result:** When a column is selected in step 3, the text field should become enabled.

**Observed result:** When a column is selected in step 3, the text field remains disabled.

Luckily, the cause of this bug is relatively simple: a small error in the optionslist widget event handler definition. There may be related errors in other places in this file.

https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/74b6d7c0ccea3c8e1a8560ba36d37b1be7207d00/resources/widgets/ext.srf.widgets.optionslist.js#L132-L143

The call `that.attr( 'value' )` on line 140 always returns "undefined", because `that` refers to the select element, which has no `value` attribute. Similarly, the call `that.is(':selected')` on line 139 will always return `false`.

**Comment by kghbln** [comment]
Thanks a lot for reporting this issue. It appears that you may very well be able to provide a pull request. However wait a sec for this until @mwjames comments since I am not sure how this relates to the library used.

**Comment by mwjames** [comment]
> However wait a sec for this until @mwjames comments since I am not sure how this relates to the library used.
> Luckily, the cause of this bug is relatively simple: a small error in the optionslist widget event handler definition. There may be related errors in other places in this file.

I haven't looked at this format for years and as far as I remember the options list is only used in connection with the SRF datatables format.

We would appreciate a PR.

**Comment by kghbln** [comment]
Thanks a lot for commenting.

> We would appreciate a PR.

@matthew-a-thompson Go for it! This will be highly appreciated.
