### ISSUE TITLE
Composer installation conflicts with mediawiki/maps package

### ISSUE THREAD

**Issue by aso-mehmudi** [SemanticMediaWiki/SemanticResultFormats#405]
### Setup

- MW version: 1.31
- DB: 10.1.34-MariaDB
- PHP version: 7.2.7
- SMW version: 2.5.7

### Issue
mediawiki/maps package requires "data-values/geo: **~4.0|~3.0**" and "mediawiki/semantic-result-formats" requires "data-values/geo: **~2.0**", and it causes conflict on composer installation. 

**Observed result:** ...
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove data-values/geo 2.1.2
    - Conclusion: remove mediawiki/semantic-result-formats 2.5.5
    - Conclusion: don't install data-values/geo 4.0.1
    - Conclusion: don't install data-values/geo 2.1.2
    - Conclusion: don't install data-values/geo 4.0.0
    - Installation request for mediawiki/semantic-result-formats ~2.5.5 -> satisfiable by mediawiki/semantic-result-formats[2.5.5].
    - Installation request for mediawiki/maps ~5.6.0 -> satisfiable by mediawiki/maps[5.6.0].
    - mediawiki/semantic-result-formats 2.5.5 requires data-values/geo ~2.0 -> satisfiable by data-values/geo[2.1.2, 2.0.0, 2.0.1, 2.1.0, 2.1.1].
    - Can only install one of: data-values/geo[3.0.0, 2.0.0].
    - Can only install one of: data-values/geo[3.0.0, 2.0.1].
    - Can only install one of: data-values/geo[3.0.0, 2.1.0].
    - Can only install one of: data-values/geo[3.0.0, 2.1.1].
    - mediawiki/maps 5.6.0 requires data-values/geo ~4.0|~3.0 -> satisfiable by data-values/geo[3.0.0, 3.0.1, 4.0.0, 4.0.1].
    - Conclusion: don't install data-values/geo 3.0.1

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
```
how to fix this problem?
thanks.

**Comment by kghbln** [comment]
Thanks a lot for reporting this issue. I cannot tell when Maps started to drop "data-values/geo" 2.x but your best immediate shot is to revert to a version of Maps which still does allow this. 

Ad hoc I cannot tell why SRF requires "data-values/geo", it is probably the "filtered" format which has a maps view if I am not mistaken. 

Perhaps it is just a matter of also allowing version 3.x and 4.x "data-values/geo" buy adding it to "composer.json". Still a release will have to be made to get the change out to the public. For this I'd like to also see the current security issue being fixed (https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/391).

@JeroenDeDauw @s7eph4n FYI

**Comment by mwjames** [comment]
> - PHP version: 7.2.7
>     - mediawiki/maps 5.6.0 requires data-values/geo ~4.0|~3.0 -> satisfiable
> by data-values/geo[3.0.0, 3.0.1, 4.0.0, 4.0.1].

So, I'm guessing because of PHP 7.2, Maps has a strict compatibility
to the data-values/geo component.

>     - mediawiki/semantic-result-formats 2.5.5 requires data-values/geo ~2.0
> -> satisfiable by data-values/geo[2.1.2, 2.0.0, 2.0.1, 2.1.0, 2.1.1].

@JeroenDeDauw ?

Btw, SRF 2.5+ (or for that matter SRF 3.0.0-alpha) are not testes
against PHP 7.2.

> - MW version: 1.31

SRF 2.5+ (or for that matter SRF 3.0.0-alpha) are not tested against MW 1.31.

**Comment by kghbln** [comment]
> So, I'm guessing because of PHP 7.2, Maps has a strict compatibility to the data-values/geo component.

This most probably answers it. Since I am running current "stable" of Debian the issue does not pop up at my end, e.g. Ubuntu people my however do.

**Comment by mwjames** [comment]
@kghbln Adding `|~3.0` to the composer.json requirements section should resolve the situation. Not sure about the impact (`data-values/geo` 2.0 vs. 3.0) though!

**Comment by s7eph4n** [comment]
In any case, it is indeed connected to the filtered format.

**Comment by JeroenDeDauw** [comment]
This repo seems to just be using `use DataValues\Geo\Parsers\GeoCoordinateParser;`. Which means it is compatible with 3.x and 4.x as well.

**Comment by JeroenDeDauw** [comment]
Change in https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/410

**Comment by JeroenDeDauw** [comment]
Fixed

**Comment by JeroenDeDauw** [comment]
Though we do still need a release with the fix

**Comment by kghbln** [comment]
>  Though we do still need a release with the fix

I can do this but I'd love to see https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/391 being fixed first, if possible.

**Comment by JeroenDeDauw** [comment]
That is not a regression so I disagree with it needing to be fixed before a release is made

**Comment by kghbln** [comment]
> That is not a regression so I disagree with it needing to be fixed before a release is made

I figured that a security issue needs to be fixed anyways. However, I am fine with doing a release and will try to do the 2.5.6 release this week end or during the next week depending how fast I get to it.
