### ISSUE TITLE
Exhibit: Use of "addOnloadHook" is deprecated. Use jQuery instead. 

### ISSUE THREAD

**Issue by ckoerner** [SemanticMediaWiki/SemanticResultFormats#41]
Chrome is throwing a warning in the console. Searching through my install and the only instance of "addOnloadHook" I can find is in SRF. I could very well be wrong here, but it appears to be coming from line #122 of SRF_Exhibit.js

https://www.mediawiki.org/wiki/ResourceLoader/JavaScript_Deprecations#wikibits.js

MW 1.24wmf4, SMW 1.9.2 and SRF 1.9.1

**Comment by kghbln** [comment]
The [result printer filtered](http://semantic-mediawiki.org/wiki/Help:Filtered_format) is meant to replace this format. Since this was already tagged as "wontfix" I am closing this issue. This does not mean that somebody may show up in the future to revive the format somehow.
