### ISSUE TITLE
Gallery format: Image dimensions exposed as caption

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#433]
### Setup and configuration

- SMW version: 3.0.0-rc.1
- MW version: 1.31.1 
- PHP version: 7.0.32
- MySQL version: 5.7.23

### Issue

The following query also prints the dimensions of the image as part of the caption:
```
{{#ask:
 [[Has title::{{PAGENAME}}]]
 |?Has note
 |captionproperty=Has Note
 |format=gallery
 |widths=400
 |heights=400
}}
```
See this page on [sandbox](https://sandbox.semantic-mediawiki.org/wiki/MEMOIRE_D%27AMOUR_PERDU). The same thing is happening on [s-mw.o main page](https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki) for the showcases.

![grafik](https://user-images.githubusercontent.com/1104078/45953581-cf01ae80-c00a-11e8-9863-b26593d87306.png)

**Comment by mwjames** [comment]
Same as #375.

**Comment by kghbln** [comment]
> Same as #375.

Ah, ok. Thanks for the pointer. I will try to do a pull with the proposed code changes.
