### ISSUE TITLE
Eventcalendar format: week and day view headers display day of week instead of day of month

### ISSUE THREAD

**Issue by krisfield** [SemanticMediaWiki/SemanticResultFormats#446]
### Setup

- MW version: 1.31.1
- DB (MySQL etc.): 
- PHP version: 7.0.32  (apache2handler)
- SMW version: 3.0.0
- SRF version:
- Browsers and versions (if applicable): Chrome 69.9.3497.100

### Issue

When viewing event calendar in week or day views the headers show dates with day of the week instead of day of the month

Monday 1/10, Tuesday 2/10, Wednesday 3/10

vs

Monday 10/15, Tuesday 10/16, Wednesday 10/17

**Steps to reproduce**

Create SMW query with eventCalendar display format and view "Week" and "Day" views

**Expected result:** 
Monday 10/15, Tuesday 10/16, Wednesday 10/17, Thursday 10/18, Friday 10/19, Saturday 10/20, Sunday 10/21

**Observed result:** ..
Monday 1/10, Tuesday 2/10, Wednesday 3/10, Thursday 4/10, Friday 5/10, Saturday 6/10, Sunday 0/10

**Comment by kghbln** [comment]
I am not absolutely sure but I think this is possible by changing some system message. Anyways it indeed makes sense to have this behaviour rather than the current one.

**Comment by krisfield** [comment]
Ah you're right, `MediaWiki:Srf-ui-eventcalendar-format-column-day` defines the format as `dddd d/M` should probably be `dddd D/M` instead.

I also find it interesting that this is the system message that effects both the day view and week view. There is another system message `srf-ui-eventcalendar-format-column-week` which I presumed would define the week view header but changing the format of that page appears to have no effect on the eventCalendar format at all.

Same can be said for the title system messages
"srf-ui-eventcalendar-format-title-week": "D MMM YYYY", - this appears to have no impact on the format
"srf-ui-eventcalendar-format-title-day": "dddd, D MMM, YYYY", - this defines both the week and day view

I think this may be a bug or maybe I am misunderstanding the intent of the `format-column-week` and `format-title-day` formats.

**Comment by kghbln** [comment]
Thanks a lot for having a closer look at this. Great that I remembered correctly. I guess the last time I looked at this was about five or six years ago. Anyways it looks like 1. the mapping of the system messages to the correct spot is somehow broken and 2. the default may be improved. So this a bug.

**Comment by kghbln** [comment]
`format-title-day` does not really work if one adds "dddd", "ddd" etc. The underlying upstream lib does some strange things here. Thus is should be `srf-ui-eventcalendar-format-title-day`: "D MMM, YYYY" for best experience.

`format-column-week` on the other hand needs to be completed with "dddd", "ddd" etc. for best experience. I think the content of both system messages needs to be swapped.

**Comment by mwjames** [comment]
> format-column-week on the other hand needs to be completed with "dddd"

Here is the part where we map to the fullCalendar and it best to refer to the fullCalendar documentation about which keys are usable in the corresponding field. 

https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/2173f1aeb6befd7b778c7ad8b474cc9d117c0ea6/formats/calendar/resources/ext.srf.formats.eventcalendar.js#L384-L426
