### ISSUE TITLE
PHP Fatal error: Uncaught UnexpectedValueException: callback 'SemanticResultFormats::initExtension' is not callable in includes/registration/ExtensionRegistry.php:360

### ISSUE THREAD

**Issue by Wikinaut** [SemanticMediaWiki/SemanticResultFormats#452]
### Setup

- MW version: 1.31.1
- DB (MySQL etc.): MySQL
- PHP version: 7.2.10
- SMW version: 3.0
- SRF version: 3.0.0 and current github
- Browsers and versions (if applicable): n/r

### Issue

MediaWiki broken.

PHP Fatal error:  Uncaught UnexpectedValueException: callback 'SemanticResultFormats::initExtension' is not callable in includes/registration/ExtensionRegistry.php:360

Stack trace:
#0 includes/registration/ExtensionRegistry.php(159): ExtensionRegistry->exportExtractedData(Array)
#1 includes/Setup.php(116): ExtensionRegistry->loadFromQueue()
#2 maintenance/doMaintenance.php(81): require_once('/var/www/events...')
#3 extensions/SemanticMediaWiki/maintenance/rebuildData.php(225): require_once('/var/www/events...')
#4 {main}
  thrown in includes/registration/ExtensionRegistry.php on line 360

We (CCC) need this urgently fixed, any help is welcome.

**Comment by Wikinaut** [comment]
Solved/invalid.

The extension appears not to suited for being included with
wfLoadExtension();

```
# SemanticResultFormats
require_once( "$IP/extensions/SemanticResultFormats/SemanticResultFormats.php" );
# DOES NOT WORK: wfLoadExtension( 'SemanticResultFormats' );
```

**Comment by kghbln** [comment]
This is awkward. I am under the impression that you are using a much older version of SRF (1.8 an probably older). The latest release needs to be invoked with `wfLoadExtension( 'SemanticResultFormats' );` That's at least the only way that works for me with SRF 3.0

**Comment by Wikinaut** [comment]
Hmm, the friends have rearranged the extensions, and the reported problem is apparently gone.
We are now using wfLoadExtension( 'SemanticResultFormats' ); again.
