### ISSUE TITLE
Eventcalendar format: week and day view headers display no longer render correctly

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#469]
### Setup

- MediaWiki | 1.32.1 (66c3c50)22:10, 14. Feb. 2019
- PHP | 7.0.33-0+deb9u1 (apache2handler)
- MariaDB | 10.1.37-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.1.0-alpha (84cdf5d) 08:11, 18. Feb. 2019
- Semantic Result Formats | 3.1.0-alpha (c0e2efa) 23:50, 30. Jan. 2019

### Issue

Something like this is shown for the week view: "Montag, 1. Aug. yyyy – Sonntag, 0. Sep. yyyy" and something like this is shown for the day view: "Sonntag, 0. Sep. yyyy – yyyy".

See the [test page](https://sandbox.semantic-mediawiki.org/wiki/Eventcalendar) on MW 1.32.x. The [demo page](https://www.semantic-mediawiki.org/wiki/Demo:Event_calendar) on MW 1.31.x is still working.

I guess this is caused by MediaWiki now using remex.

**Comment by s7eph4n** [comment]
Are you sure that this is new?
Because this is what I see on smw.org:
![image](https://user-images.githubusercontent.com/2829850/53153980-e8a72200-35b9-11e9-84da-7ebe144687aa.png)
Compare the dates on top and in the day headings. It seems that the headings always show 'day of week' instead of 'day of month'.

**Comment by mwjames** [comment]
> Something like this is shown for the week view: "Montag, 1. Aug. yyyy –
> Sonntag, 0. Sep. yyyy" and something like this is shown for the day view:
> "Sonntag, 0. Sep. yyyy – yyyy".

Please compare the message keys that declare the formatting with
`en.json` (using YYYY) while `de.json` (somehow uses yyyy).

Have a look at the fullcalendar [0] docs as well.

[0] https://fullcalendar.io/docs/titleFormat

Cheers

**Comment by mwjames** [comment]
> It seems that the headings always show 'day of week' instead of 'day of month'.

Probably related to #446 which is a matter of using d vs. D. The
fullCalendar docs should provide examples for it and my guess is that
the message key is likely to contain the "wrong" letter.

Cheers

**Comment by kghbln** [comment]
I remember that initially the results in German were completely broken and that I fixed this years ago. Now back to broken again. In recent versions of MW, SMW and SRF something must have changed. I will go through this.

I saw #446 but I figured this must be different.

**Comment by mwjames** [comment]
> I remember that initially the results in German were completely broken and
> that I fixed this years ago. Now back to broken again. In recent versions of
> MW, SMW and SRF something must have changed. I will go through this.
>

FullCalendar (hereby EventCalendar) changed its date formatting
library (see the docs [0, 1, 2]) and how it uses those short letters
as formatting device.

So, for all formatting related issues in regards to date/time it is
best to consult the FullCalendar docs.

[0] https://fullcalendar.io/docs/date-library
[1] https://fullcalendar.io/docs/date-formatting-string
[2] https://github.com/fullcalendar/fullcalendar/issues/3961

**Comment by kghbln** [comment]
Thank for the info. I moreover found [3] very useful. I am however still struggling how the title messages are constructed for the first part of the range. I thought "Srf-ui-eventcalendar-format-column-week" is used but the results do not support this. Using uselang=qqx does not work either because unidentifiably strings are being rendered instead of the message key.

I a week spans from one month to the next I get "Montag, 27. März – Sonntag, 2. April 2017" which is correct.

I a week spans within a month I get "Montag, 3 – Sonntag, 9. April 2017" which is incorrect since the dot after 3 is omitted.

I am clueless from which message the part n front of the dash is being used.

Anyways the situation is now better after pocking, meaning we got away from unidentifiable dates dates which can at least be recognized.

[3] http://momentjs.com/docs/#/displaying/format/

**Comment by kghbln** [comment]
This is obviously a dupe of #446 which I did not take as serious as I should have.

**Comment by kghbln** [comment]
Ok, I figured it out. Somehow the lib does not cater for all combinations and add, bzw. removes dots etc. on its own. Now German i18n is fixed.
