### ISSUE TITLE
Datatables: boolean properties ignore formatting

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticResultFormats#482]
### Setup

MediaWiki | 1.32.1 (7908476)26 mars 2019 à 04:26
PHP | 7.0.33-0+deb9u3 (apache2handler)
Semantic MediaWiki | 3.1.0-alpha (426a780) 25 mars 2019 à 19:05
Semantic Result Formats | 3.1.0-alpha (3d5e563) 25 mars 2019 à 19:05

### Issue

A property of type boolean displays "t" "f" (true/false) even if you set display options such as #ja,nein

**Steps to reproduce**

https://sandbox.semantic-mediawiki.org/wiki/Issue/1580

**Comment by kghbln** [comment]
Thanks for reporting.

**Comment by kghbln** [comment]
I moved the [example](https://sandbox.semantic-mediawiki.org/wiki/Issue/SRF/482) to another spot since mixing two issues it not the best of ideas.

**Comment by krabina** [comment]
This is a duplicate of #30 as I believe it does not have anything to do with the boolean datatype, but the # printout options

**Comment by thomas-topway-it** [comment]
@see following comment https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/30#issuecomment-1453243208
