### ISSUE TITLE
Datatables format: setting |?property= <blank> results into "-"

### ISSUE THREAD

**Issue by squirrelslair** [SemanticMediaWiki/SemanticResultFormats#486]
### Setup and configuration

- SMW version: 3.0.2
- MW version: 1.32.0
- PHP version: 7.2.11
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.7.25-log
- Results Formats: 3.0.1

### Issue
I have a query that runs fine when I leave a requested property alone, but that lists only "-"s when I try to set the property header to blank by adding a "=" to the end. 
See https://wiki.umintmed.ca/index.php?title=Administrative_Members_of_Department/bugreport 
I don't have a good use case why I would want to do this, I just noticed it as I was changing between formats, and I doubt it's intended behaviour.

### Steps to reproduce
I tried to make a page in the sandbox to reproduce but only get the endless "..." display that I get for most results formats stuff in sandbox. In any case, page is 
https://sandbox.semantic-mediawiki.org/wiki/Bug_example_blank_property_datatables

**Comment by kghbln** [comment]
Thanks for reporting. I guess this is similar to https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/188

**Comment by kuality** [comment]
You may well be right, I don't know enough about the implementation of this to even guess. I would not have found if by any search I could think of based on the problem I reported. So, thanks for linking them, Karsten!


-------- Original message --------

**Comment by krabina** [comment]
Can you please try with the new datatables version?
Please reopen should the problem still exist.
