### ISSUE TITLE
Tests are failing due to "Call to private method ..."

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#493]
### Setup

Multiple setups.

### Issue

[Tests fail](https://travis-ci.org/SemanticMediaWiki/SemanticResultFormats/jobs/533737613) with for following errors, i.e. either calls to private method `SMWWikiPageValue::getSortKey()` or `SMWWikiPageValue::getTitle()`:

- Error: Call to private method `SMWWikiPageValue::getSortKey()` from context 'SRF\Filtered\ResultItem' 2x
- Error: Call to private method `SMWWikiPageValue::getTitle()` from context 'SRF\Gallery'
- Error: Call to private method `SMWWikiPageValue::getTitle()` from context 'SRF\iCalendar\iCalendarFileExportPrinter'
- Error: Call to private method `SMWWikiPageValue::getTitle()` from context 'SRF\iCalendar\iCalendarFileExportPrinter' 2x
- Error: Call to private method `SMWWikiPageValue::getTitle()` from context 'SRF\TagCloud'
- Error: Call to private method `SMWWikiPageValue::getTitle()` from context 'SRFTimeline'

**Comment by kghbln** [comment]
@mwjames @s7eph4n Was not really sure how to report this best.

**Comment by mwjames** [comment]
This relates to
https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3995
because accessing the `getTitle` from a value should be avoided since
it refers to the dataItem.

> `SMWWikiPageValue::getSortKey()`

Has been deprecated since SMW 1.7 and was just a shortcut for:

```
return ApplicationFactory::getInstance()->getStore()->getWikiPageSortKey(
$this->m_dataitem );
```

**Comment by kghbln** [comment]
Something that can be done about this? ;)

**Comment by mwjames** [comment]
> Something that can be done about this? ;)

See https://github.com/JeroenDeDauw/Maps/pull/547
