### ISSUE TITLE
Graph format: add arrowhead and arrowtail parameters

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticResultFormats#505]
Following up on PR https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/297. References tracking issue #503.

**arrowhead**
SRF Graph shall provide the user with the ability to specify an "arrowhead" parameter according to arrowheads provided by Graphviz (see https://www.graphviz.org/doc/info/attrs.html#d:arrowhead and https://www.graphviz.org/doc/info/attrs.html#k:arrowType).

If the user has specified an invalid arrowhead parameter (unknown in Graphviz), SRF Graph shall default to arrowhead "normal".

Implement tests for:
* no arrowhead parameter has been specified
* invalid arrowhead (unknown in Graphviz) has been specified

**arrowtail**
SRF Graph shall provide the user with the ability to specify an "arrowtail" parameter according to arrowtails provided by Graphviz (see https://www.graphviz.org/doc/info/attrs.html#d:arrowtail and https://www.graphviz.org/doc/info/attrs.html#k:arrowType).

If the user has specified an invalid arrowtail parameter (unknown in Graphviz), SRF Graph shall default to arrowhead "none".

Implement tests for:
* no arrowtail parameter has been specified
* invalid arrowtail (unknown in Graphviz) has been specified

gesinn.it team will work on this

**Comment by alex-mashin** [comment]
The parameter is already there.

**Comment by JeroenDeDauw** [comment]
@gesinn-it-gea just say so if we need to reopen the issue
