### ISSUE TITLE
SRF 3.1.0 release

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticResultFormats#512]
### Release boundaries 

MW 1.31 - 1.33
PHP 7.0 - 7.3
SMW 3+

For discussion points see:
- https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/507#issuecomment-515680500
- https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/507#issuecomment-515681201
- https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/507#issuecomment-515687417

**Comment by kghbln** [comment]
All that is missing is the announce e-mail.

**Comment by JeroenDeDauw** [comment]
I'll announce the new releases soon
