### ISSUE TITLE
Graph format: unclear "nameproperty" parameter 

### ISSUE THREAD

**Issue by RacoonDev** [SemanticMediaWiki/SemanticResultFormats#533]
As I'm working on refactoring the "graph" format [0] I came across the parameter "nameproperty" that got lost as result of this PR. 
So I took an older commited version of SRF [1] where this parameter still exists and should work like expected [2].  

I made 2 different ask queries with and without the "nameproperty"-paramter.

1. without "nameproperty"

```
{{#ask:[[Category:Team]]
  |?Casted
  |?Part Of Team
  |format=graph
  |graphname=test
  |graphlegend=yes
  |graphlabel=yes
  |graphlink=yes
  |graphcolor=yes
}}
```
Result:
![SRF graph](https://user-images.githubusercontent.com/25004352/63589966-cfa01d80-c5aa-11e9-8a0b-9147ad9e278d.png)
:

2. using "nameproperty":
```
{{#ask:[[Category:Team]]
  |?Casted
  |?Part Of Team
  |format=graph
  |graphname=test
  |graphlegend=yes
  |graphlabel=yes
  |graphlink=yes
  |graphcolor=yes
  |nameproperty=Casted
}}
```
Result:
![SRF graph_nameproperty](https://user-images.githubusercontent.com/25004352/63590156-57862780-c5ab-11e9-972c-0382470b2c8a.png)

It's not clear to me if this property does what it should. 

[0]https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/507
[1] https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/98e0aec50fdb56ba86f1c4886cc37edec0e6602b
[2] https://www.semantic-mediawiki.org/wiki/Help:Graph_format

**Comment by mwjames** [comment]
According to [0], `nameproperty` is suppose to "Sets the property that
will be used as subject instead of the actual subject, i.e. page name"
and the code [1] is actively replacing the `$name` in case the
printrequest label (selected property) matches the used
`nameproperty`.


```
				$isName = $this->m_nameProperty ? ( $i != 0 &&
$this->m_nameProperty === $propName ) : $i == 0;
				if ( $isName ) {
					$name = $this->getWordWrappedText( $object->getShortText(
$outputmode ), $this->m_wordWrapLimit );
				}

```
...
```
			$graphInput .= $this->m_parentRelation ? " \"$text\" -> \"$name\" "
: " \"$name\" -> \"$text\" ";
```

So, the code alters the behaviour of the what is contained in
`m_parentRelation` but I'm not clear on what the intention is or the
use case for doing so.


[0] https://www.semantic-mediawiki.org/wiki/Help:Graph_format
[1] https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/98e0aec50fdb56ba86f1c4886cc37edec0e6602b/formats/graphviz/SRF_Graph.php

**Comment by RacoonDev** [comment]
> So, the code alters the behaviour of the what is contained in
`m_parentRelation` but I'm not clear on what the intention is or the
use case for doing so.

Yes, exactly for what is that supposed to be used at all?
 @JeroenDeDauw could you have a look at it too. Maybe you see the benefit of this parameter. If we all agree that this parameter is not needed, I can begin with the conversion of the graph format

**Comment by mwjames** [comment]
> this parameter. If we all agree that this parameter is not needed, I can
> begin with the conversion of the graph format

In that event, maybe write a short email to the smw-devel mailing-l
and announce that you are in the middle of a refactoring and you are
planning to remove the `nameproperty` as parameter due to its unclear
intention or missing use case.
