### ISSUE TITLE
Graph format: Undefined variable: nodeLabel 

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#556]
### Setup
- MediaWiki | 1.34.0-rc.1 (ccb2bb2)19:12, 18 November 2019
- PHP | 7.2.24-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.41-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0-alpha (aef1b47) 18:20, 18 November 2019
- Semantic Result Formats | 3.2.0-alpha (bcef869) 17:02, 11 November 2019
- GraphViz | 3.0.0 (7099bd9) 09:42, 7 November 2019

### Issue
When rebuilding the semantic data on sandbox with "rebuildData.php" I am being polluted with the following PHP notices over and over and over ...

```
PHP Notice:  Undefined variable: nodeLabel in /../w/extensions/SemanticResultFormats/src/Graph/GraphFormatter.php on line 109

Notice: Undefined variable: nodeLabel in /../w/extensions/SemanticResultFormats/src/Graph/GraphFormatter.php on line 109
PHP Notice:  Undefined variable: nodeLabel in /../w/extensions/SemanticResultFormats/src/Graph/GraphFormatter.php on line 112

Notice: Undefined variable: nodeLabel in /../w/extensions/SemanticResultFormats/src/Graph/GraphFormatter.php on line 112
```

**Comment by gesinn-it** [comment]
@SbstnS can you please have a look at this
