### ISSUE TITLE
Jqplotseries format: Hide zero value labels in bar plot

### ISSUE THREAD

**Issue by darenwelsh** [SemanticMediaWiki/SemanticResultFormats#558]
How can a user configure a jqplotseries bar chart to not display labels for zero values?

**Comment by kghbln** [comment]
Also posted [to the mailing list](https://sourceforge.net/p/semediawiki/mailman/semediawiki-user/thread/CAGvQzja%2ByPtmRLyGXGfFYcsuOkyPQodP8cxzYBT%2BfMymRGuJnw%40mail.gmail.com/#msg36869189) Here is [the script](https://github.com/SemanticMediaWiki/SemanticResultFormats/tree/master/formats/jqplot/resources) used to interact with SMW/SRF. From the link to [stackoverfow](https://stackoverflow.com/questions/26385985/removing-zero-value-point-lables-on-a-jqplot-stacked-bar-chart) it appears to me that jqplot needs to be adapted to cater for this.

**Comment by darenwelsh** [comment]
I found https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/resources/jquery/jqplot/jqplot.pointLabels.js#L128 but I can't tell if there's a way to configure hideZeros from the SMW ask query or in LocalSettings.php.

**Comment by JeroenDeDauw** [comment]
Nothing seems to allow modifying the JS value you found. https://github.com/SemanticMediaWiki/SemanticResultFormats/search?q=hideZeros&unscoped_q=hideZeros. Which if correct means you cannot modify it via LocalSettings.php

**Comment by JeroenDeDauw** [comment]
I could add a parameter to the result format to control this. Need a little incentivisation though

**Comment by darenwelsh** [comment]
![tenor](https://user-images.githubusercontent.com/6728676/72439812-3944e200-376d-11ea-8e78-73ad80c4fa68.gif)

**Comment by darenwelsh** [comment]
I imagine there are lots of configurable options for jqplot and it would be great to be able to do so from each ask query using it in a wiki.

In this specific case, I don't see why the default isn't just changed so zero values are not labeled. It doesn't display well as-is. So if just changing that boolean is acceptable I'm happy to do a pull request. I just don't know how to do the fancy way of making it configurable.

**Comment by JeroenDeDauw** [comment]
Just changing the boolean does not work, since it is inside of a third party library. Your change would get lost when we update it.

I've [added a new parameter to the result format](https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/565). Note that I have not tested this due to lack of familiarity with the format, laziness and the lack of [a good way to test this code](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4313). You now owe me a drink at the next conference ;)
