### ISSUE TITLE
Slideshow format is broken

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticResultFormats#56]
I don't know why, but the slideshow format is broken:
http://wikincat.org/wiki/User:Jaider/Página_de_testes
http://wikincat.org/wiki/User:Jaider/Página_de_testes?action=edit
This query was ok recently.

MediaWiki: 1.23.2 (f22a475)
Semantic MediaWiki: 2.0 RC3 (e17bff2)
Semantic Result Formats: 1.9 (fc1fb9c)

**Comment by kghbln** [comment]
Hmm ... I wonder why this ever worked. I believe you should do 

```text
|format=gallery
|widget=slideshow
```
instead of 

```text
|format=slideshow
```
At least that's who I use it and it works for me.

**Comment by kghbln** [comment]
A sorry, there is acutally a dedicated slideshow format. Disregard my post.

**Comment by kghbln** [comment]
@s7eph4n You were the original author of this. Perhaps you would like to have a peep. Will be cool I believe. :)

**Comment by kghbln** [comment]
Oops, I did not see the reference to the duplicate issue before pinging you. I am sorry for this.

**Comment by mitchelln** [comment]
An example:

Page is here: http://www.prescientsoftware.co.uk/cwi/index.php/Test-SlideShow 

Let me know if you need a login. 

No errors with debugging switched on. If you add the nav controls=yes options you get the slidebar at the bottom, but that's it.

Cheers Neill.

**Comment by s7eph4n** [comment]
@JeroenDeDauw: Is the ParamDefinition class still available in newer versions of SMW?

**Comment by JeroenDeDauw** [comment]
@s7eph4n has not changed for a while https://github.com/JeroenDeDauw/ParamProcessor

Perhaps you have and old ref to the un-namedpaced one?

**Comment by s7eph4n** [comment]
@JeroenDeDauw: Could well be. Would be in line with the error on @jaideraf 's wiki:

`<b>Fatal error</b>:  Class 'ParamDefinition' not found in <b>/home/jaideraf/webapps/wikincat/w/extensions/SemanticResultFormats/formats/slideshow/SRF_SlideShowApi.php</b> on line <b>32</b><br />`

**Comment by JeroenDeDauw** [comment]
#91
