### ISSUE TITLE
Spreadsheet format : filename parameter not taken account

### ISSUE THREAD

**Issue by otisyves** [SemanticMediaWiki/SemanticResultFormats#560]
### Setup
- MW version: 1.31.3 
- DB (MySQL etc.): 5.6.36
- PHP version: 7.3.9
- SMW version: 3.1.1
- SRF version:  3.1.0
- Browsers and versions (if applicable):

### Issue

When providing a filename via the param, it is not taken in account in the resulting actuel filename (always the random generated one).

Small issue but annoying.

**Steps to reproduce**

Look here for examples :
https://wiki.lineaire-ecoconstruction.com/wiki/Test_Spreadsheet

Seems that the filename

**Comment by s7eph4n** [comment]
Probably connected: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4375

**Comment by kghbln** [comment]
> Probably connected: SemanticMediaWiki/SemanticMediaWiki#4375

Affirmative.  Thus closing here.

PS Examples on sandbox: https://sandbox.semantic-mediawiki.org/wiki/Issue/4375.
