### ISSUE TITLE
Listwidget format:  ArgumentCountError from line 74 of "ListResultBuilder.php": Too few arguments to function

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#564]
### Setup

- MediaWiki | 1.34.0 (ae6e0c0)15:53, 27 December 2019
- PHP | 7.2.24-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.43-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0-alpha (da7cf23) 18:02, 6 January 2020
- Semantic Result Formats | 3.2.0-alpha (da9f322) 12:53, 26 December 2019

### Issue

This may very well already come from the list printer.

Error message:
```
ArgumentCountError from line 74 of /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ListResultPrinter/ListResultBuilder.php: Too few arguments to function SMW\Query\ResultPrinters\ListResultPrinter\ListResultBuilder::__construct(), 2 passed in /../w/extensions/SemanticResultFormats/formats/widget/SRF_ListWidget.php on line 44 and exactly 3 expected
```
Query:
```
{{#ask:
 [[Category:Person]]
 |format=listwidget
}}
```
### Backtrace
```
#0 /../w/extensions/SemanticResultFormats/formats/widget/SRF_ListWidget.php(44): SMW\Query\ResultPrinters\ListResultPrinter\ListResultBuilder->__construct(SMW\Query\QueryResult, Linker)
#1 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(337): SRFListWidget->getResultText(SMW\Query\QueryResult, integer)
#2 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(302): SMW\Query\ResultPrinters\ResultPrinter->buildResult(SMW\Query\QueryResult)
#3 /../w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(348): SMW\Query\ResultPrinters\ResultPrinter->getResult(SMW\Query\QueryResult, array, integer)
#4 /../w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(364): SMWQueryProcessor::getResultFromQuery(SMWQuery, array, integer, integer)
#5 /../w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(197): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array, array)
#6 /../w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse(array)
#7 /../w/includes/parser/Parser.php(3816): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string)
#8 /../w/includes/parser/Parser.php(3519): Parser->callParserFunction(PPFrame_Hash, string, array)
#9 /../w/includes/parser/PPFrame_Hash.php(254): Parser->braceSubstitution(array, PPFrame_Hash)
#10 /../w/includes/parser/Parser.php(3330): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#11 /../w/includes/parser/Parser.php(1489): Parser->replaceVariables(string)
#12 /../w/includes/parser/Parser.php(593): Parser->internalParse(string)
#13 /../w/includes/content/WikitextContent.php(368): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#14 /../w/includes/content/AbstractContent.php(555): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#15 /../w/includes/Revision/RenderedRevision.php(267): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#16 /../w/includes/Revision/RenderedRevision.php(236): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#17 /../w/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string)
#18 /../w/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#19 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#20 /../w/includes/Revision/RenderedRevision.php(198): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#21 /../w/includes/poolcounter/PoolWorkArticleView.php(196): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#22 /../w/includes/poolcounter/PoolCounterWork.php(125): PoolWorkArticleView->doWork()
#23 /../w/includes/page/Article.php(791): PoolCounterWork->execute()
#24 /../w/includes/page/CategoryPage.php(66): Article->view()
#25 /../w/includes/actions/ViewAction.php(63): CategoryPage->view()
#26 /../w/includes/MediaWiki.php(511): ViewAction->show()
#27 /../w/includes/MediaWiki.php(302): MediaWiki->performAction(CategoryTreeCategoryPage, Title)
#28 /../w/includes/MediaWiki.php(900): MediaWiki->performRequest()
#29 /../w/includes/MediaWiki.php(527): MediaWiki->main()
#30 /../w/index.php(44): MediaWiki->run()
#31 {main}
```

### Example

See [sandbox.](https://sandbox.semantic-mediawiki.org/wiki/Issue/SRF/564)

**Comment by mwjames** [comment]
See [0] for clarification on `ArgumentCountError`.

> #0 /../w/extensions/SemanticResultFormats/formats/widget/SRF_ListWidget.php(44): SMW\Query\ResultPrinters\ListResultPrinter\ListResultBuilder->__construct(SMW\Query\QueryResult, Linker)
#1 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(337): SRFListWidget->getResultText(SMW\Query\QueryResult, integer)

I suspect https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/6453652b3392cef69d621e13bac4a76a5fc16b2f to be the cause given that it touched `ListResultBuilder.php`. (see https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4383)

[0] https://www.php.net/manual/en/class.argumentcounterror.php.

**Comment by kghbln** [comment]
Meh, one fixed one killed. Apparently this replicating slave nonsense gives me the creeps.

@JeroenDeDauw FYI

**Comment by kghbln** [comment]
omg, after the recent update of the code on sandbox the issue went away.

**Comment by kghbln** [comment]
I now go this on

- MediaWiki | 1.31.6 (0441c81)14:24, 19. Dez. 2019
- PHP | 7.2.24-0ubuntu0.18.04.2 (apache2handler)
- MariaDB | 10.1.43-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.1.2 (e00b175) 09:42, 12. Jan. 2020
- Semantic Result Formats | 3.1.0 (aa0649f) 18:55, 18. Aug. 2019

I hope that this is restricted to 3.1.x I will reopen and check as soon as the new versions 3.2.0 are published.

**Comment by JeroenDeDauw** [comment]
This is an SMW 3.1.2 issue, present only in that patch release. It is because that patch release contains the list format changes but not https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4383/commits/540e492d489c8bde262015ccf025e5ac213eea27.

I recall backporting it onto 3.1.x branch last week or so but am not seeing it there now. Weird.

**Comment by JeroenDeDauw** [comment]
Apparently I linked the wrong SRF issue in that commit, which explains why it did not end up in 3.1.2.

**Comment by kghbln** [comment]
> Apparently I linked the wrong SRF issue in that commit, which explains why it did not end up in 3.1.2.

Ok, this explains it.. I was wondering what the pull had to do with this ill fated database issue but in the end I am not a code bunny. Anyways, I flag this for back-porting to SMW 3.1.3

**Comment by JeroenDeDauw** [comment]
Ah, my backport did not dissapear. It just did not get merged yet: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4427

**Comment by kghbln** [comment]
Now I am completely confused. I just back-ported the other commit referenced before (https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/540e492d489c8bde262015ccf025e5ac213eea27). This one is an new and second one which is failing it tests.
