### ISSUE TITLE
Problem with instalation Semantic Result Formats

### ISSUE THREAD

**Issue by zhuravlevasn** [SemanticMediaWiki/SemanticResultFormats#569]
### Setup

MediaWiki 	1.32.1
PHP 		7.3.5 (apache2handler)
MariaDB 	10.1.40-MariaDB

Semantic MediaWiki	2.3.1	
Page Forms		4.5.1
ParserHooks		1.4.0
Validator		2.0.4

### Problem

I tried setup extension Semantic Result Formats (v. 2.4.2). I have unzipped the archive into the \extension-directory and have written into LocalSetting.php:
require_once( "$IP/extensions/SemanticResultFormats/SemanticResultFormats.php" );
(I can't use Composer, because I haven,t Internet on my machine).
 When I started my Wiki I seen the following error:

Error:
[8975bbc6ba5eaffb3b925e63] /wiki/mediawiki-1.32.1/index.php/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0 MWException from line 164 of C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\Hooks.php: Invalid callback SRFParserFunctions::registerFunctions in hooks for ParserFirstCallInit

Backtrace:

#0 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#1 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\parser\Parser.php(369): Hooks::run(string, array)
#2 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\StubObject.php(112): Parser->firstCallInit()
#3 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\StubObject.php(138): StubObject->_call(string, array)
#4 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\cache\MessageCache.php(1190): StubObject->__call(string, array)
#5 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\cache\MessageCache.php(1166): MessageCache->getParser()
#6 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\Message.php(1282): MessageCache->transform(string, boolean, Language, Title)
#7 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\Message.php(883): Message->transformText(string)
#8 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\Message.php(943): Message->toString(string)
#9 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\OutputPage.php(924): Message->text()
#10 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\OutputPage.php(971): OutputPage->setHTMLTitle(Message)
#11 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\page\Article.php(622): OutputPage->setPageTitle(string)
#12 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\actions\ViewAction.php(68): Article->view()
#13 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\MediaWiki.php(501): ViewAction->show()
#14 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\MediaWiki.php(294): MediaWiki->performAction(Article, Title)
#15 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\MediaWiki.php(860): MediaWiki->performRequest()
#16 C:\xampp\htdocs\wiki\mediawiki-1.32.1\includes\MediaWiki.php(517): MediaWiki->main()
#17 C:\xampp\htdocs\wiki\mediawiki-1.32.1\index.php(42): MediaWiki->run()
#18 {main}

What is the problem? Can you help me?

**Comment by kghbln** [comment]
Thanks for asking. SRF 2.4.2 is not compatible with MediaWiki 1.32.x. Anyhow, you best shot will be an [individual file release](https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/docs/COMPATIBILITY.md#platform-compatibility). Since the software you are using is a bit dated I suggest to updated all of it anyways.
