### ISSUE TITLE
Mermaid 2.2.0 now requires MW 1.33+

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticResultFormats#570]
### Setup

- MW version: 1.31.6
- SRF 3.1.0

### Issue

Since v2.2.0, Mermaid requires MW 1.33+. Mermaid is installed by SRF via composer:

```
"mediawiki/mermaid": "~2.1"
```
which installs latest v2.2.0 of Mermaid, thus making SRF 3.1.0 incompatible with MW 1.31.

**Expected result:**
 A minor update of Mermaid should not require a "major" update of MW.

**Comment by JeroenDeDauw** [comment]
This is caused by Mermaid not defining what MW versions it is compatible with. Normally Composer would not install a more recent version of a package if it is incompatible with your system.

SRF could pin down the Mermaid version more but this comes with its own issues. So I think this is a Mermaid issue, not an SRF one.

**Comment by akuckartz** [comment]
In any case it is an issue (also) for the SMW community.

**Comment by gesinn-it** [comment]
Well, I'd say it's also an MW issue with MW not really following SemVer. MW's minor updates are indeed major updates. However, I think SRF should in this case pin Mermaid to 2.1.0. Also it would be ideal to have a SRF patch release soon. @kghbln what do you think?

**Comment by kghbln** [comment]
That's what I meant. I is up to us bloody admins to take care of this now. I waited months for help on the respective issue with Mermaid. Nothing. Anyways add 2.1.0 to you composer.local.json to adapt.

**Comment by gesinn-it** [comment]
@kghbln I'm not sure I understand your feedback. Of course I know how to technically solve it. I just wanted to avoid a "patch" and others having the same issue when trying to install on MW 1.31.

**Comment by kghbln** [comment]
Whatever. We should remove mermaid from required to suggest if at all.

**Comment by JeroenDeDauw** [comment]
> Whatever. We should remove mermaid from required to suggest if at all.

Good idea. Not perfect all round but I like this as a low effort pragmatic solution for now.

**Comment by gesinn-it** [comment]
I had a look at the Mermaid commits but do not see a reason, why Mermaid itself technically requires MW 1.33 now. Did I miss something? MW 1.33 requirement was indroduced https://github.com/SemanticMediaWiki/Mermaid/commit/9e4859bd655b35572a1a68a882692032eebb2e86 probably cause by removing "mediawiki.api.parse" in https://github.com/SemanticMediaWiki/Mermaid/commit/d24b4510486554c9e44cc4e78a58889cc2c25f1e

See also comments in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3626#issuecomment-524620879

**Comment by gesinn-it** [comment]
I think removing Mermaid as a requirement makes sense as for integrators it would be easier to add a (pinned) version that fit's their needs. Loose coupling of components so to say...

**Comment by JeroenDeDauw** [comment]
PR welcome!

**Comment by mwjames** [comment]
> A minor update of Mermaid should not require a "major" update of MW.
> @kghbln I'm not sure I understand your feedback. Of course I know how to technically solve it. I just wanted to avoid a "patch" and others having the same issue when trying to install on MW 1.31.

I think @kghbln did his best effort to make a Mermaid release happen while anyone else was sitting on the sideline waiting for something to happen. Now, if there is something to fix please do so by proposing a PR and not ranting about changes that were necessary due to some MW related issues.

**Comment by kghbln** [comment]
After this pull SRF still requires Mermaid 2.1 Not sure where this comes from. Anyhow this MediaWiki disaster continues.

**Comment by akuckartz** [comment]
@kghbln Are these problems caused by MediaWiki or Mermaid?

**Comment by kghbln** [comment]
MediaWiki is the root cause of this issue because some developers out there lack commons sense. Mostly the ones who do not run wikis themselves I presume. It is up to us admins to resolve this mess.

**Comment by gesinn-it** [comment]
@kghbln did you mean: if you want to use SRF Gantt with MW 1.31 then you still need to install Mermaid 2.1.0 (not Mermaid 2.2.0+)? That's correct. And yes, you are right, the whole issue was caused by an "unfortunate" change in MW.

Also note that there is another issue with SRF Gantt: #577

**Comment by kghbln** [comment]
Well sorry for the noise. Admittedly I fucked up here by adding the wrong version request to my composer.local.json file. :( Note that we need Mermaid 2.0.0 for SRF 3.1.0.
