### ISSUE TITLE
[Datatables] Value for properties of datatype Quantity are not sorted properly

### ISSUE THREAD

**Issue by osnard** [SemanticMediaWiki/SemanticResultFormats#571]
### Setup

- MW version: 1.34.0
- DB (MySQL etc.): 10.2.12-MariaDB-10.2.12+maria~jessie
- PHP version: 7.2.24-0ubuntu0.18.04.1 (fpm-fcgi)
- SMW version: 3.1.5
- SRF version: 3.1.0

### Issue

When using a `format=datatables` with a query that contains a printout for a property of type "Quantity", the respective column is sorted as string instead of number.

**Steps to reproduce**

(recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org))

1. Create the following pages: 
- "Property:SomeProp": `[[Has type::Quantity]][[Corresponds to::1 €]]`
- "Test_001": `[[SomeProp::150]]`
- "Test_002": `[[SomeProp::200]]`
- "Test_003": `[[SomeProp::1000]]`

2. Create ASK query:
```
{{#ask:[[SomeProp::+]]
|?SomeProp
|format=datatables
}}
```
3. Sort column "SomeProp"

**Expected result:** ...
Order should be: Test_001/150€ - Test_002/200€ - Test_003/1000€

**Observed result:** ...
Order is: Test_003/1000€ - Test_001/150€ - Test_002/200€

**Hints**
The jQuery DataTables widget seems to support currency-sorting. Unfortunately SMW has no concept of that is a currency. It only knows about "Quantity". But maybe columns of type quantity can have a generic sorter that just strips any unit from the value, thus making it a number again

**Comment by kghbln** [comment]
Thanks for reporting. Yeah, support for this would be great.

**Comment by osnard** [comment]
Btw.: it looks like "date" values are also not properly sorted.

**Comment by krabina** [comment]
I cannot confirm this. In our [latest version](https://github.com/Knowledge-Wiki/SemanticResultFormats), both sorting of dates and quantities is working fine.
You can see it here: https://silver.knowledge.wiki/User:Admin/Datatables_test
Both dates and weight are sorting fine. 

Thus I suggest closing this (our PR has been merged with SRF already, the latest open one is only concerning caching).
