### ISSUE TITLE
[Outline] Support introtemplate and outrotemplate parameter

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticResultFormats#578]
### Issue
At the moment, Outline provides a template mechanism, that allows to specify templates for segment header and items.

As a user I'd like to be able to specify an intro and outro template that surrounds the complete Outline's results. This could for example be a container `<div>` tag.

I propose, on the basis of the existing template/plainlist format parameters, to use `introtemplate` and `outrotemplate` as parameter names.

@kghbln @s7eph4n @JeroenDeDauw @mwjames : what do you think?

**Comment by kghbln** [comment]
Sounds good to my since these parameters would behave identically to the ones at plainlist.
