### ISSUE TITLE
[Eventcalendar] Including end date for multi-day events

### ISSUE THREAD

**Issue by mint-thompson** [SemanticMediaWiki/SemanticResultFormats#584]
### Setup

- MW version: 1.32.1
- DB (MySQL etc.): MySQL 5.6.47
- PHP version: 7.2.29
- SMW version: 3.0.1
- SRF version: 3.0.2-alpha (43a8844)
- Browsers and versions (if applicable): Tested in Chrome 80, IE 11, Edge 44

### Issue

When displaying events that span multiple days, the eventcalendar format shows the event on each day that it occurs. However, this can be troublesome when the start and end of the event are stored as dates without times. In this case, a default time of midnight is used, and the end date is not included in the range. For example, a start date of `2020 March 23` and end date of `2020 March 27` will occupy Monday (March 23), Tuesday (March 24), Wednesday (March 25), and Thursday (March 26), but not Friday (March 27).

**Steps to reproduce**

The sandbox is currently refusing to let me confirm my email address, so I can't build a demonstration there. I will edit this issue to include a link to it as soon as that is resolved.

I have a solution ready to go in [my fork](https://github.com/mint-thompson/SemanticResultFormats/tree/calendar-end-date), but I will try to get the demonstration on the sandbox first.

**Comment by kghbln** [comment]
Yeah, handling events and recurring events can indeed require some voodoo. If there is something to improve the cause ...!

**Comment by mint-thompson** [comment]
The sandbox is still insisting that my email is unconfirmed and that I've tried to confirm my email too many times, so I went ahead and created the PR.

**Comment by kghbln** [comment]
Thanks for the pull! I guess it is just a matter of clicking on the link you got via e-mail. Either a typo in the e-mail or deep in your spam filter. The wiki uses Amazon SES so it should be fairly reliable.

**Comment by mwjames** [comment]
> the range. For example, a start date of 2020 March 23 and end date of 2020 March 27 will occupy Monday (March 23), Tuesday (March 24), Wednesday (March 25), and Thursday (March 26), but not Friday (March 27).

@mint-thompson Just to clarify, there isn't any other why to deduce from existing information that the end-date has to be included and requires an extra parameter to come to that conclusion?

**Comment by mint-thompson** [comment]
@mwjames I chose to implement this as an extra parameter in order to avoid changing the behavior of existing queries. To implement this behavior without the additional parameter, I think it would be sufficient to check that the ending date has no specified time. This check `( value.precision & 8 ) == 0` is currently included alongside checking the `includeend` parameter.

My opinion is that the behavior achieved by setting `includeend` to `true` will almost always be the desired behavior. But, I would still like to include the parameter so that in the case that someone _does_ want to maintain current behavior, they can do so without changing any data. In that sense, it may be best to default the parameter to `true`, as suggested by @akuckartz : https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/586#commitcomment-38432284

**Comment by kghbln** [comment]
@mint-thompson Thanks for your effort!
