### ISSUE TITLE
[Outline] Results with format=outline and outlineproperties displays each page only one time

### ISSUE THREAD

**Issue by Seb35** [SemanticMediaWiki/SemanticResultFormats#599]
### Setup

- MW version: 1.34.1
- DB (MySQL etc.): MySQL 5.7
- PHP version: 7.2
- SMW version: 3.1.6
- SRF version: 3.1.0
- Browsers and versions (if applicable): not applicable

### Issue

For the format "outline" with the option "outlineproperties", when a page returned by the query has multiple values for the given property, it is only displayed in the first value.

**Steps to reproduce**

For instance we have the following query:

```
{{#ask:[[Category:Article]]
|?Topic
|format=outline
|outlineproperties=Topic
}}
```

and the page "My wonderful article" contains:

```
[[Topic::My first topic]]
[[Topic::My second topic]]
[[Category:Article]]
```

**Expected result:**

The result of the query should be:

My first topic
- My wonderful article

My second topic
- My wonderful article

**Observed result:**

Currently the result of the query is:

My first topic
- My wonderful article

See [this page on sandbox.smw](https://sandbox.semantic-mediawiki.org/wiki/Query_outline_with_outlineproperties_with_multiple_values).

**Comment by kghbln** [comment]
@Seb35 Thanks for reporting and working on a patch!

**Comment by Seb35** [comment]
This issue occurs also when the parameter `template=` is set, and the fix seems to be similar in the file `src/Outline/TemplateBuilder.php`. I will further check this and propose another PR.
