### ISSUE TITLE
"Showing 0 to 0 of 0 entries" is a rather weird message

### ISSUE THREAD

**Issue by amire80** [SemanticMediaWiki/SemanticResultFormats#60]
I am translating this extension and I ran into the message "srf-ui-datatables-label-sInfoEmpty", which says "Showing 0 to 0 of 0 entries".

Is this really needed? Can't it just be something like "No entries"?

**Comment by s7eph4n** [comment]
Permanent link: https://github.com/DataTables/DataTables/blob/786d79d1/media/js/jquery.dataTables.js#L10923
