### ISSUE TITLE
[iCalendar] Downloading the file with calendar information causes server error

### ISSUE THREAD

**Issue by IRA1777** [SemanticMediaWiki/SemanticResultFormats#612]
For my private wiki as well as for SMW site format example (https://www.semantic-mediawiki.org/wiki/Help:ICalendar_format), clicking the link results in:

> This page isn’t working
> www.semantic-mediawiki.org is currently unable to handle this request.

### Setup

- MW version: 1.31.8 LTS
- DB (MySQL etc.): mysql
- PHP version: 7.0
- SMW version: 3.1.6
- SRF version: 3.1.0
- Browsers and versions (if applicable): Yandex browser 20.8

### Issue
...context and general description...
ICalendar format isn't working.

**Steps to reproduce**

1. go to [https://www.semantic-mediawiki.org/wiki/Help:ICalendar_format]
2. click "Export for iCalendar" in Result section

**Expected result:** 
iCalendar file download

**Observed result:** ...
> This page isn’t working

**Comment by akuckartz** [comment]
> Yandex browser 20.8

@IRA1777 
What happens with other browsers?

**Comment by IRA1777** [comment]
Blank page with firefox @ https://www.semantic-mediawiki.org/wiki/Help:ICalendar_format

**Comment by akuckartz** [comment]
I can confirm seeing a 500 http error when accessing this URL:
https://www.semantic-mediawiki.org/wiki/Special:Ask/-5B-5BCategory:SMWCon-5D-5D-20-5B-5BHas-20conference-20type::SMWCon-5D-5D/-3FHas-20conference%3Dsummary/-3FHas-20planned-20start%3Dstart/-3FHas-20planned-20finish%3Dend/-3FHas-20location%3Dlocation/-3FHas-20description%3Ddescription/mainlabel%3D/limit%3D50/offset%3D0/format%3Dicalendar/searchlabel%3DExport-20for-20iCalendar/title%3DSMWCon/description%3DThe-20dates-20of-20all-20SMWCons.

**Comment by IRA1777** [comment]
Strangely enough, I got the same exact problem (error 500) with another server, but now with spreadsheet format, while iCalendar works!

**Comment by kghbln** [comment]
@IRA1777 Could you try SRF 3.2.0. The previously failing export on [ICalendar format](https://www.semantic-mediawiki.org/wiki/Help:ICalendar_format) works now (I am no Fx). The difference for that wiki was the upgrade of SRF.

**Comment by kghbln** [comment]
Cool. Thanks for reporting back!
