### ISSUE TITLE
[Filtered] Add "list view userparam"

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticResultFormats#629]
Add "list view userparam" to support SMW's `#userparam`

**Comment by gesinn-it** [comment]
@kghbln I'm about to update the docu on smw.org. It makes use of {{#smwdoc:filtered|parameters=specific}}. I'm I right that smwdoc updates automatically with the next release? https://www.semantic-mediawiki.org/wiki/Help:Generating_documentation says nothing about how / when the docu is updated.

**Comment by kghbln** [comment]
Indeed. I just [enhanced the docu](https://www.semantic-mediawiki.org/w/index.php?title=Help:Generating_documentation&diff=80379&oldid=75251)
