### ISSUE TITLE
Format filtered does not show slider at distance filter

### ISSUE THREAD

**Issue by markmuzenhardt** [SemanticMediaWiki/SemanticResultFormats#669]
I have MediaWiki 1.35 installed, SemanticResultFormats 3.2.0 and SemanticMediaWiki 3.2.3. With the following code I have tried to show a filtered table, using the distance filter. But no matter what I change, the silder of the distance filter never shows up.

`{{#ask:[[Geokoordinate::+]] 
|?Geokoordinate=|+filter=distance|+distance filter origin=49.473, 10.985|+distance filter unit=m|+distance filter initial value=200|+distance filter max distance=2000|+hide=no
|format=filtered
|limit=100
|filter position=top
|views=table
}}
`

**Comment by kghbln** [comment]
Thanks for reporting. Probably creating a example on the [sandbox wiki](https://sandbox.semantic-mediawiki.org/wiki/Main_Page) will allow to demonstrate the issue live.

**Comment by markmuzenhardt** [comment]
I did a demonstration on:

[https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Red_Rooster/Sandbox]

it shows exactly what the problem is: You get no slider for the search distance.

I couldn't figure out, what I did wrong. Maybe it's my code, but it could also be a SMW-Bug. I copied my example from wiengeschichtewiki, where it works. But at fuerthwiki and sandbox-wiki it doesn't work.

**Comment by kghbln** [comment]
Thank you for creating the example. I very much suspect that the result format is to blame here. FürthWiki and Sandbox are on MW 1.35.x whereas WienGeschichteWiki is still on MW 1.31.x

@krabina Could you do a sanity check on the code to make sure that it is as required?

**Comment by krabina** [comment]
I can confirm that on a development version of the Vienna History Wiki, this problem also occurs. So it is definitely a bug related to the upgrade to MW 1.35.

**Comment by kghbln** [comment]
Thanks for your info.

**Comment by gesinn-it** [comment]
@markmuzenhardt can you please check, if PR #685 fixes you issue
