### ISSUE TITLE
Cannot merge a pull request

### ISSUE THREAD

**Issue by alex-mashin** [SemanticMediaWiki/SemanticResultFormats#674]
Cannot merge pull request #675.

Scrutinizer test does not run.

```
Waiting for External Code Coverage    61:50
Waits for external service to send code coverage to Scrutinizer.
The code coverage data was not received within the specified time. Please make sure your third-party service is configured to send code coverage data.

Code coverage data is not yet available.
Code Coverage was not sent to Scrutinizer.
Make sure that you have set-up your external service correctly.
You can find more information on this in the documentation:

    https://scrutinizer-ci.com/docs/tools/external-code-coverage/

If you need help you can also email support@scrutinizer-ci.com.
```
https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticResultFormats/inspections/5296be6c-b321-40fb-b5c1-f1274e4f0a1b

**Comment by alex-mashin** [comment]
And now checks of #676 are still pending.

**Comment by alex-mashin** [comment]
Another hanging pull request: https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/pull/170.

**Comment by gesinn-it** [comment]
Thanks @alex-mashin for your contributions! I'd like to get CI and coverage working again. This makes it easier to accept PRs.

**Comment by alex-mashin** [comment]
> Thanks @alex-mashin for your contributions! I'd like to get CI and coverage working again. This makes it easier to accept PRs.

I have corrected the unit test for this format.

**Comment by alex-mashin** [comment]
The PR in question have been merged.
