### ISSUE TITLE
Require MW 1.35+

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticResultFormats#682]
Current master requires MW 1.35+ (#621). This should imho already be prepared regardless of a release to avoid surprises if someone uses dev-master with older wikis.

- [x] Update CI matrix
- [x] Update README.md
- [ ] Update extension.json
- [x] Update RELEASE-NOTES.md → 3.3.0 will never be released but 4.0.0

@kghbln @JeroenDeDauw did I miss something in the list above?

**Comment by JeroenDeDauw** [comment]
Looks good to me

**Comment by kghbln** [comment]
What about SRF 4.0.0?

**Comment by gesinn-it-gea** [comment]
I think #448 should definitely be fixed before SRF 4.0.0. See details there.

**Comment by kghbln** [comment]
Okay, will sit tight.
