### ISSUE TITLE
[CI] SMW@dev-master Class 'SMW\Test\QueryPrinterRegistryTestCase' not found

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticResultFormats#689]
### Setup

- mediawiki_version: '1.36'
- semantic_mediawiki_version: dev-master
- mermaid_version: dev-master

### Issue
Error: Class 'SMW\Test\QueryPrinterRegistryTestCase' not found

https://github.com/SemanticMediaWiki/SemanticResultFormats/runs/4358830580?check_suite_focus=true#step:8:10

ping @hexmode

**Comment by hexmode** [comment]
This is actually [fixed](https://github.com/SemanticMediaWiki/SemanticResultFormats/runs/4361535169?check_suite_focus=true) in 97f4d0b12b6a15a40c68821e771da4e7d22d9fc9.
