### ISSUE TITLE
Some issue with jqplotchart

### ISSUE THREAD

**Issue by Bagrat1on** [SemanticMediaWiki/SemanticResultFormats#696]
### Setup

- MW version: 1.35.5
- MySQL: 5.7.27-30
- PHP version: 7.4.14 (cgi-fcgi)
- SMW version: 3.2.3
- SRF version: 3.2.0

### Issue

Hi, I am a new SMW and SRF user and need some help!
I tried to repeat an example of a chart from [here](https://www.semantic-mediawiki.org/wiki/Demo:Jqplotchart/Population) but it does not work for my wiki and I don't know why.

**Steps to reproduce**

I have a [[Category:City]] and 4 cities inside: Berlin, Munchen, London, Moskow.
Each city page have similar text:
```
[[Located in::Germany]]
[[Population::1234979]]  
[[Average rainy days::130]]
[[Area::87600]]
[[Category:City]]
```
On page of Category:City I write:
`{{#ask:[[Category:City]] | ?Population | ?Average rainy days | ?Area}}`
and have a result:
![image](https://user-images.githubusercontent.com/6755827/147404945-036a4273-1513-471e-b70b-4e48cf613cd8.png)
It's working, but when I try to use a chart:
```
{{#ask:[[Category:City]]
|?Population
|format=jqplotchart
|link=all
|headers=show
|searchlabel=… further results
|distributionsort=none
|direction=vertical
|numbersaxislabel=Population
|height=400
|width=50%
|valueformat=%d
|ticklabels=1
|theme=simple
|filling=1
|chartlegend=none
|datalabels=percent
|charttype=bar
}}
```
I have a warning about data:
**"Warning
The requested data cannot be displayed due to insufficient selection criteria."(c) Translator**
But when a add **|distribution=yes** to parameters, I have:
![image](https://user-images.githubusercontent.com/6755827/147405000-2ae18d7b-e62f-4c04-b535-3615a785588d.png)
The same problem with other charts formats excluding googlepie and googlebar - they are working well. I think the problem is in data format, but I can't be sure and don't know how to fix it.
Please help me to solve this problem.
[Link to my test wiki](http://u1559308.isp.regruhosting.ru/index.php?title=%D0%9A%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D1%8F:City) on temporary hosting (becoz [sandbox](https://sandbox.semantic-mediawiki.org) is not avaible).
I'm newbee on Git and if I was wrong in the place for my simple question - please tell me where to go.

**Comment by JeroenDeDauw** [comment]
Looks like your properties are not of type number. Hence the red numbers (with links to non-existing pages) in the table. Properties are of type page by default and they should be of type number for your.

**Comment by Bagrat1on** [comment]
> Looks like your properties are not of type number. Hence the red numbers (with links to non-existing pages) in the table. Properties are of type page by default and they should be of type number for your.

Thank you!
I didn't even know properties have types.
