### ISSUE TITLE
Unused dependency to `symfony/css-selector` packages

### ISSUE THREAD

**Issue by osnard** [SemanticMediaWiki/SemanticResultFormats#710]
Current version (4.0.1) declared a dependency to `symfony/css-selector` in version 3.3 [1]. Can you tell me about its purpose? I have searched the code but did not find any reference to a class of function provided by this library. Could it be removed?

I am asking, because the version constraint is pretty low, thus it may collide with higher requirements by other extensions.

[1] https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/4.0.1/composer.json#L52

**Comment by JeroenDeDauw** [comment]
This dependency was added in https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/6077519d4

Please verify it is no longer used.

**Comment by osnard** [comment]
I have checked the codebase as of https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/6077519d4
Looks like it was only used in the file `./tests/phpunit/Integration/JSONScript/HtmlValidator.php`. This file does no longer exist in the codebase.

```
$ SemanticResultFormats (6077519d…) > grep -rn Symfony .
./tests/phpunit/Integration/JSONScript/HtmlValidator.php:6:use Symfony\Component\CssSelector\CssSelectorConverter;
```
$ SemanticResultFormats (master) > grep -rn Symfony .
# No output
```

Apparently this file was removed in https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/88098144cb970f3d0f121407896e5d2c822e69a2
