### ISSUE TITLE
[pagewidget] carousel not working

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticResultFormats#724]
### Setup

MediaWiki | 1.35.6
-- | --
PHP | 7.4.3 (fpm-fcgi)
MariaDB | 10.3.34-MariaDB-0ubuntu0.20.04.1
ICU | 66.1
Semantic MediaWiki | 4.0.2 | GPL-2.0-or-later | Ermöglicht es, das Wiki zugänglicher zu machen – für Menschen und Maschinen 
Semantic Result Formats | 4.0.1

### Issue

Instead of the widget, a widget spinner is shown that never stops. The following errors are shown:

Wikicode used:
`{{#ask: [[Category:XYZ]] 
|format=pagewidget
|link=all
|embedformat=ul
|widget=carousel
}}`

```
The resource from “extensions/CIForms/select2/select2.full.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
Loading failed for the <script> with source “extensions/CIForms/select2/select2.full.js?”.
The resource from “extensions/CIForms/select2/select2.min.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
The resource from “extensions/CIForms/style.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
The resource from “extensions/CIForms/validation.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

**Comment by krabina** [comment]
It has to do with chameleon skin. When I use vector, it is working.

**Comment by kghbln** [comment]
Good that we at least tracked it down to SRF and Chameleon.

**Comment by krabina** [comment]
According to https://github.com/ProfessionalWiki/chameleon/issues/346 this should be resolved in SRFl, not in Chameleon.
