### ISSUE TITLE
slideshow format broken

### ISSUE THREAD

**Issue by mitchelln** [SemanticMediaWiki/SemanticResultFormats#75]
Hi.

I've just upgraded a wiki to 1.23.7 from 1.19.5 and the slideshow format no longer works. I have:

{{#ask:
[[Category:Snippets]] 
[[Snippet Type::Did You Know]]
| ?Headline
| ?Description
| order=random
| format=slideshow
| effect=none
| delay=7
| limit=15
| width=210px
| height=110px
| mainlabel=-
| template=Slide Format
}}

and nothing is displayed anymore. SMW is version 2 and SRF is version 2. All installed via Composer.

Thanks.

**Comment by jaideraf** [comment]
This error has been reported here: https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/56

**Comment by kghbln** [comment]
Closing this as a dupe as referenced in the last post.
