### ISSUE TITLE
Translation issue with message MediaWiki:Srf-paramdesc-carousel-slick-option/qqq

### ISSUE THREAD

**Issue by verdy-p** [SemanticMediaWiki/SemanticResultFormats#753]
URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=srf-paramdesc-carousel-slick-option&group=mwgithub-semanticresultformats&language=qqq

See the FIXME added in the documentation of this message. For now the translation is not clear, and the doc is insufficient. This is a new message, so it may still be in beta (just like the carousel visualization widget which has demos in the SMW wiki, but none of them using any "slick option", and none of them for the "table" output format but only for galeries).

These carousel widgets also have other unsolved maintenance issues listed in GitHub (if changes are made, this could alter the behavior or layout, and would require change in the documentation of this feature).

For now it's not clear how to translate "slick", but I suppose this means that it controls whever the carrousel slides smoothly from page to page, or instantly. All existing demos for now seem to use a smooth ("slick"?) sliding behavior by default. But "slick" also has another meaning in English (as a name), and may refer to a layout rather than a sliding behavior.

Other possible layout or behavior (for galleries) would use a freely sliding area (working like a scrollbar, where the content could still be loaded on demand, when it becomes visible, or fully preloaded), instead of using "paged" results. And MediaWiki also featuers its own galleries, that are "playable" in full screen, paged image by image, to show all images used in any page. In-content galleries also feature various layouts (using vertical scrolling if needed, but not requiring any javascript addon). Getting galleries with enhanced layouts or behavior is still a work ni progress, not just in SMW but in Mediawiki in general. It is also sensitive in terms of usability/accessibility, and in terms of cross-browser and cross-device compatibility. Other sites (notably search engines, photo-based social networks, dating sites & apps, but also merchant sites for listing their products) also propose their own layouts and behaviors for showing and navigating across large image galleries.

**Comment by kghbln** [comment]
@krabina @thomas-topway-it This is about pull https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/730

If you just explain in a short sentence what is slick about the slick option.... I could update the system message docu on twn.

**Comment by thomas-topway-it** [comment]
Slick is the Javascript library on which the carousel format is based

https://github.com/kenwheeler/slick

all the slick's options are supported using the prefix slick- in parameters, for instance slick-autoplaySpeed

**Comment by verdy-p** [comment]
This is now clearer. Thanks for improving the doc (and probably you should include a link pointing to the slick documentation, eventually as well in the message to be translated within some "tvar" if it's not just in the "/qqq" page: users of the translated tool may also wonder what it is on how to use it).

**Comment by kghbln** [comment]
I just looked closer at this. To be honest: In general, all system messages belonging to the respective pull are more or less meaningless for translators. If you have not used the result format you will have no clue how to translate. I just translated something based on educated guesses however I am pretty sure... I will create a pull to mitigate this issue.

**Comment by verdy-p** [comment]
I would have loved to use it, but such commit without any test or demo page
me as that such messages are un likely to be useful for now in any
translation, even in English. Effectively we have no clue about what they
mean as no one knows how such thing can be used, or eve' if it will be used
as is. Such thing intended to be an alpha version to be evaluated is very
likely to be changed without having been used, or tested and evaluated.
However the way it is described is as new options added in pages that are
in production, for its UI and not just as internal technical
implémentations details for debogging or support purpose

And there are alsi différent possible options for implementing carousels of
images, including those already implemented in MediaWiki for its galeries
or when we clic or tap on an image thumbnail in wiki pages. So users are
already accustomized to one way, and this merits some reflection to make
cohérent choices and integration. For now there were some separate gadgets,
but starting to integrate one of them to early without making a review of
the existant seems prematured when there are also other pending unsolved
bugs related to image carousels. One of thembeung thé fact that the
previous solution ceased to be supported, and other possilble alternatives
have not benn evaluated also for their maintenance at longer term: is that
the only solution ? Shouldn't #730 remain in a alpha branch instead of the
trunk ?

**Comment by thomas-topway-it** [comment]
hello, I've checked.
Sure, the messages in qqq.json related to the new carousel format are unclear or incomplete. 
As soon as possible I will add some documentation here

https://www.semantic-mediawiki.org/wiki/Help:Carousel_format

and in the same time I will update the qqq messages.
best
