### ISSUE TITLE
jqplotchart label error with DistributionResults and link != none

### ISSUE THREAD

**Issue by thomas-topway-it** [SemanticMediaWiki/SemanticResultFormats#782]
### Setup

- MW version: 1.35.8
- DB (MySQL etc.): MariaDB 10.3.38
- PHP version: 7.4.3-4ubuntu2.19 (fpm-fcgi)
- SMW version: 4.1.0
- SRF version: 4.1.0-beta
- Browsers and versions (if applicable):

### Issue
A query like the following 
```

{{#ask:[[Category:Correspondence]][[Numismatic keyword::+]]           
|?Numismatic keyword# 
|format=jqplotchart
|charttype=bar   
|direction=horizontal
|mainlabel=-
|limit=5000
|link=all
|headers=show
|charttitle=Numismatic keywords
|highlighter=yes
|datalabels=value
|valueformat=%d
|theme=simple
|chartlegend=
|distribution=yes
|distributionsort=asc
|min=10
|labelaxislabel=minimum 10
|height=3000
}}
```
displays linked labels, as follows  
![screencapture-fjqplotchart-linkall-error](https://github.com/SemanticMediaWiki/SemanticResultFormats/assets/46287689/b7256f80-90fd-4114-8460-0242c8865c8b)

This is caused by 
`$value = $dataValue->getShortText( $outputMode, $this->getLinker( false ) );`

SMW's `AggregatablePrinter` -> `getDistributionResults`

`getLinker` should be forced to return null, since the labels are never clickable in the **jqplot** format

**Comment by thomas-topway-it** [comment]
hello @gesinn-it-gea can you also confirm from your side that the statement "labels are never clickable in the jqplot format" is true for all the following chart types "bar", "line", "pie", "donut" ?
Also, what about `SRFjqPlotSeries` ? (this is not affected by the commit since they extend different classes)

**Comment by gesinn-it-gea** [comment]
In fact, I had only glanced at the pull request. Are the formats mentioned above also affected by your PR?

**Comment by thomas-topway-it** [comment]
only those handled in the class `SRFjqPlotChart`

**Comment by gesinn-it-gea** [comment]
I can not say something about the other chart types. You would have to test this.

**Comment by thomas-topway-it** [comment]
I have tested, so the error shows only for bar and line, however none of them are clickable. I will check `SRFjqPlotSeries` later, however this is not affected by the pull request

**Comment by thomas-topway-it** [comment]
I confirm that `SRFjqPlotSeries` does not need any update since the linker is already not passed as parameter, see

```
} elseif ( $object->getDataItem()->getDIType() == SMWDataItem::TYPE_TIME ) {
	$label = $object->getShortWikiText();
} else {
	$label = $object->getWikiValue();
}
```
`SRFjqPlotSeries` -> `getResultData`

this also confirms that it is correct to override the $linker to null in the current pull request for SRFjqPlot
