### ISSUE TITLE
Logspam: Premature access to service container 

### ISSUE THREAD

**Issue by octfx** [SemanticMediaWiki/SemanticResultFormats#794]
I'm seeing the following log spam with MW 1.39.5
> Premature access to service container [Called from SemanticResultFormats::registerHooks in /var/www/html/extensions/SemanticResultFormats/SemanticResultFormats.php at line 56] in /var/www/html/includes/debug/MWDebug.php on line 381

This seems to be introduced by #792

**Comment by JeroenDeDauw** [comment]
@Seb35

**Comment by alistair3149** [comment]
We got the same log spam as well from #792 
![image](https://github.com/SemanticMediaWiki/SemanticResultFormats/assets/9260542/bd92c815-50f2-42fa-be88-affb5e745ed1)

**Comment by krabina** [comment]
I can also confirm this.

**Comment by Sophivorus** [comment]
Me too.

**Comment by D-Groenewegen** [comment]
Thanks @Sophivorus for the fix. 

I would just like to add that the issue has a potentially greater impact than simply overwhelming the logs. In my case, it also threw a SyntaxError in the browser's console (relating to a stray angle bracket) and disabled certain Bootstrap components such as dropdowns that come with the Chameleon skin. An unfortunate side-effect but one can be remedied using Sophivorus's fix.

**Comment by kghbln** [comment]
I assume this issue is done. The related commit should be in 4.1.3. Please reopen if there is still an issue.

**Comment by D-Groenewegen** [comment]
The commit actually post-dates the latest release (v4.2.0), which should probably be avoided. Anyway, the important thing now is that it's part of master.

**Comment by kghbln** [comment]
Ah, this is SRF. Indeed, it has not been released yet.
