### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by YOUR1** [SemanticMediaWiki/SemanticResultFormats#796]
I'm waiting for the next release, since the last one from march doesn't have the latest fixes.

**Comment by krabina** [comment]
Maybe we should remove result formats that are still there in the source code, but are not supported anymore?
IMO these are 
- exhibit
- jitgraph
(the old datatables version has been removed already)

**Comment by krabina** [comment]
Furthermore, we should include

- #786 (already reviewed)
- #784 
- #697 

@YOUR1 you could help with looking at 784 and 697 and leave a comment there.

**Comment by JeroenDeDauw** [comment]
Last release was in october https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/RELEASE-NOTES.md

**Comment by JeroenDeDauw** [comment]
I would not block making a release on new stuff. You can always make another release after said new stuff gets in.

**Comment by kghbln** [comment]
> Last release was in October https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/RELEASE-NOTES.md

The tag is missing though.

**Comment by kghbln** [comment]
I just tagged the release and published the release.

**Comment by kghbln** [comment]
Please ping me once I can do the next release. Currently, when looking at the release notes it looks like a 4.1.1
