### ISSUE TITLE
 Deprecated: Premature access to service container 

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticResultFormats#797]
### Setup

- MW version: 1.39.5
- DB (MySQL etc.):
- PHP version: 7.4
- SMW version: 4.1.2
- SRF version: 4.1.0-beta (
- Browsers and versions (if applicable):

### Issue

on a wiki upgraded from 1.35 to 1.39 (with the same versions of SMW and SRF), I get this deprecation notice:

```
PHP Deprecated:  Premature access to service container [Called from SemanticResultFormats::registerHooks in /mediawiki/extensions/SemanticResultFormats/SemanticResultFormats.php at line 56] in /var/www/html/mediawiki/includes/debug/MWDebug.php on line 381
```
Does not seem to affect functionality, is just a deprecation notice.

**Comment by octfx** [comment]
See also #794 :)

**Comment by krabina** [comment]
duplicate, thus closing
