### ISSUE TITLE
Eventcalendar rendering problem with class

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticResultFormats#8]
http://sourceforge.net/mailarchive/message.php?msg_id=31856789

**Comment by mwjames** [comment]
> I have also a problem with the "class" of the eventcalendar : I tried to set the height to 100px but 

`min-height` is specified as `350px` anything else will not work for the event calendar,

Using an external class with a height attribute should work after 46b18e5a35ca13d8f877155a20bcd8b207bc9101 and a5b89b358d5732156ad13c94738a14cc8b3fec20.
