### ISSUE TITLE
Tagging 2.1

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#83]
@JeroenDeDauw @mwjames What about doing a release now. Do not see real blockers but nice improvements Now that SMW 2.1 is out.

**Comment by JeroenDeDauw** [comment]
Fine from my side, but then I don't really know what's been going on.

I can create the tag and do a rel mail if you want.

**Comment by mwjames** [comment]
> Do not see real blockers but nice improvements Now that SMW 2.1 is out.

I fixed some 1.24+ jQuery incompatibility issues but it might be that there are still some around (I haven't checked whether all formats are working correctly on smw.org or not).

**Comment by kghbln** [comment]
Since SMW was advertised as compatible with MW 1.24 and this branch was release too it might not hurt to release now and do SRF 2.1.1 etc. as the issues arise

**Comment by JeroenDeDauw** [comment]
#85
