### ISSUE TITLE
result format "gallery" does no longer play with "image_auth.php"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#84]
After upgrading private wikis from SRF 1.8 to 2.0 the setting  
``$wgUploadPath = "$wgScriptPath/img_auth.php";``

starts to prevent the files from being fetched due to a 403 permission error. So SRF does not longer seem to know what it is acting as a "logged in" user.

**Comment by mwjames** [comment]
Nothing has changed here, especially for this like `$wgUploadPath = "$wgScriptPath/img_auth.php";`. Where do you maintain `$wgUploadPath = "$wgScriptPath/img_auth.php";` and what is expected?

**Comment by mwjames** [comment]
Just looked at the code and the gallery doesn't make any assumptions about `$wgUploadPath` it receives the title objects which supposed to be in `NS_FILE` and uses the information to create an `ImageGallery` object.

**Comment by kghbln** [comment]
Hmm, `$wgUploadPath = "$wgScriptPath/img_auth.php";` is set in "LocalSettings.php" with an additional mod_alisas defined for the vhost. However it may be that MW 1.23 introduced an issue here as it did for files ending with JPG as opposed to jpg and I have not been told before. Hold on a sec. I will investigate.

**Comment by mwjames** [comment]
> with an additional mod_alisas defined for the vhost.

When I read this you already lost me (not my field of expertise).

**Comment by kghbln** [comment]
No worries, if I managed to grasp this ... However, this is apparently not the issue here. It turns out that I messed up with the mod_alias in the vhost which worked in previous versions of MW but not in 1.23. After fixing this it turns out that SFR is working allrighty. This issue was just not reported to me before.
