### ISSUE TITLE
Inline ask-query with format=datatable broken

### ISSUE THREAD

**Issue by robinwiel** [SemanticMediaWiki/SemanticResultFormats#842]
### Setup

- MW version: 1.39.7
- DB (MySQL etc.): mysql v15.1 Distrib 10.3.39-MariaDB
- PHP version: 7.4
- SMW version: 4.1.3
- SRF version: 4.2.1 (5515deb47810365aa2fc51406cd8905d307e6fa3)

### Issue

Running an inline ask-query with the result format "datatable" suddenly gives no results.
Additionally, running the same query on Special:Ask with the result format "datatable" does not give any result either.

The used query condition is of the form `[[Category:Foo]]`. 
When using SemanticResultsFormat on branch master with this commit (https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/23f535b059de66859a758a79d9f1a48ce8135d3d) seems to work just fine, and the ask-query shows the results as it should.

However, when running on the commit after the aforementioned commit (https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/5515deb47810365aa2fc51406cd8905d307e6fa3) seems to break the query and does not give any results.

**Steps to reproduce**

(recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org))

1. Ensure there is at least one page in Category:Foo
2. Copy the inline ask query below to a page:
```
{{#ask: [[Category:Foo]]
 |format=datatable
 |limit=10
 |link=all
}}
```
3. Save the page

**Expected result:** a DataTable showing all the pages in the category Foo.

**Observed result:** an empty DataTable with the text "No data available in table"

### Suspicion
We suspect the error is in https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/5515deb47810365aa2fc51406cd8905d307e6fa3/formats/datatables/Hooks.php#L74

The variables `wgSmQMaxLimit` and `wgSmQMaxInlineLimit` do not exist (@gesinn-it-ilm). Semantic MediaWiki uses the variables `smwgQMaxLimit` and `smwgQMaxInlineLimit`.

Since a lot of variable names have been changed in this commit, it might be necessary to run more checks...

**Comment by YOUR1** [comment]
Those are SMW variables; they should not be changed at all. 

Also it's weird to have this kind of commits where you change logic of stuff, while you're fixing things so the unit tests don't fail.

[/rant off]
