### ISSUE TITLE
Empty config getters in multiple classes

### ISSUE THREAD

**Issue by robinwiel** [SemanticMediaWiki/SemanticResultFormats#843]
### Setup

- MW version: 1.39.7
- DB (MySQL etc.): mysql v15.1 Distrib 10.3.39-MariaDB
- PHP version: 7.4
- SMW version: 4.1.3
- SRF version: 4.2.1 (5515deb47810365aa2fc51406cd8905d307e6fa3)

### Issue

There are five occurrences in the code of the form `$this->getConfig()->get();` where the function `get()` is missing an argument. This was caused by commit https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/5515deb47810365aa2fc51406cd8905d307e6fa3.

This results in fatal errors.

#### Locations
https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/5515deb47810365aa2fc51406cd8905d307e6fa3/formats/datatables/Api.php#L240

https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/5515deb47810365aa2fc51406cd8905d307e6fa3/formats/datatables/Api.php#L279

https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/5515deb47810365aa2fc51406cd8905d307e6fa3/formats/datatables/Api.php#L280

https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/5515deb47810365aa2fc51406cd8905d307e6fa3/formats/datatables/Api.php#L359

https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/5515deb47810365aa2fc51406cd8905d307e6fa3/formats/slideshow/SRF_SlideShowApi.php#L178

**Comment by gesinn-it-ilm** [comment]
This is fixed within PR number 844.
