### ISSUE TITLE
Remove support for MW 1.35

### ISSUE THREAD

**Issue by paladox** [SemanticMediaWiki/SemanticResultFormats#876]
This extension should probably remove support for MW 1.35 and bump the requirement to MW 1.39+

**Comment by gesinn-it-gea** [comment]
@gesinn-it-ilm will remove 1.35 from CI, as coverage is broken since https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/855/files. Instead 1.40 will be added to CI as this is the next version that supports creating coverage reports

**Comment by gesinn-it-ilm** [comment]
This is done and part of PR #884.
