### ISSUE TITLE
Outline format: add support for a "template=" parameter

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticResultFormats#88]
Moved here from: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/849
- 'outline' format - add support for a "template=" parameter, similar to the ones found in various other formats. [independent]

**Comment by davidforgianni** [comment]
Related to #87

**Comment by kghbln** [comment]
@yaronkoren FYI since you were the original author
