### ISSUE TITLE
Coverage report not uploaded because no report found

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticResultFormats#880]
For example, see: https://github.com/SemanticMediaWiki/SemanticResultFormats/actions/runs/12381061707/job/34558773962?pr=878#step:6:47

@gesinn-it-ilm can you please have a look what's going wrong
CC: @paladox

**Comment by gesinn-it-ilm** [comment]
@gesinn-it-gea I will check it now.

**Comment by gesinn-it-ilm** [comment]
This is fixed and covered within the support for MW 1.40. 
The fix is a part of PR #884.
