### ISSUE TITLE
MW 1.40 - 4.2.0 overrules dev-master while running CI

### ISSUE THREAD

**Issue by gesinn-it-ilm** [SemanticMediaWiki/SemanticResultFormats#882]
When try to run CI using MW 1.40 and SMW to be set as `dev-master`, for some reason `4.2.0` SMW still being used. 

**MW 1.40 matrix:**

```
 mediawiki_version: '1.40'
 smw_version: dev-master
 php_version: 8.1
 database_type: mysql
 database_image: "mariadb:11.2"
 coverage: false
 experimental: true

```
Looks like `require` section in `composer.json` forces Composer to use version `4.2.0` instead of `dev-master`.
Check the line here - [composer.json](https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/2aba7d2bd991002d9af353658eaea08c810372b7/composer.json#L49)

Possible solution could be to add `dev-master` to `require` section like: 
`"mediawiki/semantic-media-wiki": "~3.0|~4.0|~5.0|dev-master"`.

cc: @paladox, @JeroenDeDauw

**Comment by paladox** [comment]
@gesinn-it-gea did that change fix it for you?

**Comment by gesinn-it-gea** [comment]
At @paladox: you mean if #883 fixed the issue?

**Comment by paladox** [comment]
> At @paladox: you mean if #883 fixed the issue?

Yup

**Comment by gesinn-it-ilm** [comment]
I will recheck it as well on my side to confirm if it works.

**Comment by gesinn-it-ilm** [comment]
Support for MW 1.40 added, the issue fixed by addind `dev-master` to `require` section in `composer.json`.
Now CI has support for MW 1.39 and MW 1.40, both using SMW 'dev-master' version.

SMW 'dev-master' is only temp solution until new SMW tag `5.0.0` is released.

cc: @paladox, @JeroenDeDauw
