### ISSUE TITLE
Ploticus format: fix the security leak in this (currently-disabled) format

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticResultFormats#89]
Moved here from: SemanticMediaWiki/SemanticMediaWiki#849

* 'ploticus' format - fix the security leak in this (currently-disabled) format. [independent]

**Comment by JeroenDeDauw** [comment]
Last edit to the code was 3 years ago when I moved it to a new directory. Thinking we should probably just remove it.

@yaronkoren @mwjames @SemanticMediaWiki/testers Any reasons to keep this?

**Comment by kghbln** [comment]
I think that this format was originally provided by @jqnatividad If so he might also have a comment.

**Comment by kghbln** [comment]
I guess it indeed makes no sense to keep this. In case somebody wants to provide a format using ploticus she or he could still retrieve the code from earlier version to build on for a future implementation if necessary.

**Comment by kghbln** [comment]
See https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/163
