### ISSUE TITLE
Extract formats into their own packages?

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticResultFormats#92]
Now that we have composer, would it make sense to maintain result formats separately and have SRF just pull them in?

One advantage would be, that it would make it possible to update SRF and keep selected formats at some lower version, e.g. to not have to update all the #asks in case some fundamental change took place for some format. 

Another one would be that people could install just selected formats instead of the whole package (for that we would probably need some SRFBase package).

**Comment by JeroenDeDauw** [comment]
I think this makes maintenance more costly, and suspect it's actually more annoying for most users as well. Right now they'd need to find all the package names and appropriate versions. That could be remedied with some additional infrastructure which we do not yet have.

**Comment by s7eph4n** [comment]
Probably not. Closing this.
