### ISSUE TITLE
Datatables: URL type destroys complete table

### ISSUE THREAD

**Issue by formwandler** [SemanticMediaWiki/SemanticResultFormats#93]
This issue occurs in _Datatables_ format: As soon as I add a property to a query from type <code>URL</code>, the table is not displayed at all (the loading icon just appears).

Example:
<code>
|?my_link=Link
</code>

Property definition of _my_link_:
<code>
This is a property of type [[Has type::URL]].
</code>

My system (even though the issue occured also in earlier versions):
- MW 1.24.1
- SMW: 2.1
- SRF: 2.1.1
- SF: 3.0
- SFI: 0.9.0

**Comment by mwjames** [comment]
I can't confirm this observation using a query with [0] does displays results as expected [1].

```
{{#ask: [[Has video url::+]][[Has video type::!conference]]
 |?Has video url=Source
 |?Has description=Description
 |?Has video type=Type
 |mainlabel=-
 |format=datatables
 |limit=100
}}
```

[0] https://semantic-mediawiki.org/wiki/Property:Has_video_url
[1] https://semantic-mediawiki.org/wiki/Video_collection

>  (the loading icon just appears)

You encountered a JavaScript issue, for details see [2].

[2] https://semantic-mediawiki.org/wiki/Semantic_Result_Formats#FAQ

**Comment by formwandler** [comment]
Okay, thanks for the feedback. If I query just for the properties like in your query, then it works in deed.

But in my query I use a inverse subobject query like:
<code>
{{#ask: [[-Has subobject::MyPage]][[my_title::+]]
|?my_title=Title
|?my_link=Link
|format=datatables
|mainlabel=-
|sort=my_title
|order=ascending
}}
</code>

Once I remove [[-Has subobject::MyPage]], the query works. But I need the subobject query, which does not work as soon as I want to display the URL property.

**Comment by mwjames** [comment]
For an inverse subobject query I can't confirm your observation [0] either. Does your query work with the normal `table` format?

```
{{#ask:[[-Has subobject::Demo:Event_calendar:2012/09/12]]
|?Has event start
|format=datatables
|link=all
|headers=show
|searchlabel=... further results
|class=sortable wikitable smwtable
|theme=bootstrap
}}
```
[0] https://semantic-mediawiki.org/w/index.php?title=Special%3AAsk&q=[[-Has+subobject%3A%3ADemo%3AEvent_calendar%3A2012%2F09%2F12]]&po=%3FHas+event+start%0D%0A&eq=yes&p[format]=datatables&sort_num=&order_num=ASC&p[limit]=&p[offset]=&p[link]=all&p[sort]=&p[headers]=show&p[mainlabel]=&p[intro]=&p[outro]=&p[searchlabel]=...+further+results&p[default]=&p[class]=sortable+wikitable+smwtable&p[theme]=bootstrap&eq=yes#

**Comment by formwandler** [comment]
Yes, ```table``` format works in all my cases.

Your subobject query example does not return data from type _URL_ - or do I miss something?

Very strange, the "regular" ask query (without "Has subobject"), I confirmed to work, does soemtimes work - sometimes not.

**Comment by mwjames** [comment]
I don`t really have time to look at this issue unless for a clear indication of what needs to be changed (in the JS source) or a reproducible use case on smw.org.

@kghbln Now the sandbox would come in handy!

**Comment by formwandler** [comment]
Yes, I understand. Don't worry. I am not a JavaScript guru and my time is limited as well. But maybe I can create a use case for reproducing it once I have some time. Anyway, thanks for you help.

**Comment by kghbln** [comment]
> @kghbln Now the sandbox would come in handy!

I was able to reproduce on our [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Issue/93SRF)

**Comment by krabina** [comment]
I am running into this problem in 

Software | Version
-- | --
MediaWiki | 1.35.6
PHP | 7.4.3 (fpm-fcgi)
MariaDB | 10.3.34-MariaDB-0ubuntu0.20.04.1
ICU | 66.1
Semantic MediaWiki | 4.0.2
Semantic Result Formats | 4.0.2 (e13794c) 08:01, 30 September 2022

The SRF version is from our upgraded [datatables PR](https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/730)

Since we still don't have the sandbox back up, can somebody else confirm that this bug still exists (also in the current master or SRF)?
