### ISSUE TITLE
Adding own formats to SRF without touching SRF files

### ISSUE THREAD

**Issue by DestructionOfPlanetJupiter** [SemanticMediaWiki/SemanticResultFormats#94]
We have a format that is not available in the SRF formats, but is currently been used on one of our sites and it works within the SRF environment. The problem is that several of the files had been changed in order to get the format working:
- SemanticResultsFormats.php (adding the format to $formatClasses)
- SemanticResultFormats.settings.php (adding it to the function registerUnitTests)
- SemanticResultFormats.settings.php (adding it to the srfgFormats array)

It would be nice to be able to add something to the SRF extension without having to touch any of the files set one's own format up like one would do it with a normal extension. 

It would be nice to have some guidance in this regard and maybe point to some way of dealing with this issue.

**Comment by JeroenDeDauw** [comment]
Rather than stuffing your new format into SRF, just create your own mini extension for it. All you have to do in there is register the format with SMW via the same mechanism as SRF itself uses.
