### ISSUE TITLE
"I was blindly following the installation instructions"

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticResultFormats#95]
> OK, will do. Thanks! I was blindly following the instructions here which say 1.9.*. Am I missing something or do those instructions need updating? 

See, https://semantic-mediawiki.org/wiki/Talk:Semantic_Result_Formats#blockUI_requires_jQuery_v1.3_or_later.21__You_are_using_v1.11.1_1636

**Comment by JeroenDeDauw** [comment]
???

**Comment by kghbln** [comment]
Fixed with [this diff on smw.o](https://semantic-mediawiki.org/w/index.php?title=Semantic_Result_Formats&curid=350&diff=37790&oldid=37124). The instructions were indeed very version centric. Should probably have a look at Maps and Semantic Maps, too.
