### ISSUE TITLE
Eventcalendar : my new events are not showing up

### ISSUE THREAD

**Issue by pierro78** [SemanticMediaWiki/SemanticResultFormats#97]
I have added an event ( http://wiki.plateforme-tests.gentilsvirus.org/index.php/Testppp ) that happens on friday 27 of march but it doesn't show up in my eventcalendar ( http://wiki.plateforme-tests.gentilsvirus.org/index.php/Cat%C3%A9gorie:Evenements ) ... 
... it's not working for my new events but it s working for some other users though ...

(this is a test wiki, you can test it in any way you want ...)

**Comment by mwjames** [comment]
I just had a quick look, if you adjust your limit setting then the alleged event appears. It is all about setting the correct condition/query context and ensure that the parser output doesn't interfere (for that see [0, 1] to mitigate the issue).

[0] https://semantic-mediawiki.org/wiki/Help:User_preferences

[1] https://semantic-mediawiki.org/wiki/Demo:Event_calendar#Notes

**Comment by pierro78** [comment]
thanks , I have also set  $smwgQMaxInlineLimit in LocalSettings.php ( as indicated in https://semantic-mediawiki.org/wiki/Semantic_Result_Formats#FAQ ) , and it seems to work now :)
