### ISSUE TITLE
jqplotchart and jqplotseries format

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticResultFormats#98]
Then looking at the `$wgIncludejQueryMigrate` setting in the [installation instructions](https://semantic-mediawiki.org/wiki/Semantic_Result_Formats#Installation) I come to think that both formats will not be available for MW 1.25+ since the [jqPlot library](https://bitbucket.org/cleonello/jqplot/commits/all/) is no longer maintained and probably does not work with jQery 1.11.1 Is this assumption correct?

**Comment by mwjames** [comment]
> Then looking at the $wgIncludejQueryMigrate setting in the installation instructions I come to think that both formats will not be available for MW 1.25+ 

Never used the ` $wgIncludejQueryMigrate` setting.

We use our own little helper [0] to not depend on MW which should work past the MW 1.25 / ` $wgIncludejQueryMigrate` setting.

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/resources/jquery/ext.jquery.migration.browser.js

**Comment by kghbln** [comment]
A great, thank you for your insight to this. I presume that this buys us time till 2020. I will remove the info about the `wgIncludejQueryMigrate` setting to avoid confusion for our users. Thanks again!
